<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Maria Tackett">
<title>4&nbsp; Simple linear regression – Introduction to Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-slr-inference.html" rel="next">
<link href="./03-eda.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-31c3c5ec0f84e3846e28bd1517aa8340.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script defer="" data-domain="https://matackett.github.io/regression-book/" src="https://plausible.io/js/script.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-slr.html">Part 2: Simple linear regression</a></li><li class="breadcrumb-item"><a href="./04-slr.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simple linear regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Regression Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/matackett/regression-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 1: Getting started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression in the data science workflow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-review-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data analysis in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 2: Simple linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-slr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-slr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inference for simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-slr-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model conditions and diagnostics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 3: Multiple linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-mlr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for multiple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-mlr-transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variable transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-model-eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model selection</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 4: Beyond linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-logistic-prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Logistic regression: Prediction and evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-special-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Special topics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathematics of linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Mathematics of logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Data sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#sec-slr-intro" id="toc-sec-slr-intro" class="nav-link" data-scroll-target="#sec-slr-intro"><span class="header-section-number">4.1</span> Introduction: Movie ratings</a></li>
  <li>
<a href="#sec-slr-eda" id="toc-sec-slr-eda" class="nav-link" data-scroll-target="#sec-slr-eda"><span class="header-section-number">4.2</span> Exploratory data analysis</a>
  <ul class="collapse">
<li><a href="#univariate-eda" id="toc-univariate-eda" class="nav-link" data-scroll-target="#univariate-eda"><span class="header-section-number">4.2.1</span> Univariate EDA</a></li>
  <li><a href="#bivariate-eda" id="toc-bivariate-eda" class="nav-link" data-scroll-target="#bivariate-eda"><span class="header-section-number">4.2.2</span> Bivariate EDA</a></li>
  </ul>
</li>
  <li>
<a href="#sec-fit-regression" id="toc-sec-fit-regression" class="nav-link" data-scroll-target="#sec-fit-regression"><span class="header-section-number">4.3</span> Linear regression</a>
  <ul class="collapse">
<li><a href="#sec-slr-specify" id="toc-sec-slr-specify" class="nav-link" data-scroll-target="#sec-slr-specify"><span class="header-section-number">4.3.1</span> Statistical (theoretical) model</a></li>
  <li><a href="#sec-slr-appropriate" id="toc-sec-slr-appropriate" class="nav-link" data-scroll-target="#sec-slr-appropriate"><span class="header-section-number">4.3.2</span> Evaluating whether SLR is appropriate</a></li>
  </ul>
</li>
  <li>
<a href="#sec-slr-estimation" id="toc-sec-slr-estimation" class="nav-link" data-scroll-target="#sec-slr-estimation"><span class="header-section-number">4.4</span> Estimating the model coefficients</a>
  <ul class="collapse">
<li><a href="#sec-least-squares" id="toc-sec-least-squares" class="nav-link" data-scroll-target="#sec-least-squares"><span class="header-section-number">4.4.1</span> Least squares regression</a></li>
  </ul>
</li>
  <li><a href="#sec-slr-interpret-coef" id="toc-sec-slr-interpret-coef" class="nav-link" data-scroll-target="#sec-slr-interpret-coef"><span class="header-section-number">4.5</span> Interpreting the model coefficients</a></li>
  <li><a href="#sec-slr-predict" id="toc-sec-slr-predict" class="nav-link" data-scroll-target="#sec-slr-predict"><span class="header-section-number">4.6</span> Prediction</a></li>
  <li>
<a href="#sec-model-assessment" id="toc-sec-model-assessment" class="nav-link" data-scroll-target="#sec-model-assessment"><span class="header-section-number">4.7</span> Model evaluation</a>
  <ul class="collapse">
<li><a href="#root-mean-square-error" id="toc-root-mean-square-error" class="nav-link" data-scroll-target="#root-mean-square-error"><span class="header-section-number">4.7.1</span> Root Mean Square Error</a></li>
  <li><a href="#sec-slr-sum-sq" id="toc-sec-slr-sum-sq" class="nav-link" data-scroll-target="#sec-slr-sum-sq"><span class="header-section-number">4.7.2</span> Analysis of variance and <span class="math inline">\(R^2\)</span></a></li>
  </ul>
</li>
  <li>
<a href="#sec-slr-R" id="toc-sec-slr-R" class="nav-link" data-scroll-target="#sec-slr-R"><span class="header-section-number">4.8</span> Simple linear regression in R</a>
  <ul class="collapse">
<li><a href="#sec-slr-fit-R" id="toc-sec-slr-fit-R" class="nav-link" data-scroll-target="#sec-slr-fit-R"><span class="header-section-number">4.8.1</span> Fitting the least-squares model</a></li>
  <li><a href="#prediction" id="toc-prediction" class="nav-link" data-scroll-target="#prediction"><span class="header-section-number">4.8.2</span> Prediction</a></li>
  <li><a href="#r2-and-rmse" id="toc-r2-and-rmse" class="nav-link" data-scroll-target="#r2-and-rmse"><span class="header-section-number">4.8.3</span> <span class="math inline">\(R^2\)</span> and RMSE</a></li>
  </ul>
</li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">4.9</span> Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/matackett/regression-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-slr.html">Part 2: Simple linear regression</a></li><li class="breadcrumb-item"><a href="./04-slr.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simple linear regression</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-ch-slr" class="quarto-section-identifier"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="learning-goals" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="learning-goals">Learning goals</h2>
<ul>
<li>Use exploratory data analysis to assess whether a simple linear regression is an appropriate model to describe the relationship between two variables</li>
<li>Estimate the slope and intercept for a simple linear regression model</li>
<li>Interpret the slope and intercept in the context of the data</li>
<li>Use the model to compute predictions and residuals</li>
<li>Evaluate model performance using RMSE and <span class="math inline">\(R^2\)</span>
</li>
<li>Conduct simple linear regression using R</li>
</ul></section><section id="sec-slr-intro" class="level2" data-number="4.1"><h2 data-number="4.1" class="anchored" data-anchor-id="sec-slr-intro">
<span class="header-section-number">4.1</span> Introduction: Movie ratings</h2>
<p>Reviews from movie critics can be helpful when determining whether a movie is high quality and well-made; however, it can sometimes be challenging to determine whether regular audience members will like a movie based on critics reviews. We would like a way to better understand the relationship between what movie critics and regular movie goers think about a movie, and ultimately predict how an audience will rate a movie based on its score from movie critics.</p>
<p>To do so, we will analyze data that contains the critics scores and audience scores for 146 movies released in 2014 and 2015. The scores are for every movie released in these years that have “a rating on Rotten Tomatoes, a RT User rating, a Metacritic score, a Metacritic User score, an IMDb score, and at least 30 fan reviews on Fandango” <span class="citation" data-cites="fivethirtyeight">(<a href="references.html#ref-fivethirtyeight" role="doc-biblioref">Albert Y. Kim, Ismay, and Chunn 2018a</a>)</span>. The analysis in this chapter focuses on scores from <a href="#0">Rotten Tomatoes</a>, a website for information and ratings on movies and television shows. The data were originally analyzed in the article “Be Suspicious of Online Movie Ratings, Especially Fandango’s” <span class="citation" data-cites="hickey2015suspicious">(<a href="references.html#ref-hickey2015suspicious" role="doc-biblioref">Hickey 2015</a>)</span> on the former data journalism website <a href="#0">FiveThirtyEight</a>. The data are available in <code>movie_scores.csv</code>. The data set was adapted from the <code>fandago</code> data frame in the <strong>fivethirtyeight</strong> R package <span class="citation" data-cites="kim2018fivethirtyeight">(<a href="references.html#ref-kim2018fivethirtyeight" role="doc-biblioref">Albert Y. Kim, Ismay, and Chunn 2018b</a>)</span>.</p>
<p>We will focus on two variables for this analysis:</p>
<ul>
<li><p><code>critics_score</code>: The percentage of critics who have a favorable review of the movie. This is known as the “Tomatometer” score on the Rotten Tomatoes website. The possible values are 0 - 100.</p></li>
<li><p><code>audience_score</code>: The percentage of users (regular movie-goers) on Rotten Tomatoes who have a favorable review of the movie. The possible values are 0 - 100.</p></li>
</ul>
<div class="objective">
<p>Our goal is to use simple linear regression to model the relationship between the critics score and audience score. We want to use the model to</p>
<ul>
<li>describe how the audience score is expected to change as the critics score changes.</li>
<li>predict the audience score for a movie based on its critics score.</li>
</ul>
</div>
<p>Recall from <a href="01-intro.html#sec-what-is-regression" class="quarto-xref"><span>Section 1.1.1</span></a>, the <strong>response variable</strong> is the outcome of interest, meaning the variable we are interested in predicting and understanding its variability. It is also known as the <em>outcome</em> or <em>dependent variable</em> and is represented as <span class="math inline">\(Y\)</span>. The <strong>predictor variable(s)</strong> is the variable (or variables) used to understand variability in the response. It is also known as the <em>explanatory</em> or <em>independent variable</em> and represented as <span class="math inline">\(X\)</span>. The observed values of the response and predictor are represented as <span class="math inline">\(y_i\)</span> and <span class="math inline">\(x_i\)</span>, respectively.</p>
<div class="yourturn">
<p>What is the response variable for the movie scores analysis? What is the predictor variable?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
</section><section id="sec-slr-eda" class="level2" data-number="4.2"><h2 data-number="4.2" class="anchored" data-anchor-id="sec-slr-eda">
<span class="header-section-number">4.2</span> Exploratory data analysis</h2>
<p>Recall from <a href="03-eda.html" class="quarto-xref"><span>Chapter 3</span></a> that we begin analysis with <strong>exploratory data analysis (EDA)</strong> to better understand the data, the distributions of key variables, and relationships in the data before fitting the regression model. The exploratory data analysis here focuses on the two variables that will be in the regression model, <code>critics</code> and <code>audience</code>. In practice, however, we may want to explore other variables in the data set (for example, <code>year</code> in this analysis) to provide additional context later on as we interpret results from the regression model. We begin with univariate EDA (<a href="03-eda.html#sec-univar-eda" class="quarto-xref"><span>Section 3.4</span></a>), exploring one variable at a time, then we’ll conduct bivariate EDA (<a href="03-eda.html#sec-bivar-eda" class="quarto-xref"><span>Section 3.5</span></a>) to look at the relationship between the critics scores and audience scores.</p>
<section id="univariate-eda" class="level3" data-number="4.2.1"><h3 data-number="4.2.1" class="anchored" data-anchor-id="univariate-eda">
<span class="header-section-number">4.2.1</span> Univariate EDA</h3>
<p>The univariate distributions of <code>critics_score</code> and <code>audience_score</code> are visualized in <a href="#fig-movies-univariate" class="quarto-xref">Figure&nbsp;<span>4.1</span></a> and summarized in <a href="#tbl-movies-univariate" class="quarto-xref">Table&nbsp;<span>4.1</span></a>.</p>
<div class="cell">
<div id="fig-movies-univariate" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-movies-univariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="fig-movies-univariate-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-movies-univariate-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="04-slr_files/figure-html/fig-movies-univariate-1.png" class="lightbox" data-gallery="fig-movies-univariate" title="Figure&nbsp;4.1&nbsp;(a): Critics score"><img src="04-slr_files/figure-html/fig-movies-univariate-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-movies-univariate"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-movies-univariate-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Critics score
</figcaption></figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-movies-univariate-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-movies-univariate-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="04-slr_files/figure-html/fig-movies-univariate-2.png" class="lightbox" data-gallery="fig-movies-univariate" title="Figure&nbsp;4.1&nbsp;(b): Adience score"><img src="04-slr_files/figure-html/fig-movies-univariate-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-movies-univariate"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-movies-univariate-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Adience score
</figcaption></figure>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-movies-univariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.1: Univariate distributions of <code>critics_score</code> and <code>audience_score</code>
</figcaption></figure>
</div>
</div>
<div class="cell">
<div id="tbl-movies-univariate" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-movies-univariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4.1: Summary statistics for <code>critics_score</code> and <code>audience_score</code>
</figcaption><div aria-describedby="tbl-movies-univariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Median (Q2)</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">critics_score</td>
<td style="text-align: right;">60.8</td>
<td style="text-align: right;">30.2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">31.2</td>
<td style="text-align: right;">63.5</td>
<td style="text-align: right;">89</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">audience_score</td>
<td style="text-align: right;">63.9</td>
<td style="text-align: right;">20.0</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">66.5</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The distribution of <code>critics_score</code> is left-skewed, meaning the movies in the data set are generally more favorably reviewed by critics (more observations with higher critics scores). Given the apparent skewness, the center is best described by the median score of 63.5 points. The interquartile range (IQR), the spread of the middle 50% of the distribution, is 57.8 points <span class="math inline">\((Q_3 - Q_1 = 89 - 31.2)\)</span>, so there is a lot of variability in the critics scores for the movies in the data. There are no apparent outliers, but we observe from the raw data that there are two notable observations of movies that have perfect critics scores of 100. There are no missing values of critics score.</p>
<div class="yourturn">
<p>Use the histogram in <a href="#fig-movies-univariate-2" class="quarto-xref">Figure&nbsp;<span>4.1 (b)</span></a> and summary statistics in <a href="#tbl-movies-univariate" class="quarto-xref">Table&nbsp;<span>4.1</span></a> to describe the distribution of the response variable <code>audience_score</code>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
</section><section id="bivariate-eda" class="level3" data-number="4.2.2"><h3 data-number="4.2.2" class="anchored" data-anchor-id="bivariate-eda">
<span class="header-section-number">4.2.2</span> Bivariate EDA</h3>
<p>Now let’s look at the relationship between <code>critics_score</code> and <code>audience_score</code>. From <a href="03-eda.html#sec-bivar-quant-eda" class="quarto-xref"><span>Section 3.5.1</span></a>, we use visualizations and summary statistics to examine the relationship between two quantitative variables. A scatterplot of the the audience score versus critics score is shown in <a href="#fig-movies-bivariate" class="quarto-xref">Figure&nbsp;<span>4.2</span></a>. The predictor variable is on the <span class="math inline">\(x\)</span>-axis (horizontal axis), and the response variable is on the <span class="math inline">\(y\)</span>-axis (vertical axis).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-movies-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-movies-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="04-slr_files/figure-html/fig-movies-bivariate-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;4.2: Scatterplot of critics_score and audience_score"><img src="04-slr_files/figure-html/fig-movies-bivariate-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-movies-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.2: Scatterplot of <code>critics_score</code> and <code>audience_score</code>
</figcaption></figure>
</div>
</div>
</div>
<p>There is a positive, linear relationship between the critics scores and audience scores for the movies in our data. The correlation between these two variables is 0.78, indicating the relationship is strong. Therefore, we can generally expect the audience score to be higher for movies with higher critics scores. There are no apparent outliers, but there does appear to be more variability in the audience score for movies with lower critics scores than for those with higher critics scores.</p>
</section></section><section id="sec-fit-regression" class="level2" data-number="4.3"><h2 data-number="4.3" class="anchored" data-anchor-id="sec-fit-regression">
<span class="header-section-number">4.3</span> Linear regression</h2>
<p>In <a href="#sec-slr-eda" class="quarto-xref"><span>Section 4.2</span></a>, we used visualizations and summary statistics to describe the relationship between two variables. The exploratory data analysis, however, does not tell us what the audience score is predicted to be for a given value of the critics score or how much the audience score is expected to change as the critics score changes. Therefore, we will fit a linear regression model to quantify the relationship between the two variables. Recall the general form of the linear regression model in <a href="01-intro.html#eq-parametric-model" class="quarto-xref">Equation&nbsp;<span>1.3</span></a>. More specifically, when we have one predictor variable, we will fit a model of the form</p>
<p><span id="eq-slr"><span class="math display">\[
Y = \beta_0 + \beta_1 X + \epsilon \hspace{8mm} \epsilon \sim N(0, \sigma^2_{\epsilon})
\tag{4.1}\]</span></span></p>
<p><a href="#eq-slr" class="quarto-xref">Equation&nbsp;<span>4.1</span></a>, called a <strong>simple linear regression (SLR) model</strong>, is the equation to model the relationship between one quantitative response variable and one predictor variable. For now we will focus on models with one quantitative predictor variable. In later chapters, we will introduce models with two or more predictors (<a href="07-mlr.html" class="quarto-xref"><span>Chapter 7</span></a>), categorical predictors (<a href="07-mlr.html#sec-mlr-interpret-categorical" class="quarto-xref"><span>Section 7.4.2</span></a>), and models with a categorical response variable (<a href="11-logistic.html" class="quarto-xref"><span>Chapter 11</span></a>).</p>
<p>We are generally interested in using regression models for two types of tasks:</p>
<ul>
<li>
<strong>Prediction:</strong> Finding the expected value of the response variable for given values of the predictor variable(s).</li>
<li>
<strong>Inference:</strong> Drawing conclusions about the relationship between the response and predictor variables.</li>
</ul>
<div class="yourturn">
<p>Suppose we fit a simple linear regression line to summarize the relationship between <code>critics_score</code> and <code>audience_scores</code> for movies.</p>
<ul>
<li>What is an example of a <strong>prediction</strong> question that can be answered using a simple linear regression model?</li>
<li>What is an example of an <strong>inference</strong> question that can be answered using a simple linear regression model?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>
</li>
</ul>
</div>
<section id="sec-slr-specify" class="level3" data-number="4.3.1"><h3 data-number="4.3.1" class="anchored" data-anchor-id="sec-slr-specify">
<span class="header-section-number">4.3.1</span> Statistical (theoretical) model</h3>
<p>We expand on the concepts introduced in <a href="01-intro.html#sec-what-is-regression" class="quarto-xref"><span>Section 1.1.1</span></a> for the simple linear regression model. Suppose there is a response variable <span class="math inline">\(Y\)</span> and a predictor variable <span class="math inline">\(X\)</span>. The values of the response variable <span class="math inline">\(Y\)</span> can be generated in the following way:</p>
<p><span id="eq-slr-step0"><span class="math display">\[
Y = \text{Model} + \text{Error}
\tag{4.2}\]</span></span></p>
<p>More specifically, we define the model as a function of the predictor <span class="math inline">\(X\)</span>, <span class="math inline">\(\text{Model} = f(X)\)</span>, and error <span class="math inline">\(\epsilon\)</span>, such that</p>
<p><span id="eq-general-model-2"><span class="math display">\[
Y = f(X) + \epsilon
\tag{4.3}\]</span></span></p>
<p>The function <span class="math inline">\(f(X)\)</span> that describes the relationship between the response and predictor variables is the <strong>regression model</strong>. This is the model we will fit in later sections using equations and software. The error, <span class="math inline">\(\epsilon\)</span>, is how much the actual value of the response <span class="math inline">\(Y\)</span> deviates from the value produced by the regression model, <span class="math inline">\(f(X)\)</span>. <!--# Maybe add the piece from the glm book about stochastic part / random part?-->There is some randomness in <span class="math inline">\(\epsilon\)</span>, because not all observations with the same value of <span class="math inline">\(X\)</span> have the same value of <span class="math inline">\(Y\)</span>. For example, not all movies with a critics score of 70 have the same audience score.</p>
<p><a href="#eq-general-model-2" class="quarto-xref">Equation&nbsp;<span>4.3</span></a> is the general form of the equation to generate values of <span class="math inline">\(Y\)</span> given values of <span class="math inline">\(X\)</span>. In the context of simple linear regression, the function <span class="math inline">\(f(X)\)</span> in <a href="#eq-general-model-2" class="quarto-xref">Equation&nbsp;<span>4.3</span></a> is</p>
<p><span id="eq-slr-function"><span class="math display">\[
f(X) = \mu_{Y|X} = \beta_0 + \beta_1X
\tag{4.4}\]</span></span></p>
<p>where <span class="math inline">\(\mu_{Y|X}\)</span> is the mean value of <span class="math inline">\(Y\)</span> at a particular value of <span class="math inline">\(X\)</span>, and <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the model coefficients. The error terms <span class="math inline">\(\epsilon\)</span> from <a href="#eq-general-model-2" class="quarto-xref">Equation&nbsp;<span>4.3</span></a> are normally distributed with a mean of 0 and variance <span class="math inline">\(\sigma_{\epsilon}^2\)</span>, represented as <span class="math inline">\(N(0, \sigma^2_{\epsilon})\)</span> (more on this in <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a>. The specification of the simple linear regression model written in terms of individual observations <span class="math inline">\((x_i, y_i)\)</span> is</p>
<p><span id="eq-slr-complete"><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i \hspace{7mm} \epsilon_i \sim N(0, \sigma_{\epsilon}^2)
\tag{4.5}\]</span></span></p>
<p>such that <span class="math inline">\(y_i\)</span> is the response for the <span class="math inline">\(i^{th}\)</span> observation, <span class="math inline">\(x_i\)</span> is he predictor for the <span class="math inline">\(i^{th}\)</span> observation, and <span class="math inline">\(\epsilon_i\)</span> is the error for the <span class="math inline">\(i^{th}\)</span> observation. <a href="#eq-slr-complete" class="quarto-xref">Equation&nbsp;<span>4.5</span></a> is the <strong>statistical model</strong>, also called the <em>data-generating model</em> or <em>population-level model</em>. It is the theoretical form of the model that describes exactly how to generate the values of the response <span class="math inline">\(Y\)</span> given values of the predictor in the population. The model coefficients are the intercept <span class="math inline">\(\beta_0\)</span> and the slope <span class="math inline">\(\beta_1\)</span>. The<span class="math inline">\(\sigma^2_{\epsilon}\)</span> is called the standard error. In practice we don’t know the exact values of <span class="math inline">\(\beta_0\)</span>, <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\sigma_{\epsilon}^2\)</span>, so our goal is to use sample data to estimate these values. We will focus on the coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in this chapter. We discuss estimating <span class="math inline">\(\sigma^2_{\epsilon}\)</span> in <a href="05-slr-inference.html#sec-estimate-reg-std-err" class="quarto-xref"><span>Section 5.8.2</span></a>.</p>
<div class="yourturn">
<p>In simple linear regression, we use sample data to estimate a model to understand trends in the population.</p>
<p>What is the population in the movie scores analysis? What is the sample?<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <em>Recall the definition of population and sample in <a href="01-intro.html#sec-regression-analysis" class="quarto-xref"><span>Section 1.1</span></a>.</em></p>
</div>
</section><section id="sec-slr-appropriate" class="level3" data-number="4.3.2"><h3 data-number="4.3.2" class="anchored" data-anchor-id="sec-slr-appropriate">
<span class="header-section-number">4.3.2</span> Evaluating whether SLR is appropriate</h3>
<p>Before doing any more calculations, we need to determine if the simple linear regression model is a reasonable choice to summarize the relationship between the response variable and predictor variable based on what we know about the data and what we’ve observed from the exploratory data analysis. Determining this early on can help prevent going in a wrong analysis direction if a linear regression model is obviously not a good choice for the data.</p>
<p>We can ask the following questions to evaluate whether simple linear regression is appropriate:</p>
<ul>
<li>Will a linear regression model be practically useful? Does quantifying and interpreting the relationship between the variables make sense in this scenario?</li>
<li>Is the shape of the relationship reasonably linear?</li>
<li>Do the observations in the data represent the population of interest, or are there biases in the data that could limit conclusions drawn from the analysis? <!--# Differentiate this from the first two bullet points. Make clear if the first two points are violated, we definitely shouldn't do SLR. If this one is violated, we can still do SLR but need to be mindful about the scope of conclusions.-->
</li>
</ul>
<p>Mathematical equations or statistical software can be used to fit a linear regression model between any two quantitative variables. Therefore it is upon the judgment of the data scientist to determine if it is reasonable to proceed with a linear regression model or if doing so might result in misleading conclusions about the data. If the answer is “no” to any of the questions above, consider if a different analysis technique is better for the data, or proceed with caution if using regression. If we proceed with regression, be transparent about some of the limitations of the conclusions.</p>
<p>From <a href="#sec-slr-intro" class="quarto-xref"><span>Section 4.1</span></a>, the goal of this analysis is understand the relationship between the critics scores and audience score for movies on Rotten Tomatoes. Therefore, there is a practical use for fitting the regression model. We observed from <a href="#fig-movies-bivariate" class="quarto-xref">Figure&nbsp;<span>4.2</span></a> that the relationship between the two variables is approximately linear, so it could reasonably be summarized a model of the form of <a href="#eq-slr-complete" class="quarto-xref">Equation&nbsp;<span>4.5</span></a>. Lastly, the data set includes all movies in 2014 and 2015 that has a sufficient number of ratings on popular movie ratings websites, so we can reasonably conclude the sample is representative of the population of movies on Rotten Tomatoes. Therefore, we are comfortable drawing conclusions about the population based on the analysis of our sample data. <!--# Not sure if this last point is a leap--></p>
<p>The form of the simple linear regression model for the movie scores data is</p>
<p><span id="eq-movies-stat-model"><span class="math display">\[
\text{audience\_score} = \beta_0 + \beta_1~\text{critics\_score} + \epsilon, \hspace{5mm}\epsilon  \sim N(0, \sigma^2_{\epsilon})
\tag{4.6}\]</span></span></p>
<p>Now that we have the form of the model, let’s discuss how to estimate and interpret the model coefficients, the slope <span class="math inline">\(\beta_1\)</span> and the intercept <span class="math inline">\(\beta_0\)</span>. We will estimate <span class="math inline">\(\sigma^2_{\epsilon}\)</span> in <a href="05-slr-inference.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
</section></section><section id="sec-slr-estimation" class="level2" data-number="4.4"><h2 data-number="4.4" class="anchored" data-anchor-id="sec-slr-estimation">
<span class="header-section-number">4.4</span> Estimating the model coefficients</h2>
<p>Ideally, we would have data from the entire population of movies rated on Rotten Tomatoes in order to calculate the exact values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>. In reality we don’t have access to the data from the entire population, but we can use the sample to obtain the estimated <strong>regression equation</strong> in <a href="#eq-regression" class="quarto-xref">Equation&nbsp;<span>4.7</span></a></p>
<p><span id="eq-regression"><span class="math display">\[
\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1x_i
\tag{4.7}\]</span></span></p>
<p>where <span class="math inline">\(\hat{\beta}_0\)</span> is the estimated intercept, <span class="math inline">\(\hat{\beta}_1\)</span> is the estimated slope, and <span class="math inline">\(\hat{y}_i\)</span> is the predicted (estimated) response.</p>
<p>Specifically for the movie scores analysis, the estimated regression equation is</p>
<p><span id="eq-movies-slr"><span class="math display">\[
\widehat{\text{audience\_score}}_i = 32.316 + 0.519~\text{critics\_score}_i
\tag{4.8}\]</span></span></p>
<p>In this equation 32.316 is <span class="math inline">\(\hat{\beta}_0\)</span>, the estimated value for the intercept, 0.519 is <span class="math inline">\(\hat{\beta}_1\)</span>, the estimated value for the slope <span class="math inline">\(\beta_1\)</span>, and <span class="math inline">\(\widehat{\text{audience\_score}}_i\)</span> is the expected audience score when the critics score is equal to <span class="math inline">\(\text{critics\_score}_i\)</span>. Notice that <a href="#eq-regression" class="quarto-xref">Equation&nbsp;<span>4.7</span></a> and <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a> do not have have error term, <span class="math inline">\(\epsilon\)</span>. The output from the regression equation is <span class="math inline">\(\hat{f(X)} = \hat{\mu}_{Y|X}\)</span>, the expected <em>mean</em> value of the response given a value of the predictor. Therefore, when we discuss the values of the response estimated using simple linear regression, what we are really talking about is what the value of the response variable is expected to be, <em>on average</em>, for a given value of the predictor variable.</p>
<p>From <a href="#fig-movies-bivariate" class="quarto-xref">Figure&nbsp;<span>4.2</span></a>, we know that the value of the response is not necessarily the same for all observations with the same value of the predictor. For example, we wouldn’t expect (nor do we observe) the same audience score for every movie with a critics score of 70. We know there are other factors other than the critics score that are related to how an audience reacts to a movie. Our analysis, however, only takes into account the critics score, so we do not capture these additional factors in our regression equation <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>. This is where the error terms come back in.</p>
<p>Once we computed estimates <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> for the regression equation, we can calculate how far the predicted values of the response produced by the regression equation differ from the actual values of the response variable observed in the data. This difference is called the <strong>residual</strong>, denoted <span class="math inline">\(e_i\)</span>. <!--# Introduce residuals before explicitly before estimating the regression line. Maybe it's own subsection?--></p>
<!--# Key terms box: The residual is the difference between the observed and predicted values of the response for a given observation.-->
<p><a href="#eq-residual" class="quarto-xref">Equation&nbsp;<span>4.9</span></a> shows the equation of the residual for the <span class="math inline">\(i^{th}\)</span> observation.</p>
<p><span id="eq-residual"><span class="math display">\[
e_i = \text{observed}_i - \text{predicted}_i =  y_i - \hat{y}_i
\tag{4.9}\]</span></span></p>
<p>In the case of the movie scores data, the residual is the difference between the actual audience score and the audience score predicted by <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>. For example, the 2015 movie <em>Avengers: Age of Ultron</em> received a critics score of <span class="math inline">\(y_i = 74\)</span>. Therefore, using <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>, the estimated (predicted) audience score is.</p>
<p><span class="math display">\[
\hat{y}_i = 32.316 + 0.519 \times 74 = 70.722.
\]</span></p>
<p>The observed audience score is 86, so the residual is</p>
<p><span class="math display">\[
e_i = y_i - \hat{y}_i = 86 - 70.722 = 15.278
\]</span></p>
<div class="yourturn">
<p>Would you rather see a movie that has a positive or negative residual? Explain your response.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</div>
<section id="sec-least-squares" class="level3" data-number="4.4.1"><h3 data-number="4.4.1" class="anchored" data-anchor-id="sec-least-squares">
<span class="header-section-number">4.4.1</span> Least squares regression</h3>
<p>There are many possible regression lines (infinitely many, in fact) that we could use to summarize the relationship between <code>critics_score</code> and <code>audience_scores</code>. We see some fo the potential lines represented in <a href="#fig-many-lines" class="quarto-xref">Figure&nbsp;<span>4.3</span></a>. So how did we determine the line that “best” fits the data is the one described by <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>? We’ll use the residuals to help us answer this question.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-many-lines" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-many-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="04-slr_files/figure-html/fig-many-lines-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4.3: Potential regression lines for the relationship between critics_score and audience_score"><img src="04-slr_files/figure-html/fig-many-lines-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-many-lines-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.3: Potential regression lines for the relationship between <code>critics_score</code> and <code>audience_score</code>
</figcaption></figure>
</div>
</div>
</div>
<p>The residuals, represented by the vertical dotted lines in <a href="#fig-scatterplot-resid" class="quarto-xref">Figure&nbsp;<span>4.4</span></a>, are a measure of the “error”, the difference between the observed value of the response and the value predicted from a regression model. The line that “best” fits the data is the one that generally results in the smallest overall error. One way to find the line with the smallest overall error is to add up all the residuals for each possible line in <a href="#fig-many-lines" class="quarto-xref">Figure&nbsp;<span>4.3</span></a> and choose the one that has the smallest sum. Notice, however, that for lines that seem to closely align with the trend of the data, there is approximately equal distribution of points above and below the line. Thus as we’re trying to compare lines that pretty closely fit the data, we’d expect the residuals to add up to a value very close to zero. This would make it difficult, then, to determine a best fit line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatterplot-resid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-scatterplot-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="04-slr_files/figure-html/fig-scatterplot-resid-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;4.4: Regression line of the relationship between critics_score and audience_score with residuals"><img src="04-slr_files/figure-html/fig-scatterplot-resid-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatterplot-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.4: Regression line of the relationship between <code>critics_score</code> and <code>audience_score</code> with residuals
</figcaption></figure>
</div>
</div>
</div>
<p>Instead of using the sum of the residuals, we will instead consider the sum of the squared residuals in <a href="#eq-sum-sq-resid" class="quarto-xref">Equation&nbsp;<span>4.10</span></a></p>
<p><span id="eq-sum-sq-resid"><span class="math display">\[
\sum_{i=1}^n e_i^2 = e_1^2 + e_2^2 + \dots + e_n^2
\tag{4.10}\]</span></span></p>
<p>where <span class="math inline">\(n\)</span> is the number of observations in the data. The line that “best” fits the data, then, is the line that minimizes <a href="#eq-sum-sq-resid" class="quarto-xref">Equation&nbsp;<span>4.10</span></a>. This is called the <strong>least squares regression model.</strong></p>
<!--# Key terms box: The least squares regression line is the line, $\hat{\beta}_0 + \hat{\beta}_1 ~X$ , that minimizes the sum of the squared residuals.-->
<!-- add something about why not the absolute value-->
<p>Let’s expand <a href="#eq-sum-sq-resid" class="quarto-xref">Equation&nbsp;<span>4.10</span></a>. Recall that <span class="math inline">\(e_i\)</span>, the residual of the <span class="math inline">\(i^{th}\)</span> observation, is <span class="math inline">\(y_i - \hat{y}_i\)</span> where <span class="math inline">\(\hat{y}_i\)</span> is the estimated response. Then,</p>
<p><span id="eq-least-sq-pt1"><span class="math display">\[
\begin{aligned}
e_i &amp;= y_i - \hat{y}_i \\
&amp;= y_i - (\hat{\beta}_0 + \hat{\beta}_1x_i)
\end{aligned}
\tag{4.11}\]</span></span></p>
<p>Thus, putting <a href="#eq-least-sq-pt1" class="quarto-xref">Equation&nbsp;<span>4.11</span></a> into <a href="#eq-sum-sq-resid" class="quarto-xref">Equation&nbsp;<span>4.10</span></a>, we have</p>
<p><span id="eq-least-sq-pt2"><span class="math display">\[
\begin{aligned}
\sum_{i=1}^n e_i^2 &amp;= e_1^2 + e_2^2 + \dots + e_n^2 \\
&amp;= [y_1 - (\hat{\beta}_0 + \hat{\beta}_1x_1)]^2 + [y_2 - (\hat{\beta}_0 + \hat{\beta}_1x_2)]^2 + &amp; \\
&amp; \dots + [y_n - (\hat{\beta}_0 + \hat{\beta}_1x_n)]^2
\end{aligned}
\tag{4.12}\]</span></span></p>
<p>Using calculus, the <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> that minimize <a href="#eq-least-sq-pt2" class="quarto-xref">Equation&nbsp;<span>4.12</span></a> are</p>
<p><span id="eq-least-sq-estimates"><span class="math display">\[
\hat{\beta}_1 = r\frac{s_Y}{s_X} \hspace{10mm} \hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}
\tag{4.13}\]</span></span></p>
<p>where <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(\bar{y}\)</span> are the mean values of the predictor and response variables, respectively, <span class="math inline">\(s_X\)</span> and <span class="math inline">\(s_Y\)</span> are the standard deviations of the predictor and response variables, respectively, and <span class="math inline">\(r\)</span> is the correlation between the response and predictor variables. See <a href="appendix-linear.html#sec-least-sq-math" class="quarto-xref">Appendix&nbsp;<span>A.1</span></a> for the full details of the derivation from <a href="#eq-least-sq-pt2" class="quarto-xref">Equation&nbsp;<span>4.12</span></a> to <a href="#eq-least-sq-estimates" class="quarto-xref">Equation&nbsp;<span>4.13</span></a>.</p>
<p><a href="#eq-slr-computations" class="quarto-xref">Equation&nbsp;<span>4.14</span></a> show the calculations of slope and intercept for the movie scores model based on the summary statistics in <a href="#tbl-movies-univariate" class="quarto-xref">Table&nbsp;<span>4.1</span></a>. Note that the small differences in the values compared to <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a> are due to rounding (versus coefficients computed by software).</p>
<p><span id="eq-slr-computations"><span class="math display">\[
\begin{aligned}
\hat{\beta}_1 &amp;= 0.78 \times \frac{20.0}{30.2} = 0.517 \\ \hat{\beta}_0 &amp;=  63.9 - 0.517 \times  60.8 = 32.467
\end{aligned}
\tag{4.14}\]</span></span></p>
<div class="analysis_in_practice">
<p>Below are a few properties of least-squares regression models.</p>
<ul>
<li><p>The regression line goes through the center of mass point, the coordinates corresponding to average <span class="math inline">\(X\)</span> and average <span class="math inline">\(Y\)</span>: <span class="math inline">\(\hat{\beta}_0 = \bar{y} - \hat{\beta}_1\bar{x}\)</span></p></li>
<li><p>The slope has the same sign as the correlation coefficient: <span class="math inline">\(\hat{\beta}_1 = r\frac{s_Y}{s_X}\)</span></p></li>
<li><p>The sum of the residuals is zero: <span class="math inline">\(\sum_{i=1}^n e_i = 0\)</span></p></li>
<li><p>The residuals and values of the predictor are uncorrelated</p></li>
</ul>
</div>
</section></section><section id="sec-slr-interpret-coef" class="level2" data-number="4.5"><h2 data-number="4.5" class="anchored" data-anchor-id="sec-slr-interpret-coef">
<span class="header-section-number">4.5</span> Interpreting the model coefficients</h2>
<p>The <strong>slope</strong> <span class="math inline">\(\hat{\beta}_1\)</span> is the estimated change in the response for each unit increase in the predictor variable. What do we mean by “estimated change”? Recall that the output from the regression equation is <span class="math inline">\({\mu}_{Y|X}\)</span> the estimated mean of the response <span class="math inline">\(Y\)</span> for a given value of the predictor <span class="math inline">\(X\)</span>. Thus, the slope or the “steepness” of the regression line, is a measure of how much the response variable is expected to change, on average, for each unit increase of the predictor.</p>
<p>It is good practice to write the interpretation of the slope in the context of the data, so that it can be more easily understood by others reading the analysis results. “In the context of the data” means that the interpretation includes</p>
<ul>
<li>meaningful descriptions of the variables, if the variable names would be unclear to an outside reader</li>
<li>units for each variable</li>
<li>an indication of the population for which the model applies.</li>
</ul>
<p>The slope in <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a> of 0.519 is interpreted as the following:</p>
<blockquote class="blockquote">
<p><em>For each additional point in the critics score, the audience score for movies on Rotten Tomatoes is expected to increase by 0.519 points, on average.</em></p>
</blockquote>
<p>The <strong>intercept</strong> is the estimated value of the response variable when the predictor variable equals zero <span class="math inline">\((x_i = 0)\)</span>. On a scatterplot of the response and predictor variable, this is the point where the regression line crosses the <span class="math inline">\(y\)</span>-axis. Similar to the slope, the “estimated value” is more specifically the estimated mean value of the response variable when the predictor equals 0 ( <span class="math inline">\(\hat{\mu}_{Y|X = 0})\)</span>.</p>
<p>The intercept in <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a> of 32.316 is interpreted as the following:</p>
<blockquote class="blockquote">
<p><em>The expected audience score for movies on Rotten Tomatoes with a critics score of 0 is 32.316 points.</em></p>
</blockquote>
<p>We always need to estimate the intercept in <span class="quarto-unresolved-ref">?eq-regressio</span> to get the line that best fit using least squares regression. The intercept, however, does not always have a meaningful interpretation. We ask the following questions to determine if the intercept has a meaningful interpretation:</p>
<ol type="1">
<li><p>Is it plausible for the predictor variable to take values at or near zero?</p></li>
<li><p>Are there observations in the data with values of the predictor at or near zero?</p></li>
</ol>
<p>If the answer to either question is no, then it is not meaningful, and potentially misleading, to interpret the intercept.</p>
<div class="yourturn">
<p>Is the interpretation of the intercept in <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a> meaningful? Briefly explain.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</div>
<div class="analysis_in_practice">
<p>Avoid using causal language and making declarative statements (e.g., “The audience score for a movie with a critics score of 0 points <u><strong>will</strong></u> be 32.316 points.”) when interpreting the slope and intercept. Remember the slope and intercept are estimates describing what is <u><strong>expected</strong></u>in the relationship between the response and predictor to be based on the sample data and linear regression model. They do not tell us exactly what will happen in the data.</p>
<p><br><br>
There is an area of statistics called <em>causal inference</em> about model that can be used to make causal statements from observational (non-experimental) data. See <a href="13-special-topics.html#sec-causal" class="quarto-xref"><span>Section 13.4</span></a> for a brief introduction to causal inference.</p>
</div>
</section><section id="sec-slr-predict" class="level2" data-number="4.6"><h2 data-number="4.6" class="anchored" data-anchor-id="sec-slr-predict">
<span class="header-section-number">4.6</span> Prediction</h2>
<p>One of the primary purposes of a regression model is to use for prediction. When a regression model is used for prediction, the estimated value of the response variable is computed based on a given value of the predictor. We’ve seen this in earlier sections when calculating the residuals. Let’s take a look at the model predictions for two movies released in 2023.</p>
<p>The movie <em>Barbie</em> was released in theaters on July 21, 2023. This movie was widely praised by critics, and it has a critics score of 88 at the time the data were obtained. Based on <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>, the predicted audience score is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\text{audience\_scores}} &amp;= 32.316 + 0.519 \times 88 \\
&amp;= \textbf{77.988} \\
\end{aligned}
\]</span></p>
<p>From the snapshot of the Barbie Rotten Tomatoes page (<a href="#fig-barbie" class="quarto-xref">Figure&nbsp;<span>4.5</span></a>), we see the actual audience score is 83<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>. Therefore, the model under predicted the audience score by about 5 points (83 - 77.988). Perhaps this isn’t surprising given this film’s massive box office success! <!--# do i need a citation for this statement?--></p>
<div id="fig-barbie" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-barbie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/04-barbie.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;4.5: Source: https://www.rottentomatoes.com/m/barbie (accessed August 29, 2023)"><img src="images/04-barbie.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-barbie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4.5: Source: https://www.rottentomatoes.com/m/barbie (accessed August 29, 2023)
</figcaption></figure>
</div>
<div class="yourturn">
<p>The movie <em>Asteroid City</em> was released in theaters on June 23, 2023. The critics score for this movie was 75<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</p>
<ul>
<li><p>What is the predicted audience score?</p></li>
<li><p>The actual audience score is 62. Did the model over or under predict? What is the residual? <a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p></li>
</ul>
</div>
<!--# can i remove this paragraph and just use the callout box about extraploation-->
<p>The regression model is most reliable when predicting the response for values of the predictor within the range of the sample data used to fit the regression model. Using the model to predict for values far outside this range is called <strong>extrapolation<em>.</em></strong> The sample data provide information about the relationship between the response and predictor variables for values within the range of the predictor in the data. We can not safely assume that the linear relationship quantified by our model is the same for values of the predictor far outside of this range. Therefore, extrapolation often results in unreliable predictions that could be misleading if the linear relationship does not hold outside the range of the sample data.</p>
<div class="analysis_in_practice">
<p>Only use the regression model to compute predictions for values of the predictor that are within (or very close) to the range of values in the sample data used to fit the model. Extrapolation, using a model to compute predictions for value so the predictor far outside the range in the data, can result in unreliable predictions.</p>
</div>
</section><section id="sec-model-assessment" class="level2" data-number="4.7"><h2 data-number="4.7" class="anchored" data-anchor-id="sec-model-assessment">
<span class="header-section-number">4.7</span> Model evaluation</h2>
<p>We have shown how a simple linear regression model can be used to describe the relationship between a response and predictor variable and to predict new values of the response. Now we will look at two statistics that will help us evaluate how well the model fits the data and how well it explains variability in the response.</p>
<section id="root-mean-square-error" class="level3" data-number="4.7.1"><h3 data-number="4.7.1" class="anchored" data-anchor-id="root-mean-square-error">
<span class="header-section-number">4.7.1</span> Root Mean Square Error</h3>
<p>The <strong>Root Mean Square Error (RMSE)</strong>, shown in <a href="#eq-slr-rmse" class="quarto-xref">Equation&nbsp;<span>4.15</span></a>, is a measure of the average difference between the observed and predicted values of the response variable.</p>
<p><span id="eq-slr-rmse"><span class="math display">\[
RMSE = \sqrt{\frac{\sum_{i=1}^ne_i^2}{n}} = \sqrt{\frac{\sum_{i=1}^n(y_i - \hat{y}_i)^2}{n}}
\tag{4.15}\]</span></span></p>
<p>This measure is especially useful if prediction is the primary modeling objective. The RMSE takes values from 0 to <span class="math inline">\(\infty\)</span> (infinity) and has the same units as the response variable.</p>
<div class="yourturn">
<p>Do higher or lower values of RMSE indicate a better model fit?<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
</div>
<p>There is no universal threshold of RMSE to determine whether the model is a good fit. In fact, the RMSE is often most useful when comparing the performance of multiple models. Take the following into account when using RMSE to evaluate model fit.</p>
<ol type="1">
<li>What is the range <span class="math inline">\((\text{max} - \text{min})\)</span> of the response variable in the data? How does the RMSE compare to the range? For example, <span class="math inline">\(RMSE = 10\)</span> indicates very good model performance if the response variable ranges from 10000 to 20000, but very poor model performance if the response variable ranges from 0 to 20.</li>
<li>What is a reasonable error threshold based on the subject matter and analysis objectives? We may be willing to use a model with higher RMSE for a low-stakes analysis objective (for example, the model is used to inform the choices of movie-goers) than a high-stakes objective (the model is used to inform how a movie studio’s multi-million dollar marketing budget will be allocated).</li>
</ol>
<div class="yourturn">
<p>The RMSE for the movie scores model is 12.452. The range for the audience score is -. What is your evaluation of the model fit based on RMSE? Explain your response.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
</div>
</section><section id="sec-slr-sum-sq" class="level3" data-number="4.7.2"><h3 data-number="4.7.2" class="anchored" data-anchor-id="sec-slr-sum-sq">
<span class="header-section-number">4.7.2</span> Analysis of variance and <span class="math inline">\(R^2\)</span>
</h3>
<p>The <strong>coefficient of determination</strong>, <span class="math inline">\(R^2\)</span>, the percentage of variability in the response variable that is explained by the predictor variable. In terms of the movie scores data, it is the percentage of variability in the audience score that is accounted for by changes in the critics score. Before talking more about how <span class="math inline">\(R^2\)</span> is used for model evaluation, let’s discuss how this percentage is calculated.</p>
<p>There is variability in the response variable, as we see in the exploratory data analysis in <a href="#fig-movies-univariate" class="quarto-xref">Figure&nbsp;<span>4.1</span></a> and <a href="#tbl-movies-univariate" class="quarto-xref">Table&nbsp;<span>4.1</span></a>. <strong>Analysis of Variance (ANOVA)</strong>, shown in <a href="#eq-anova" class="quarto-xref">Equation&nbsp;<span>4.16</span></a>, is the process of partitioning the various sources of variability.</p>
<p><span id="eq-anova"><span class="math display">\[
\text{Total variability} = \text{Explained variability} + \text{Unexplained variability}
\tag{4.16}\]</span></span></p>
<p>From <a href="#eq-anova" class="quarto-xref">Equation&nbsp;<span>4.16</span></a>, the variability in the response variable is from two sources:</p>
<ol type="1">
<li><p><strong>Explained variability (Model)</strong>: This is the variability in the response variable that can be explained by the model. In the case of simple linear regression, it is the variability in the response variable that can be explained by the predictor variable. In the movie scores analysis, this is the variability in <code>audience_score</code> that is explained by the <code>critics_score</code>.</p></li>
<li><p><strong>Unexplained variability (Residuals)</strong>: This is the variability in the response variable that is left unexplained after the model is fit. This can be understood by assessing the variability in the residuals. In the movie scores analysis, this is the variability due to the factors other than critics score.</p></li>
</ol>
<p>The variability in the response variable and the contribution from each source is quantified using sum of squares. In general, the <strong>sum of squares (SS)</strong> is a measure of how far the observations are from a given point, for example the mean. Using sum of squares, we can quantify the components of <a href="#eq-anova" class="quarto-xref">Equation&nbsp;<span>4.16</span></a>.</p>
<p>Let <span class="math inline">\(SST\)</span> = Sum of Squares Total, <span class="math inline">\(SSM\)</span> = Sum of Squares Model, and <span class="math inline">\(SSR\)</span> = Sum of Squares Residuals. Then,</p>
<p><span id="eq-anova-ss"><span class="math display">\[
\begin{aligned}
SST &amp;= SSM + SSR \\[10pt]
\sum_{i=1}^n (y_i - \bar{y})^2 &amp;= \sum_{i=1}^n(\hat{y}_i - \bar{y})^2 + \sum_{i=1}^n(y_i - \hat{y}_i)^2
\end{aligned}
\tag{4.17}\]</span></span></p>
<!--# add link to appendix to see mathematically-->
<p><strong>Sum of Squares Total (SST)</strong> <span class="math inline">\(= \sum_{i=1}^n(y_i - \bar{y})^2\)</span>, is the total variability, an overall measure of how far the observed values of the response variable are from the mean value of the response <span class="math inline">\(\bar{y}\)</span>. The formula for SST may look familiar, as it is <span class="math inline">\((n-1)s_y^2\)</span> , which equals<span class="math inline">\((n-1)\)</span> times the variance of <span class="math inline">\(y\)</span>. SST can be partitioned into two pieces, Sum of Squares Model (SSM) and Sum of Squares Residuals (SSR).</p>
<p><strong>Sum of Squares Model (SSM)</strong> <span class="math inline">\(= \sum_{i=1}^n(\hat{y}_i - \bar{y})^2\)</span>, is the explained variability, an overall measure of how much the predicted value of the response variable (the expected mean value of the response given the predictor) differs from the overall mean value of the response. This indicates how much the observed response’s deviation from the mean is accounted for by knowing the value of the predictor.</p>
<p>Lastly, the <strong>Sum of Squares Residual (SSR)</strong> <span class="math inline">\(= \sum_{i=1}^n(y_i - \hat{y}_i)^2\)</span>, is the unexplained variability, an overall measure of how much the observed values of the response differ from the predicted values. This is the same sum of squared residuals used to estimate the least-squares regression model in <a href="#sec-least-squares" class="quarto-xref"><span>Section 4.4.1</span></a>.</p>
<p>We use the sum of squares to calculate the <strong>coefficient of determination</strong> <span class="math inline">\(R^2\)</span></p>
<p><span id="eq-rsq"><span class="math display">\[
R^2 = \frac{SSM}{SST} = 1 - \frac{SSR}{SST}
\tag{4.18}\]</span></span></p>
<!--# add images breaking down variability-->
<p><a href="10-model-eval.html#eq-rsq" class="quarto-xref">Equation&nbsp;<span>10.1</span></a>, shows that <span class="math inline">\(R^2\)</span> is a the proportion of variability in the response (SST) that is explained by the model (SSM). Note that <span class="math inline">\(R^2\)</span> is calculated as proportion between 0 and 1, but is reported as a percentage between 0% and 100%.</p>
<p>The <span class="math inline">\(R^2\)</span> for the model in <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a> is 0.611. It is interpreted as the following:</p>
<blockquote class="blockquote">
<p><em>About 61.1% of the variability in the audience score for movies on Rotten Tomatoes can be explained by the model (critics score).</em></p>
</blockquote>
<div class="yourturn">
<p>Do higher or lower values of <span class="math inline">\(R^2\)</span> indicate a better model fit?<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
</div>
<p>Similar to RMSE, there is no universal threshold for what makes a “good” <span class="math inline">\(R^2\)</span> value. When using <span class="math inline">\(R^2\)</span> to determine if the model is a good fit, take into account what might be a reasonable to expect given the subject matter.</p>
</section></section><section id="sec-slr-R" class="level2" data-number="4.8"><h2 data-number="4.8" class="anchored" data-anchor-id="sec-slr-R">
<span class="header-section-number">4.8</span> Simple linear regression in R</h2>
<section id="sec-slr-fit-R" class="level3" data-number="4.8.1"><h3 data-number="4.8.1" class="anchored" data-anchor-id="sec-slr-fit-R">
<span class="header-section-number">4.8.1</span> Fitting the least-squares model</h3>
<p>We fit linear regression models using the <code>lm</code> function, which is part of the <strong>stats</strong> package <span class="citation" data-cites="stats">(<a href="references.html#ref-stats" role="doc-biblioref">2024</a>)</span> built into R. We then use the <code>tidy</code> function from the <strong>broom</strong> package <span class="citation" data-cites="broom-2">(<a href="references.html#ref-broom-2" role="doc-biblioref">Robinson, Hayes, and Couch 2023</a>)</span> to display the results in a <em>tidy</em> data format (<a href="02-review-r.html#sec-tidy-data" class="quarto-xref"><span>Section 2.3.1</span></a>). The code to find the linear regression model using the <code>movie_scores</code> data with <code>audience_score</code> as the response and <code>critics_score</code> as the predictor (<a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>) is below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">audience_score</span> <span class="op">~</span> <span class="va">critics_score</span>, data <span class="op">=</span> <span class="va">movie_scores</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = audience_score ~ critics_score, data = movie_scores)

Coefficients:
  (Intercept)  critics_score  
       32.316          0.519  </code></pre>
</div>
</div>
<p>Next, we want to display the model results in a tidy format. We build upon the code above by saving the model in an object called <code>movie_fit</code> and displaying the object. We will also use <code>movie_fit</code> to calculate predictions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">movie_fit</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">audience_score</span> <span class="op">~</span> <span class="va">critics_score</span>, data <span class="op">=</span> <span class="va">movie_scores</span><span class="op">)</span> </span>
<span></span>
<span><span class="fu">tidy</span><span class="op">(</span><span class="va">movie_fit</span><span class="op">)</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term          estimate std.error statistic  p.value
  &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     32.3      2.34        13.8 4.03e-28
2 critics_score    0.519    0.0345      15.0 2.70e-31</code></pre>
</div>
</div>
<p>Notice the resulting the model is the same as <a href="#eq-movies-slr" class="quarto-xref">Equation&nbsp;<span>4.8</span></a>, which we calculated based on <a href="#eq-least-sq-estimates" class="quarto-xref">Equation&nbsp;<span>4.13</span></a>. We will discuss the other columns in the output in <a href="05-slr-inference.html" class="quarto-xref"><span>Chapter 5</span></a>.</p>
<p>We can also use <code>kable()</code> from the <strong>knitr</strong> package <span class="citation" data-cites="knitr">(<a href="references.html#ref-knitr" role="doc-biblioref">Xie 2024</a>)</span> to display the tidy results in an neatly formatted table and control the number of digits in the output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tidy</span><span class="op">(</span><span class="va">movie_fit</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu">kable</span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">32.316</td>
<td style="text-align: right;">2.343</td>
<td style="text-align: right;">13.8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">critics_score</td>
<td style="text-align: right;">0.519</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">15.0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section><section id="prediction" class="level3" data-number="4.8.2"><h3 data-number="4.8.2" class="anchored" data-anchor-id="prediction">
<span class="header-section-number">4.8.2</span> Prediction</h3>
<p>Below is the code to predict the audience score for <em>Barbie</em> as shown earlier in the section. We create a tibble that contains the critics score for <em>Barbie</em>, then use <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code> and the model object to compute the prediction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">barbie_movie</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>critics_score <span class="op">=</span> <span class="fl">88</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">movie_fit</span>, <span class="va">barbie_movie</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> 1 
78 </code></pre>
</div>
</div>
<p>We can also produce predictions for multiple movies by putting multiple values of the predictor in the tibble. In the code below we produce predictions for <em>Barbie</em> and <em>Asteroid City</em>. We begin by storing the critics scores for both movies in a tibble. Then we use <code><a href="https://rdrr.io/r/stats/predict.html">predict()</a></code>, as before.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">new_movies</span> <span class="op">&lt;-</span> <span class="fu">tibble</span><span class="op">(</span>critics_score <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">88</span>, <span class="fl">75</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">movie_fit</span>, <span class="va">new_movies</span><span class="op">)</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   1    2 
78.0 71.2 </code></pre>
</div>
</div>
</section><section id="r2-and-rmse" class="level3" data-number="4.8.3"><h3 data-number="4.8.3" class="anchored" data-anchor-id="r2-and-rmse">
<span class="header-section-number">4.8.3</span> <span class="math inline">\(R^2\)</span> and RMSE</h3>
<p>The <code>glance()</code> function in the <strong>broom</strong> package produces model summary statistics, including <span class="math inline">\(R^2\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glance</span><span class="op">(</span><span class="va">movie_fit</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 12
  r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
      &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     0.611         0.608  12.5      226. 2.70e-31     1  -575. 1157. 1166.
# ℹ 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
</div>
</div>
<p>The code below will only return <span class="math inline">\(R^2\)</span> from the output of <code>glance()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">glance</span><span class="op">(</span><span class="va">movie_fit</span><span class="op">)</span><span class="op">$</span><span class="va">r.squared</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.611</code></pre>
</div>
</div>
<p>RMSE is computed using the <code>rmse()</code> function from the <strong>yardstick</strong> package <span class="citation" data-cites="yardstick">(<a href="references.html#ref-yardstick" role="doc-biblioref">Kuhn, Vaughan, and Hvitfeldt 2025</a>)</span>. First, we use <code>augment()</code> from the <strong>broom</strong> package to compute the predicted value for each observation in the data set. These values are stored if the column <code>.fitted</code>. We may notice that many other columns are produced by <code>augment()</code> as well; these are discussed in <a href="06-slr-conditions.html" class="quarto-xref"><span>Chapter 6</span></a>. We input the augmented data into <code>rmse()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">movies_augment</span> <span class="op">&lt;-</span> <span class="fu">augment</span><span class="op">(</span><span class="va">movie_fit</span><span class="op">)</span> </span>
<span></span>
<span><span class="fu">rmse</span><span class="op">(</span><span class="va">movies_augment</span>, truth <span class="op">=</span> <span class="va">audience_score</span>, estimate <span class="op">=</span> <span class="va">.fitted</span><span class="op">)</span> </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard        12.5</code></pre>
</div>
</div>
</section></section><section id="summary" class="level2" data-number="4.9"><h2 data-number="4.9" class="anchored" data-anchor-id="summary">
<span class="header-section-number">4.9</span> Summary</h2>
<p>In this chapter, we introduced simple linear regression. We showed how to use exploratory data analysis to evaluate whether linear regression is appropriate to model the relationship between two variables. Next, we computed the slope and intercept (the model coefficients) and interpreted these values in in the context of the data. We used the model to compute predictions and evaluated the model performance using <span class="math inline">\(R^2\)</span> and RMSE. We finished the chapter by conducting simple linear regression in R.</p>
<p>This chapter has helped set the foundation for all the regression methods presented throughout the remainder of the text. In <a href="05-slr-inference.html" class="quarto-xref"><span>Chapter 5</span></a>, we’ll use the simple linear regression model to draw conclusions about the relationship between the response and predictor variables.</p>
<!--Partitioning variability and $R^2$-->
<!--Reference notes: https://sta210-fa21.netlify.app/slides/08-partition-var.html#1-->
<!--Introduce $R^2$ here, but does it make sense to move this the inference chapter?-->
<!--Could also introduce root mean square error here.-->
<!-- chapter summary-->
<!--Computing lab assignments-->
<!--Homework assignments-->
<!--north carolina assignment?-->


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-hickey2015suspicious" class="csl-entry" role="listitem">
Hickey, Walt. 2015. <span>“Be Suspicious of Online Movie Ratings, Especially Fandango’s.”</span> <em>FiveThirtyEight, Available at: Http://Fivethirtyeight. Com/Features/Fandango-Movies-Ratings</em>.
</div>
<div id="ref-fivethirtyeight" class="csl-entry" role="listitem">
Kim, Albert Y., Chester Ismay, and Jennifer Chunn. 2018a. <span>“The Fivethirtyeight r Package: ’Tame Data’ Principles for Introductory Statistics and Data Science Courses”</span> 11. <a href="https://escholarship.org/uc/item/0rx1231m">https://escholarship.org/uc/item/0rx1231m</a>.
</div>
<div id="ref-kim2018fivethirtyeight" class="csl-entry" role="listitem">
Kim, Albert Y, Chester Ismay, and Jennifer Chunn. 2018b. <span>“The Fivethirtyeight r Package:‘tame Data’principles for Introductory Statistics and Data Science Courses.”</span> <em>Technology Innovations in Statistics Education</em> 11 (1).
</div>
<div id="ref-yardstick" class="csl-entry" role="listitem">
Kuhn, Max, Davis Vaughan, and Emil Hvitfeldt. 2025. <span>“Yardstick: Tidy Characterizations of Model Performance.”</span> <a href="https://doi.org/10.32614/CRAN.package.yardstick">https://doi.org/10.32614/CRAN.package.yardstick</a>.
</div>
<div id="ref-stats" class="csl-entry" role="listitem">
R Core Team. 2024. <span>“R: A Language and Environment for Statistical Computing.”</span> <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-broom-2" class="csl-entry" role="listitem">
Robinson, David, Alex Hayes, and Simon Couch. 2023. <span>“Broom: Convert Statistical Objects into Tidy Tibbles.”</span> <a href="https://CRAN.R-project.org/package=broom">https://CRAN.R-project.org/package=broom</a>.
</div>
<div id="ref-knitr" class="csl-entry" role="listitem">
Xie, Yihui. 2024. <span>“Knitr: A General-Purpose Package for Dynamic Report Generation in r.”</span> <a href="https://yihui.org/knitr/">https://yihui.org/knitr/</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The response variable is <code>audience</code>, the audience score. The predictor variable is <code>critics</code>, the critics score.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The distribution of <code>audience_score</code> is unimodal and left-skewed. The median score is 66.5 and the IQR is 31 (81 - 50). We note that the center is higher and there is less variability in the middle 50% of the distribution compared to <code>critics_score</code> .<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><strong>Example prediction question:</strong> What do we expect the audience score to be for movies with a critics score of 75?<br><strong>Example inference question</strong> Is the critics score a useful predictor of the audience score?<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The population is all movies on the Rotten Tomatoes website. The sample is the set of 146 movies in the data set.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><strong>Example answer:</strong> I would rather see a movie with a positive residual, because that means the audience actually rated the movie more favorably than what was expected based on the model.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The interpretation of the intercept is meaningful, because it is plausible for a movie to have a critics score of 0 and there are observations with scores around 5, which is near 0 on the 0 - 100 point scale.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Source: https://www.rottentomatoes.com/m/barbie Accessed on August 29, 2023.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Source: https://www.rottentomatoes.com/m/asteroid_city Accessed on August 29, 2023.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>The predicted audience score is 32.316 + 0.519 * 75 = <strong>71.241</strong>. The model over predicted. The residual is 62 - 71.241 = <strong>-9.241.</strong><a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Lower values indicate a better fit, with 0 indicating the predictor variable perfectly predicts the response.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><strong>Example answer:</strong> An error of 12.452 is about a 17% error based on the range of the audience scores. Because the audience scores range 0 to 100, this error seems relatively large.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Higher values of <span class="math inline">\(R^2\)</span> indicate a better model fit, as it means more of the variability in the response is being explained by the model.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/introregressio\.netlify\.app");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./03-eda.html" class="pagination-link" aria-label="Exploratory data analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-slr-inference.html" class="pagination-link" aria-label="Inference for simple linear regression">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inference for simple linear regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/matackett/regression-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>