<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Maria Tackett">
<title>6&nbsp; Model conditions and diagnostics – Introduction to Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-mlr.html" rel="next">
<link href="./05-slr-inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-31c3c5ec0f84e3846e28bd1517aa8340.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script defer="" data-domain="https://matackett.github.io/regression-book/" src="https://plausible.io/js/script.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-slr.html">Part 2: Simple linear regression</a></li><li class="breadcrumb-item"><a href="./06-slr-conditions.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model conditions and diagnostics</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Regression Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/matackett/regression-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 1: Getting started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression in the data science workflow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-review-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data analysis in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 2: Simple linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-slr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inference for simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-slr-conditions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model conditions and diagnostics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 3: Multiple linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-mlr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for multiple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-mlr-transformations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variable transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-model-eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model selection</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 4: Beyond linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-logistic-prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Logistic regression: Prediction and evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-special-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Special topics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathematics of linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Mathematics of logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Data sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li><a href="#sec-coffee-intro" id="toc-sec-coffee-intro" class="nav-link" data-scroll-target="#sec-coffee-intro"><span class="header-section-number">6.1</span> Introduction: Coffee grades</a></li>
  <li>
<a href="#sec-model-conditions" id="toc-sec-model-conditions" class="nav-link" data-scroll-target="#sec-model-conditions"><span class="header-section-number">6.2</span> Model conditions</a>
  <ul class="collapse">
<li><a href="#assumptions-and-the-line-conditions" id="toc-assumptions-and-the-line-conditions" class="nav-link" data-scroll-target="#assumptions-and-the-line-conditions"><span class="header-section-number">6.2.1</span> Assumptions and the LINE conditions</a></li>
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity"><span class="header-section-number">6.2.2</span> Linearity</a></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence"><span class="header-section-number">6.2.3</span> Independence</a></li>
  <li><a href="#normality" id="toc-normality" class="nav-link" data-scroll-target="#normality"><span class="header-section-number">6.2.4</span> Normality</a></li>
  <li><a href="#equal-variance" id="toc-equal-variance" class="nav-link" data-scroll-target="#equal-variance"><span class="header-section-number">6.2.5</span> Equal variance</a></li>
  </ul>
</li>
  <li>
<a href="#sec-conditions-not-satisfied" id="toc-sec-conditions-not-satisfied" class="nav-link" data-scroll-target="#sec-conditions-not-satisfied"><span class="header-section-number">6.3</span> Strategies when conditions aren’t satisfied</a>
  <ul class="collapse">
<li><a href="#linearity-1" id="toc-linearity-1" class="nav-link" data-scroll-target="#linearity-1"><span class="header-section-number">6.3.1</span> Linearity</a></li>
  <li><a href="#independence-1" id="toc-independence-1" class="nav-link" data-scroll-target="#independence-1"><span class="header-section-number">6.3.2</span> Independence</a></li>
  <li><a href="#normality-1" id="toc-normality-1" class="nav-link" data-scroll-target="#normality-1"><span class="header-section-number">6.3.3</span> Normality</a></li>
  <li><a href="#equal-variance-1" id="toc-equal-variance-1" class="nav-link" data-scroll-target="#equal-variance-1"><span class="header-section-number">6.3.4</span> Equal variance</a></li>
  <li><a href="#recap" id="toc-recap" class="nav-link" data-scroll-target="#recap"><span class="header-section-number">6.3.5</span> Recap</a></li>
  </ul>
</li>
  <li>
<a href="#sec-model-diagnostics" id="toc-sec-model-diagnostics" class="nav-link" data-scroll-target="#sec-model-diagnostics"><span class="header-section-number">6.4</span> Model diagnostics</a>
  <ul class="collapse">
<li><a href="#influential-points" id="toc-influential-points" class="nav-link" data-scroll-target="#influential-points"><span class="header-section-number">6.4.1</span> Influential points</a></li>
  <li><a href="#sec-slr-leverage" id="toc-sec-slr-leverage" class="nav-link" data-scroll-target="#sec-slr-leverage"><span class="header-section-number">6.4.2</span> Leverage</a></li>
  <li><a href="#sec-slr-std-resid" id="toc-sec-slr-std-resid" class="nav-link" data-scroll-target="#sec-slr-std-resid"><span class="header-section-number">6.4.3</span> Standardized residuals</a></li>
  <li><a href="#sec-cooks-distance" id="toc-sec-cooks-distance" class="nav-link" data-scroll-target="#sec-cooks-distance"><span class="header-section-number">6.4.4</span> Cook’s distance</a></li>
  <li><a href="#sec-outliers-impact" id="toc-sec-outliers-impact" class="nav-link" data-scroll-target="#sec-outliers-impact"><span class="header-section-number">6.4.5</span> Handling influential points</a></li>
  </ul>
</li>
  <li><a href="#sec-model-in-practice" id="toc-sec-model-in-practice" class="nav-link" data-scroll-target="#sec-model-in-practice"><span class="header-section-number">6.5</span> Modeling in practice</a></li>
  <li><a href="#sec-conditions-in-r" id="toc-sec-conditions-in-r" class="nav-link" data-scroll-target="#sec-conditions-in-r"><span class="header-section-number">6.6</span> Model conditions and diagnostics in R</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">6.7</span> Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/matackett/regression-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-slr.html">Part 2: Simple linear regression</a></li><li class="breadcrumb-item"><a href="./06-slr-conditions.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model conditions and diagnostics</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-ch-slr-conditions" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model conditions and diagnostics</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="learning-goals" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="learning-goals">Learning goals</h2>
<ul>
<li>Describe how model conditions are used to check the assumptions for linear regression</li>
<li>Use the data to check model conditions and diagnostics</li>
<li>Identify strategies to handle violations in the conditions</li>
<li>Identifying influential observations using Cook’s distance</li>
<li>Use leverage and standardized residuals to understand potential outliers</li>
<li>Identify strategies for dealing with outliers and influential points</li>
<li>Check model conditions and diagnostics using R</li>
</ul>
<!--#
## Software and packages {.unnumbered}

-   `library(tidyverse)` [@tidyverse]

-   `library(broom)` [@broom-2]

-   `library(knitr)` [@knitr]
--></section><section id="sec-coffee-intro" class="level2" data-number="6.1"><h2 data-number="6.1" class="anchored" data-anchor-id="sec-coffee-intro">
<span class="header-section-number">6.1</span> Introduction: Coffee grades</h2>
<p>What makes a delicious cup of coffee? Is there a relationship between a coffee’s aroma and its flavor? We will consider these questions by analyzing data from the Coffee Quality Database (<a href="https://database.coffeeinstitute.org/" class="uri">https://database.coffeeinstitute.org/</a>). The data set used in this analysis was curated by James LeDoux and was featured as part of the TidyTuesday weekly data visualization challenge in July 2020 <span class="citation" data-cites="tidytuesday">(<a href="references.html#ref-tidytuesday" role="doc-biblioref">Community 2024</a>)</span>. It contains a variety of features and quality ratings for over 1,000 coffees scraped from the Coffee Quality Database in 2018.<!--# add something about how the grades are determined-->The data are in <code>coffee-grades.csv</code>. We will use the following variables in this chapter:</p>
<ul>
<li><p><code>aroma</code> : Aroma grade (0: worst aroma - 10: best aroma)</p></li>
<li><p><code>flavor</code>: Flavor grade (0: worst flavor - 10: best flavor)</p></li>
</ul>
<div class="objective">
<p>The goal of the analysis is to use the aroma grade to understand variability in the flavor grade, and assess model conditions and diagnostics to evaluate whether regression analysis is suitable for drawing reliable conclusions from the data.</p>
</div>
<div class="cell" data-layout="[[1,1],[1]]">
<div id="fig-coffee-eda" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-coffee-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-coffee-eda-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-coffee-eda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-eda-1.png" class="lightbox" data-gallery="fig-coffee-eda" title="Figure&nbsp;6.1&nbsp;(a): Distribution of flavor"><img src="06-slr-conditions_files/figure-html/fig-coffee-eda-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-coffee-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-coffee-eda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Distribution of <code>flavor</code>
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-coffee-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-coffee-eda-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-coffee-eda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-eda-2.png" class="lightbox" data-gallery="fig-coffee-eda" title="Figure&nbsp;6.1&nbsp;(b): Distribution of aroma"><img src="06-slr-conditions_files/figure-html/fig-coffee-eda-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-coffee-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-coffee-eda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Distribution of <code>aroma</code>
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-coffee-eda" style="flex-basis: 100.0%;justify-content: flex-start;">
<div id="fig-coffee-eda-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-coffee-eda-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-eda-3.png" class="lightbox" data-gallery="fig-coffee-eda" title="Figure&nbsp;6.1&nbsp;(c): flavor versus aroma"><img src="06-slr-conditions_files/figure-html/fig-coffee-eda-3.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-coffee-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-coffee-eda-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) <code>flavor</code> versus <code>aroma</code>
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Univariate and bivariate exploratory data analysis for coffee data
</figcaption></figure>
</div>
</div>
<div class="cell">
<div id="tbl-coffee-eda" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coffee-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Summary statistics for <code>aroma</code> and <code>flavor</code>
</figcaption><div aria-describedby="tbl-coffee-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Median (Q2)</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">aroma</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">5.1</td>
<td style="text-align: right;">7.4</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">7.8</td>
<td style="text-align: right;">8.8</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">flavor</td>
<td style="text-align: right;">7.5</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">6.1</td>
<td style="text-align: right;">7.3</td>
<td style="text-align: right;">7.6</td>
<td style="text-align: right;">7.8</td>
<td style="text-align: right;">8.8</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>From the exploratory data analysis in <a href="#fig-coffee-eda" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>, we see preliminary indication of a relationship between the aroma and flavor grades. There is an outlier in <a href="#fig-coffee-eda-3" class="quarto-xref">Figure&nbsp;<span>6.1 (c)</span></a> that has a very low aroma grade but a flavor grade close to the average.</p>
<div class="cell">
<div id="tbl-coffee-model" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coffee-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Linear regression model of the <code>aroma</code> versus <code>flavor</code> with 95% confidence intervals
</figcaption><div aria-describedby="tbl-coffee-model-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">0.151</td>
<td style="text-align: right;">9.75</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.173</td>
<td style="text-align: right;">1.764</td>
</tr>
<tr class="even">
<td style="text-align: left;">aroma</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">40.25</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.761</td>
<td style="text-align: right;">0.839</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We use the model in <a href="#tbl-coffee-model" class="quarto-xref">Table&nbsp;<span>6.2</span></a> to describe the relationship between the aroma and flavor of coffee. For each additional point in the aroma grade, the flavor grade is expected to increase by 0.8 points, on average.</p>
<div class="yourturn">
<ul>
<li>Use <a href="#tbl-coffee-model" class="quarto-xref">Table&nbsp;<span>6.2</span></a> to conduct a hypothesis test to determine if the data provide evidence of a linear relationship between <code>aroma</code> and <code>flavor</code>.</li>
<li>Is the confidence interval consistent with the conclusion from the test?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>
</li>
</ul>
</div>
<p>From the interval in <a href="#tbl-coffee-model" class="quarto-xref">Table&nbsp;<span>6.2</span></a>, we are 95% confident that for each additional point in the aroma grade, the flavor grade increases by 0.761 to 0.839 points, on average. In summary, coffees that smell better are expected to taste better!</p>
<p>The inferential methods introduced in <a href="05-slr-inference.html" class="quarto-xref"><span>Chapter 5</span></a> used to make conclusions about the relationship between the response and predictor variables rely on a set of underlying assumptions about the data. Though we are unable to check if these underlying conditions hold for the entire population, we will see in <a href="#sec-model-conditions" class="quarto-xref"><span>Section 6.2</span></a> how we are able to check a set of model conditions to evaluate whether these assumptions reasonably hold in the sample data.</p>
<p>As seen in <a href="#fig-coffee-eda-3" class="quarto-xref">Figure&nbsp;<span>6.1 (c)</span></a>, there is an outlying observation that is outside the general trend of the data, given its aroma grade is much lower than the others but its flavor grade is around the average. This is a valid data point and not the result of data entry error; therefore, we’d like to evaluate whether this outlier has a noticeable impact on the estimated regression model and inferential conclusions. In <a href="#sec-model-diagnostics" class="quarto-xref"><span>Section 6.4</span></a>, we will introduce a set of model diagnostics to assess the potential impact of this observation on the results, and the impact of outliers more generally.</p>
</section><section id="sec-model-conditions" class="level2" data-number="6.2"><h2 data-number="6.2" class="anchored" data-anchor-id="sec-model-conditions">
<span class="header-section-number">6.2</span> Model conditions</h2>
<section id="assumptions-and-the-line-conditions" class="level3" data-number="6.2.1"><h3 data-number="6.2.1" class="anchored" data-anchor-id="assumptions-and-the-line-conditions">
<span class="header-section-number">6.2.1</span> Assumptions and the LINE conditions</h3>
<p><a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a> introduced the assumptions underlying the population when doing simple linear regression. These assumptions are important, as the reliability of the interpretations and inferential conclusions from the regression analysis rely on being consistent with the assumed framework. There are various analysis tasks we can do with a simple linear regression model: describe the relationship between a response and predictor variable, predict the response given values of the predictor, and draw conclusions about a population slope using inference. As we’ll see in this chapter, we need some or all of these assumptions to hold depending on the analysis task.</p>
<p>Recall the assumptions from <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a>:</p>
<ol type="1">
<li><p>The distribution of the response <span class="math inline">\(Y\)</span> is normal for a given value of the predictor <span class="math inline">\(X\)</span>.</p></li>
<li><p>The expected value (mean) of <span class="math inline">\(Y|X\)</span> is <span class="math inline">\(\beta_0 + \beta_1 X\)</span>. There is a linear relationship between the response and predictor variable.</p></li>
<li><p>The variance <span class="math inline">\(Y|X\)</span> is <span class="math inline">\(\sigma^2_{\epsilon}\)</span>. This variance is equal for all values of <span class="math inline">\(X\)</span> and thus does not depend on <span class="math inline">\(X\)</span>.</p></li>
<li><p>The error terms for each observation, <span class="math inline">\(\epsilon\)</span> in <a href="05-slr-inference.html#eq-slr-model-ch5" class="quarto-xref">Equation&nbsp;<span>5.3</span></a>, are independent. This also means the values of the response variable, and observations more generally, are independent.</p></li>
</ol>
<p>The assumptions are based on population-level data, yet we work with sample data in practice. Therefore, we have a set of model conditions we can check using the data at hand to assess these assumptions.</p>
<p>After fitting a simple linear regression model, we check four conditions to evaluate whether the data are consistent with the underlying assumptions. They are commonly referred to using the mnemonic LINE.<!--# is there a citation for the original use?--> These four conditions are the following:</p>
<ul>
<li>
<strong>L</strong>inearity: There is a linear relationship between the response and predictor variables.</li>
<li>
<strong>I</strong>ndependence: The residuals are independent of one another. <!--# Is there a more useful way to describe independence? One residual does not inform another residual? -->
</li>
<li>
<strong>N</strong>ormality: The distribution of the residuals is approximately normal.</li>
<li>
<strong>E</strong>qual variance: The spread of the residuals is approximately equal for all predicted values.</li>
</ul>
<p>After fitting the regression model, we calculate the residuals for each observation, <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span>, and use the residuals to check the conditions. We introduce the four model conditions in order based on the LINE acronym; however, the conditions may be checked in any order.</p>
</section><section id="linearity" class="level3" data-number="6.2.2"><h3 data-number="6.2.2" class="anchored" data-anchor-id="linearity">
<span class="header-section-number">6.2.2</span> Linearity</h3>
<p>The <strong>linearity</strong> condition states that there is a linear relationship between the response and predictor variable. Though we don’t expect the relationship between the two variables to be perfectly linear, it should be linear enough that it would be reasonable to summarize the relationship between the two variables using the linear regression model.</p>
<p>Recall from <a href="#sec-coffee-intro" class="quarto-xref"><span>Section 6.1</span></a> that we used a scatterplot and the correlation coefficient to describe the shape and other features of the relationship between the <code>aroma</code> (predictor) and <code>flavor</code> (response). This exploratory data analysis provides an initial assessment of whether the linear regression model seems like a reasonable fit for the data. For example, if we saw a clear curve in the scatterplot or calculated a correlation coefficient close to 0, we might conclude that the proposed linear regression model would not sufficiently capture the relationship between the two variables and thus rethink the modeling strategy. While the exploratory data analysis can help provide initial assessment and help us thoughtfully consider our modeling approach, it should <u><strong>not</strong></u> be solely relied upon as the final evaluation of whether the proposed model sufficiently captures the relationship between the two variables. We analyze the residuals for that assessment.</p>
<!--# Why not rely on EDA to conclude linearity?-->
<p>To check linearity, we make a scatterplot of the residuals versus the predicted values as shown in <a href="#fig-coffee-linearity" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>. We have included a horizontal line at <span class="math inline">\(\text{residuals} = 0\)</span> to more easily see when the model over or under predicts.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-linearity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-linearity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-linearity-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;6.2: Residuals versus predicted values from the model of flavor and aroma"><img src="06-slr-conditions_files/figure-html/fig-coffee-linearity-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-linearity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: Residuals versus predicted values from the model of <code>flavor</code> and <code>aroma</code>
</figcaption></figure>
</div>
</div>
</div>
<p>This scatterplot looks very different than any of the scatterplots we’ve seen thus far in the exploratory data analysis sections in the text. Let’s break down what this plot is showing, then use it to make an assessment about the linearity condition.</p>
<p>When we fit a linear regression model, we are using the predictor to explain some of the variability in the response variable. Thus the residuals represent the remaining variability in the response variable that is not explained by the regression model (see <a href="04-slr.html#sec-slr-sum-sq" class="quarto-xref"><span>Section 4.7.2</span></a> for more detail). If the relationship between the response and predictor is linear, then we would expect the linear regression model has sufficiently captured the systematic variability that can be explained by the predictor, leaving the residuals to capture any random variability we generally expect when analyzing sample data. <strong>Keeping this in mind, we conclude that the linearity condition is satisfied if the residuals are randomly scattered around 0.</strong> We can check this by asking the following:</p>
<blockquote class="blockquote">
<p><em>Based on the plot, can you generally guess with some certainty whether the residual would be positive or negative for a given predicted value or range of predicted values?</em></p>
<ul>
<li><p>If the answer is no, then the linearity condition is satisfied.</p></li>
<li><p>If the answer is yes, then the current linear model does not adequately capture the relationship between the response and predictor variables. A model that incorporates information from more predictors or a different modeling approach is needed (we’ll discuss some of these in <a href="07-mlr.html" class="quarto-xref"><span>Chapter 7</span></a> and @@sec-ch-transformations).</p></li>
</ul>
</blockquote>
<p><a href="#fig-linearity-not-met" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> shows an example of a residual plot for simulated data in which the linearity condition is not met. There is a parabolic pattern in the plot, so the residuals are not randomly scattered around 0.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-linearity-not-met" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-linearity-not-met-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-linearity-not-met-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;6.3: Example of violation in linearity condition. The residuals are not randomly scattered around 0. Based on the plot, we can generally guess with some certainty whether the residual will be positive or negative for a given predicted value or range of predicted values."><img src="06-slr-conditions_files/figure-html/fig-linearity-not-met-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-linearity-not-met-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Example of violation in linearity condition. The residuals are not randomly scattered around 0. Based on the plot, we can generally guess with some certainty whether the residual will be positive or negative for a given predicted value or range of predicted values.
</figcaption></figure>
</div>
</div>
</div>
<!--# is this framing too confusing bc "no" means satisfied?-->
<p>Now let’s use the plot of residuals versus predicted values in <a href="#fig-coffee-linearity" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> to assess the linearity condition for the model in <a href="#tbl-coffee-model" class="quarto-xref">Table&nbsp;<span>6.2</span></a>. <strong>Based on this plot, we conclude</strong> <strong>the linearity condition is satisfied.</strong> We cannot determine with great certainty whether the residual will be positive or negative for any predicted value or range of predicted values, as the points are randomly scattered around the horizontal line at <span class="math inline">\(y = 0\)</span>. Thus the linear model adequately captures the relationship between aroma and flavor grades, and the residuals capture the random variability in flavor grade due to sources other than the aroma.</p>
<div class="analysis_in_practice">
<p>We made the assessment about linearity considering the range of fitted values that represents the bulk of the data. Because there is only one outlying observation with a fitted value less than 6, we are unable to determine what the random variability of the residuals would look like for fitted values in this range. Thus the presence of a few extreme outliers. Outliers are discussed in more detail in <a href="#sec-model-diagnostics" class="quarto-xref"><span>Section 6.4</span></a>.</p>
</div>
</section><section id="independence" class="level3" data-number="6.2.3"><h3 data-number="6.2.3" class="anchored" data-anchor-id="independence">
<span class="header-section-number">6.2.3</span> Independence</h3>
<p>The next condition in LINE is <strong>independence</strong>, that the residuals are independent of each other and that the sign of one residual does not inform the sign of other residuals. <!--# less confusing way to explain this?-->This condition is primarily checked based on the given information about the subject matter and the data collection process. This condition can be more challenging to evaluate, especially if we do not have much information about the data. If the condition is violated, there are two general scenarios in which the violation occurred. If neither of these apply to the data, then it is usually reasonable to conclude that the independence condition is satisfied.</p>
<p>The first scenario in which independence is often violated is due to a <strong>serial effect.</strong> <!--# does this term need to be cited?--> This occurs when data have a chronological order or are collected over time, and there is some pattern in the residuals when examining them in chronological order. If the data have a natural chronological order or were collected over time, make a scatterplot of residuals versus time order. Similar to checking the linearity condition, seeing no discernible pattern in the plot indicates the independence condition is satisfied. In this case, it means that knowing something about the order in which an observation was collected does not give information about whether the model tends to over or under predict. Otherwise, the independence condition is violated.</p>
<!--# do i need a graph illustrating this?-->
<p>The second common violation of independence is due to a <strong>cluster effect</strong>. <!--# does this term need to be cited?--> This is when there are subgroups present in the data that are not accounted for by the model. To check this condition, modify the plot of the residuals versus predicted by using color, shape, faceting, or visual features to differentiate the observations by the subgroup. Similar to checking the linearity condition, we expect the residuals to be randomly scattered above and below <span class="math inline">\(y = 0\)</span> for each subgroup. If this is not the case, there is indication that subgroup should be accounted for in the model. We will talk more about strategies for dealing with violations in the model conditions in <a href="#sec-conditions-not-satisfied" class="quarto-xref"><span>Section 6.3</span></a> and how to include categorical predictors in the model to account for subgroups in <a href="07-mlr.html" class="quarto-xref"><span>Chapter 7</span></a>.</p>
<p>Based on the description of the coffee data, we conclude that the independence condition is satisfied. We do not have evidence of a serial or cluster effect in the data description.</p>
<!--# add callout about spatial correlation. It's a type of sbugroup but a map is even more useful bc you can check correlation between neighboring areas-->
</section><section id="normality" class="level3" data-number="6.2.4"><h3 data-number="6.2.4" class="anchored" data-anchor-id="normality">
<span class="header-section-number">6.2.4</span> Normality</h3>
<p>The next condition is <strong>normality</strong>, that the residuals are normally distributed. Though not explicitly part of the condition, we also know that the mean of the residuals, and thus the center of the distribution, is approximately 0. This condition arises from the assumption from <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a> that the distribution of the response variable, and thus the residuals, at each value of the predictor variable is normal. In practice, it would be nearly impossible to check the distribution of the response or residuals for each possible value of the predictor, so we will look at the overall distribution of the residuals to check the normality condition.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-normality" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-normality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-normality-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6.4: The distribution of the residuals for model of flavor and aroma with normal density curve"><img src="06-slr-conditions_files/figure-html/fig-coffee-normality-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-normality-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: The distribution of the residuals for model of <code>flavor</code> and <code>aroma</code> with normal density curve
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-coffee-normality" class="quarto-xref">Figure&nbsp;<span>6.4</span></a> shows the distribution of the residuals along with the theoretical curve for a normal distribution that is centered at 0 the mean of the residuals, and a standard deviation of 0.229, the standard deviation of the residuals. Similar to the other conditions, we are looking for obvious departures from normality when assessing this condition. This might include strong skewness, multiple modes, large outliers, or other major departures from normality.</p>
<p>From <a href="#fig-coffee-normality" class="quarto-xref">Figure&nbsp;<span>6.4</span></a>, we see the distribution of the residuals is approximately normal, as the shape of the histogram is unimodal and symmetric, the general shape of the normal curve. Therefore, we conclude that <strong>the normality condition is satisfied</strong>.</p>
<!--# Should I introduce a goodness-of-fit test here, or is this fine?-->
<!--# Maybe move the point about sample size that comes later here-->
</section><section id="equal-variance" class="level3" data-number="6.2.5"><h3 data-number="6.2.5" class="anchored" data-anchor-id="equal-variance">
<span class="header-section-number">6.2.5</span> Equal variance</h3>
<p>The last condition is <strong>equal variance</strong> (also called <em>constant variance</em>), that the variability of the residuals is approximately equal for each predicted value. This condition stems from the assumption in <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a> that <span class="math inline">\(\sigma_{\epsilon}^2\)</span> is equal for all values of the predictor, and thus for all predicted values.</p>
<p>To check this condition, we will go back to the plot of the residuals versus predicted values from <a href="#fig-coffee-linearity" class="quarto-xref">Figure&nbsp;<span>6.2</span></a>. We look to see if the vertical spread of the residuals is approximately equal as we move along the <span class="math inline">\(x\)</span>-axis. Since we are working with sample data, we don’t expect the vertical spread of the residuals to be exactly equal as we move along the <span class="math inline">\(x\)</span>-axis (for example, there may be outliers). Therefore, similar to previous conditions, we are looking for obvious departures from equal variance to conclude that the condition is not met. <a href="#fig-equal-var-not-met" class="quarto-xref">Figure&nbsp;<span>6.5</span></a> shows an example using simulated data of plot of residuals versus fitted when the equal variance condition is not satisfied. There is a distinguishable “fan-shape” showing that the spread of the residuals increases as the predicted value increases. Additionally, keep in mind that we are examining the vertical spread for the majority of the data, not including outliers in the assessments as shown by the dotted lines in <a href="#fig-coffee-equal-var" class="quarto-xref">Figure&nbsp;<span>6.6</span></a> to serve as a guide as we assess equal variance.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-equal-var-not-met" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-equal-var-not-met-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-equal-var-not-met-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;6.5: Example of residuals from simulated data that violate the equal variance condition. The vertical spread of the residuals increases as the predicted value increases."><img src="06-slr-conditions_files/figure-html/fig-equal-var-not-met-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-equal-var-not-met-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.5: Example of residuals from simulated data that violate the equal variance condition. The vertical spread of the residuals increases as the predicted value increases.
</figcaption></figure>
</div>
</div>
</div>
<!--# Is there a way to draw the lines for checking equal variance?-->
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-equal-var" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-equal-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-equal-var-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;6.6: Plot of the residuals versus predicted values. The vertical spread is approximately for each predicted value, as shown by the residuals generally falling between the two dotted lines when moving along the x-axis."><img src="06-slr-conditions_files/figure-html/fig-coffee-equal-var-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-equal-var-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.6: Plot of the residuals versus predicted values. The vertical spread is approximately for each predicted value, as shown by the residuals generally falling between the two dotted lines when moving along the <span class="math inline">\(x\)</span>-axis.
</figcaption></figure>
</div>
</div>
</div>
<p>From <a href="#fig-coffee-equal-var" class="quarto-xref">Figure&nbsp;<span>6.6</span></a>, the vertical spread of the residuals is approximately equal, as the vast majority of the residuals are between the two dotted lines as we move along the <span class="math inline">\(x\)</span>-axis. Therefore, <strong>the equal variance condition is satisfied.</strong></p>
<!--# Consider including a test or more robust way to assess equal variance.-->
<div class="analysis_in_practice">
<p><strong>Checking model conditions</strong></p>
<ul>
<li><p><strong>Linearity</strong>: Plot residuals versus predicted values. Look for points to be randomly scattered around 0 on the <span class="math inline">\(y\)</span>-axis <span class="math inline">\((\text{residuals} = 0)\)</span> .</p></li>
<li><p><strong>Independence</strong>: Use the description of the data and data collection process to assess if the observations can reasonably be treated as independent. If data are collected over time, examine plot of residuals versus time to assess potential serial effect. If unaccounted for subgroups are represented in the data, examine plot of residuals versus predicted for each subgroup.</p></li>
<li><p><strong>Normality</strong>: Plot the distribution of the residuals. Look for a distribution that is approximately unimodal and symmetric.</p></li>
<li><p><strong>Equal variance</strong>: Plot the residuals versus predicted values. Look for approximately equal vertical spread as we move along the <span class="math inline">\(x\)</span>-axis.</p></li>
</ul>
</div>
</section></section><section id="sec-conditions-not-satisfied" class="level2" data-number="6.3"><h2 data-number="6.3" class="anchored" data-anchor-id="sec-conditions-not-satisfied">
<span class="header-section-number">6.3</span> Strategies when conditions aren’t satisfied</h2>
<p>If all the model conditions are satisfied, we can move on to the next step in the analysis; however, that is sometimes not the case in practice. The good news is we there are a variety of methods to address violations in the model conditions. Additionally, many of the analysis tasks we do are robust to violations in some of the model conditions, meaning we can still obtain reliable analysis results, even if some conditions are not satisfied.</p>
<p>For each model condition we will discuss the analysis tasks for which satisfying the model condition is very important and some approaches we can take to address the violations in the condition.</p>
<section id="linearity-1" class="level3" data-number="6.3.1"><h3 data-number="6.3.1" class="anchored" data-anchor-id="linearity-1">
<span class="header-section-number">6.3.1</span> Linearity</h3>
<p>The linearity condition is the most important condition, because the regression analysis relies on the assumption that the linear regression model adequately summarizes the relationship between the response and predictor variable (see <a href="04-slr.html#sec-slr-appropriate" class="quarto-xref"><span>Section 4.3.2</span></a>). Therefore, the linearity condition must be satisfied in order for any interpretations and conclusions from the regression analysis to be useful and reliable. This means it is necessary for fitting the linear model, interpreting the model coefficients, drawing conclusions inference conducted using simulation-based or theory-based methods.</p>
<p>If the linearity condition is not satisfied, we can ask ourselves a few questions:</p>
<ol type="1">
<li>Is the violation in the linearity condition due to the fact that there is, in fact, no evidence of a meaningful relationship between the response and predictor variable? In this case, reconsider if a linear regression model is the most useful way to understand these data.</li>
<li>Is the violation in the linearity condition because there is evidence of a meaningful non-linear relationship between the response and predictor variable? If this is the case, there are a few options to work with this non-linear relationship.
<ul>
<li>Add a higher-order term, for example <span class="math inline">\(x^2\)</span>, in the model to capture the non-linearity of the relationship. We discuss higher-order model terms in more detail in <a href="07-mlr.html" class="quarto-xref"><span>Chapter 7</span></a>. <!--# add reference at some point-->
</li>
<li>Apply a transformation on the response and/or predictor variable, so there is a linear relationship between the transformed variables. Then proceed with simple linear regression using the transformed variable(s). We discuss variable transformations in <a href="09-mlr-transformations.html" class="quarto-xref"><span>Chapter 9</span></a>.</li>
</ul>
</li>
</ol></section><section id="independence-1" class="level3" data-number="6.3.2"><h3 data-number="6.3.2" class="anchored" data-anchor-id="independence-1">
<span class="header-section-number">6.3.2</span> Independence</h3>
<p>The independence condition states that the residuals are independent of one another. This assurance is most important when estimating variability about the line or variability in the estimated regression coefficients when doing statistical inference. If the independence condition is not satisfied and some residuals are correlated with one another, then our procedures may underestimate the true variability about the regression line and ultimately the variability in the estimated regression coefficients. <!--# add link to inference chapter?--> This is due to the fact that each observation is not fully contributing new information, because there is some correlation between two or more observations. Thus the <strong>effective sample size</strong>, or how many observations independently provide information, is smaller than the true sample size <span class="math inline">\(n\)</span>. This could result in misleading inferential conclusions, such as concluding there is a linear relationship between the response and predictor variable, when in fact there is no such a relationship.</p>
<p>If the independence condition is not met, more advanced statistical methods would be required to properly deal with the correlated residuals. These methods are beyond the scope of this book, but you can learn more about these methods called <strong>multilevel models</strong> or <strong>hierarchical models</strong> in books such as <span class="citation" data-cites="roback2021beyond">Roback and Legler (<a href="references.html#ref-roback2021beyond" role="doc-biblioref">2021</a>)</span>.</p>
<p>If we observe some pattern in the residuals based on subgroup, then there are two approaches to address it. The first is creating a separate model for each subgroup. The primary disadvantage to this approach is that we may have a different estimate for the slope and intercept for each subgroup, and thus it may be more difficult to draw overall conclusions about the relationship between the response and predictor variables. The second option is to fit a model that includes the subgroup as a predictor. This will allow us to account for differences by subgroup while maintaining a single model that makes it easier to draw overall conclusions. This type of model is called a <strong>multiple linear regression</strong> model, because it includes more than one predictor variable. We will introduce these models more in detail in <a href="07-mlr.html" class="quarto-xref"><span>Chapter 7</span></a>.</p>
<p>If the violations in the independence condition are not addressed, we must use caution when drawing conclusions from the model or calculating predictions given the systematic under or over prediction by subgroup. In this case, we should consider if the model can be used to produce the type of valuable inferential insights we intend.</p>
<!--# needs some discussion about what to do if time is the issue-->
<!--# Need to work in that the condition doesn't really matter if you just want estimates of the slope and intercept with no plan to do inference-->
</section><section id="normality-1" class="level3" data-number="6.3.3"><h3 data-number="6.3.3" class="anchored" data-anchor-id="normality-1">
<span class="header-section-number">6.3.3</span> Normality</h3>
<p>By the Central Limit Theorem, we know the distribution of the estimate slope (the statistic of interest) is normal when the sample size is sufficiently large (see <a href="05-slr-inference.html#sec-slr-inf-clt" class="quarto-xref"><span>Section 5.8</span></a> for more details), regardless of the distribution of the original data. Therefore, when the sample size is “large enough”, we can be confident that the distribution of the estimated slope <span class="math inline">\(\hat{\beta}_1\)</span> is normal, even if the residuals (and thus the response variable) do not follow a normal distribution.</p>
<p>A common threshold for a “large enough” sample size is 30. This means if the sample has at least 30 observations (which is often the case for modern data sets!), we can use all the methods we’ve discussed to fit a simple linear regression model and draw conclusions from inference, even if the residuals are not normally distributed. Thus the inferential methods based on the Central Limit Theorem are considered robust to violations in the normality assumption, because we can feel confident about the conclusions from the inferential procedures even if the normality condition is not satisfied (given <span class="math inline">\(n &gt; 30\)</span>). One note of caution is that if the sample size is very close to 30, then the inferential methods based on the Central Limit Theorem are not robust to major departures form normality such as extreme skewness or outliers.</p>
<p>Recall from <a href="05-slr-inference.html" class="quarto-xref"><span>Chapter 5</span></a> the objective of simulation-based inference is to use the data to generate the sample distribution. Therefore, we do not make any assumptions about the sampling distribution of the estimated slopes. Because there are no assumptions about the sampling distribution, the normality condition is not required for simulation-based inferential procedures.</p>
<div class="analysis_in_practice">
<p>Thirty should not be treated as an absolute threshold. In other words, we should not treat data with a sample size of 29 materially different from data with a sample size of 31. If the sample size is small:</p>
<ul>
<li>The distribution of the residuals should not have large departures from normality, in order to have reliable conclusions from the CLT-based inferential results.</li>
<li>You can conduct simulation-based inference, because these methods do not rely any assumptions about the sampling distribution of <span class="math inline">\(\hat{\beta}_1\)</span>, and thus do not rely on assumptions about the distribution of the residuals.</li>
</ul>
</div>
</section><section id="equal-variance-1" class="level3" data-number="6.3.4"><h3 data-number="6.3.4" class="anchored" data-anchor-id="equal-variance-1">
<span class="header-section-number">6.3.4</span> Equal variance</h3>
<p>The equal variance condition is as assessment of whether the distribution of the residuals is approximately equal for each value of the predictor variable. This is equivalent to the distribution of the response about the line for each predictor variable. The <strong>regression standard error</strong> <span class="math inline">\(\hat{\sigma}_{\epsilon}\)</span> is the estimated value of this variability about the line, and it is the assumed to be the same for all values of the predictor (see <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a> for more detail). When conducting inference based on the Central Limit Theorem, this regression standard error is used to calculate <span class="math inline">\(SE_{\hat{\beta}_1}\)</span>, the estimated standard error for the estimated slopes. Thus similar to violations in the independence condition, if the variability about the regression line is not equal for all values of the predictor, the regression standard error will not be accurate and thus the standard error of the slope, our estimate of the sampling variability in this statistic will be inaccurate as well. The calculation of the confidence interval and test statistic for hypothesis testing both use <span class="math inline">\(SE_{\hat{\beta}_1}\)</span>, so these values will likely be inaccurate as well. Therefore, we should approach conclusions from the theory-based inferential procedures with caution if the equal variance condition is not met.</p>
<p>Similar to the normality condition, the equal variance condition is not required for simulation-based inference, because <span class="math inline">\(SE_{\hat{\beta}_1}\)</span> is estimated from the sampling distribution simulated from the data.</p>
<p>There are approaches for handling violations in the equal variance condition. These approaches typically involve performing a transformation on the response variable. We will discuss these further in @@sec-ch-transformations.</p>
</section><section id="recap" class="level3" data-number="6.3.5"><h3 data-number="6.3.5" class="anchored" data-anchor-id="recap">
<span class="header-section-number">6.3.5</span> Recap</h3>
<p><a href="#tbl-slr-conditions" class="quarto-xref">Table&nbsp;<span>6.3</span></a> provides a summary of the model conditions and whether they must be satisfied to reliably conduct each modeling task.</p>
<div id="tbl-slr-conditions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-slr-conditions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.3: Summary of necessary conditions for various analysis tasks on the slope
</figcaption><div aria-describedby="tbl-slr-conditions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 24%">
<col style="width: 29%">
<col style="width: 25%">
</colgroup>
<thead><tr class="header">
<th>Model condition</th>
<th>Interpret and predict</th>
<th>Simulation-based inference</th>
<th>Theory-based inference</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Linearity</td>
<td>Important</td>
<td>Important</td>
<td>Important</td>
</tr>
<tr class="even">
<td>Independence</td>
<td>Important</td>
<td>Important</td>
<td>Important</td>
</tr>
<tr class="odd">
<td>Normality</td>
<td>Not needed</td>
<td>Not needed</td>
<td>
<p>Not needed if <span class="math inline">\(n &gt; 30\)</span></p>
<p>Important if <span class="math inline">\(n &lt; 30\)</span></p>
</td>
</tr>
<tr class="even">
<td>Equal variance</td>
<td>Not needed</td>
<td>Not needed</td>
<td>Important</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>So far we have discussed the model conditions to assess whether the assumptions for simple linear regression reasonably hold true for our data. We have not, however, dealt with the presence of outliers in the data and the potential impact (or “influence”) they may have on the regression model. In the next section, we discuss measures we can use to identify and assess the potential impact of such outlying observations.</p>
</section></section><section id="sec-model-diagnostics" class="level2" data-number="6.4"><h2 data-number="6.4" class="anchored" data-anchor-id="sec-model-diagnostics">
<span class="header-section-number">6.4</span> Model diagnostics</h2>
<p>One challenge that may arise when doing regression analysis (or really any type of data analysis) is how to handle outliers in the data. Because we are focused on the linear relationship between two (and eventually three or more) variables, there are multiple ways in which the outliers may show up in our analysis:</p>
<ol type="1">
<li>Outlier in the value of the predictor variable</li>
<li>Outlier in the value of the response variable</li>
<li>Outlier outside the general pattern of the relationship between the response and predictor variables</li>
</ol>
<p>A single observation could fall into multiple categories. For example look at the outlier identified in <a href="#fig-coffee-eda" class="quarto-xref">Figure&nbsp;<span>6.1</span></a>. This observation is around the center of the distribution for the response variable <code>flavor</code> but has a low outlying value in terms of the predictor <code>aroma</code>. Therefore, it is an outlier as described by categories (1) and (3) above. There is a set of model diagnostics to assess if there are observations in the data that fall into one or more of these outlier scenarios, and more importantly, if any such outlying observations have an out-sized impact on the regression model.</p>
<section id="influential-points" class="level3" data-number="6.4.1"><h3 data-number="6.4.1" class="anchored" data-anchor-id="influential-points">
<span class="header-section-number">6.4.1</span> Influential points</h3>
<p>An observation is considered an <strong>influential point</strong> if the estimated regression coefficients noticeably differ when the point is included in the data used to fit the model versus when it is not. <a href="#fig-influential-point" class="quarto-xref">Figure&nbsp;<span>6.7</span></a> illustrates the potential impact an influential point can have on the estimated regression line. Additionally, influential points can affect <span class="math inline">\(SE_{\hat{\beta}_1}\)</span>, estimated standard error of the slope, which can result in unreliable inferential conclusions as described in the previous section.</p>
<div id="fig-influential-point" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-influential-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-influential-point" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-influential-point-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-influential-point-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-influential-point-1.png" class="lightbox" data-gallery="fig-influential-point" title="Figure&nbsp;6.7&nbsp;(a): With influential point"><img src="06-slr-conditions_files/figure-html/fig-influential-point-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-influential-point"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-influential-point-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) With influential point
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-influential-point" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-influential-point-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-influential-point-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-influential-point-2.png" class="lightbox" data-gallery="fig-influential-point" title="Figure&nbsp;6.7&nbsp;(b): Without influential point"><img src="06-slr-conditions_files/figure-html/fig-influential-point-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-influential-point"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-influential-point-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Without influential point
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-influential-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.7: Simulated data showing the effect of an infulential point representd by the red triangle. The slope of the line changes when the influential point is removed from the data set.
</figcaption></figure>
</div>
<p>Sometimes potential influential points can be identified in a scatterplot of the response versus predictor variable in the exploratory data analysis. In the EDA, we have called out these points as being outliers, as they are typically outside of the general trend of the relationship between the two variables. Identifying these points from the EDA can become more difficult, however, when there are multiple predictor variables (see <a href="07-mlr.html" class="quarto-xref"><span>Chapter 7</span></a>). Therefore, we will use a set of model diagnostics to identify observations that are outliers and perhaps more importantly, those that are influential.</p>
<p>There are three diagnostic measures to identify outliers and influential points:</p>
<ul>
<li>
<strong>Leverage:</strong> Identify observations that are outliers in the values of the predictor</li>
<li>
<strong>Standardized residuals:</strong> Identify observations that are outliers in the value of the response</li>
<li>
<strong>Cook’s distance:</strong> Identify observations that are influential (a combination of leverage and standardized residuals)</li>
</ul>
<p>Ultimately, we are most interested in examining Cook’s distance, because it provides the indication about each observation’s impact on the regression analysis. Cook’s distance takes into account information gleaned from leverage and standardized residuals, so we will introduce these diagnostics first.</p>
</section><section id="sec-slr-leverage" class="level3" data-number="6.4.2"><h3 data-number="6.4.2" class="anchored" data-anchor-id="sec-slr-leverage">
<span class="header-section-number">6.4.2</span> Leverage</h3>
<p>The <strong>leverage</strong> of the <span class="math inline">\(i^{th}\)</span> observation is a measure of the distance between its value of the predictor, <span class="math inline">\(x_i\)</span>, and the average value of the predictor across all <span class="math inline">\(n\)</span> observations, <span class="math inline">\(\bar{x} = \frac{1}{n}\sum_{j=1}^n x_j\)</span>.</p>
<p>When doing simple linear regression, an observation’s leverage, denoted <span class="math inline">\(h_i\)</span>, is calculated using <a href="#eq-slr-leverage" class="quarto-xref">Equation&nbsp;<span>6.1</span></a>.</p>
<p><span id="eq-slr-leverage"><span class="math display">\[
h_i = \frac{1}{n} + \frac{(x_i - \bar{x})^2}{\sum_{j=1}^n(x_j - \bar{x})^2}
\tag{6.1}\]</span></span></p>
<!--# Maybe provide more explanation about where this formula comes from?-->
<p>The values of the leverage are between <span class="math inline">\(\frac{1}{n}\)</span> and 1 for each observation in the data set, and the average value of leverage across all <span class="math inline">\(n\)</span> observations is <span class="math inline">\(\frac{(p+1)}{n}\)</span>, where <span class="math inline">\(p\)</span> is the number of predictors in the model. In simple linear regression <span class="math inline">\(p = 1\)</span>, thus the average leverage is <span class="math inline">\(\frac{2}{n}\)</span>.</p>
<p>An observation is considered to have <em>large leverage</em> if its leverage is greater than <span class="math inline">\(\frac{2(p+1)}{n}\)</span> , i.e., greater than <span class="math inline">\(\frac{2 \times 2}{n}\)</span> for simple linear regression. This means that an observation is considered to have large leverage if its value of leverage is greater than twice the average value of leverage for the observations in the data set.</p>
<!--# briefly explain why we're using h and point reader to appendix for details in matrix notation-->
<div class="analysis_in_practice">
<p>Leverage only depends on the values of the predictor variable(s). It does <u><strong>not</strong></u> depend on values of the response.</p>
</div>
<p>Let’s take a look at the leverage for the observations in the coffee ratings data set. There are 1338 observations in the data and one predictor variable, so the threshold for identifying observations with large leverage is <span class="math inline">\(\frac{2 \times 2}{1338} =\)</span> 0.003.</p>
<p><a href="#fig-coffee-leverage" class="quarto-xref">Figure&nbsp;<span>6.8</span></a> is a visualization of the leverage for each observation in the data set. The red, horizontal dotted line marks the threshold for identifying points as having large leverage. There are 114 observations that have large leverage.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-leverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-leverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-leverage-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;6.8: Leverage for observations in the coffee ratings data"><img src="06-slr-conditions_files/figure-html/fig-coffee-leverage-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-leverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.8: Leverage for observations in the coffee ratings data
</figcaption></figure>
</div>
</div>
</div>
<div class="yourturn">
<p>There are 114 observations that have large values for the leverage. What does it mean for an observation to have “large leverage” in the context of the coffee data?</p>
</div>
<p>Let’s take a look at the observations with the largest values of leverage to get a better understanding about which points may be large leverage.</p>
<div class="cell">
<div id="tbl-coffee-large-leverage" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coffee-large-leverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.4: Observations with the top five highest values for leverage
</figcaption><div aria-describedby="tbl-coffee-large-leverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Leverage</th>
<th style="text-align: right;">aroma</th>
<th style="text-align: right;">flavor</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">5.08</td>
<td style="text-align: right;">7.75</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">6.17</td>
<td style="text-align: right;">6.50</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.012</td>
<td style="text-align: right;">6.33</td>
<td style="text-align: right;">6.50</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">8.67</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">6.42</td>
<td style="text-align: right;">6.50</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Recall that the leverage only depends on the values of the predictor variable, so we only need to consider <code>aroma</code> to better understand why these points are large leverage. From the EDA in <a href="#sec-coffee-intro" class="quarto-xref"><span>Section 6.1</span></a>, the average aroma grade in the data set is 7.572 points and the standard deviation is 0.316 . The observations with the largest values of leverage have aroma grades that are either much higher (e.g., 8.75) or much lower (e.g., 5.08) than the average. Thus the large leverage points includes coffees that both smell much better and perhaps much worse than the majority of the coffees in the data.</p>
<p>Even when we identify points with large leverage, we still want to understand how these points are (or are not) influencing the model results. Thus, knowing an observation has large leverage is not enough to warrant any specific action. We’ll examine Cook’s distance to determine if the observation is influential in the model in <a href="#sec-cooks-distance" class="quarto-xref"><span>Section 6.4.4</span></a> and discuss approaches to deal with such influential points in <a href="#sec-outliers-impact" class="quarto-xref"><span>Section 6.4.5</span></a> .</p>
</section><section id="sec-slr-std-resid" class="level3" data-number="6.4.3"><h3 data-number="6.4.3" class="anchored" data-anchor-id="sec-slr-std-resid">
<span class="header-section-number">6.4.3</span> Standardized residuals</h3>
<p>The residual is an indication of how well the regression model predicts the value of the response for a given observation. One reason the model may predict poorly for an observation is because it has an observed value of the response that is much different than the rest of the data. Therefore residuals can be used to identify observations that are outliers based on Scenario 2 in <a href="#sec-model-diagnostics" class="quarto-xref"><span>Section 6.4</span></a>. We will examine the magnitude of the residuals <span class="math inline">\(|e_i|\)</span> to identify such points, because residuals can be positive (model underpredicted) or negative (model overpredicted).</p>
<p>The residuals have the same units as the response variable, so what is considered a residual with large magnitude depends on the scale and range of the response variable. This means what is considered a “large” residuals can be different for every analysis. We can address this by instead examining <strong>standardized residuals</strong>, defined as the residual divided by its standard error. <a href="#eq-std-resid" class="quarto-xref">Equation&nbsp;<span>6.2</span></a> shows the formula to calculate the standardized residual for the <span class="math inline">\(i^{th}\)</span> observation.</p>
<p><span id="eq-std-resid"><span class="math display">\[
std.resid_i = \frac{e_i}{SE_{e_i}} = \frac{e_i}{\hat{\sigma}_{\epsilon} \sqrt{1 - h_i}}
\tag{6.2}\]</span></span></p>
<p>The residuals for every analysis are now on the same scale. Thus, we can use a common threshold to determine residuals that are considered to have large magnitude. An observation is an outlier in the response if it its standardized residual has a magnitude greater than two, <span class="math inline">\(|std.resid_i| &gt; 2\)</span> (<span class="math inline">\(std.resid_i &lt; - 2 \hspace{1mm} \text{ or }\hspace{1mm} std.resid_i &gt; 2\)</span>). For large data sets, we recommend a more restrictive threshold of 3, so there is not an overwhelming number of observations considered outliers that may require further evaluation.</p>
<div class="analysis_in_practice">
<p>One assumption for linear regression is that the residuals are normally distributed and centered at 0 (see <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a>). This means the standardized residuals are normally distributed with mean of 0 and standard deviation of 1, <span class="math inline">\(N(0,1)\)</span>. In a standard normal distribution, we expect about 95% of the observations to have values between -2 and 2. By setting 2 as the threshold, we are essentially identifying the 5% of observations with the most extreme (high and low) residuals.</p>
<p>If there are a lot of observations, it may not be practical to closely examine the approximately 5% of observations that were identified as potential outliers. Thus we may use a more restrictive threshold, e.g., <span class="math inline">\(|std.resid_i| &gt; 3\)</span> (or higher) to identify points worth more close examination or only focus on those that are identified as influential points by Cook’s distance.</p>
</div>
<!--# add callout connecting large standardized residuals to large leverage?-->
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-stdresid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-stdresid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-stdresid-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;6.9: Standardized residuals versus observation number for model of flavor and aroma"><img src="06-slr-conditions_files/figure-html/fig-coffee-stdresid-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-stdresid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.9: Standardized residuals versus observation number for model of <code>flavor</code> and <code>aroma</code>
</figcaption></figure>
</div>
</div>
</div>
<!--# maybe use visualization to show why these have big std residuals-->
<p><a href="#fig-coffee-stdresid" class="quarto-xref">Figure&nbsp;<span>6.9</span></a> shows 12 observations with large magnitude residuals based on the threshold <span class="math inline">\(\pm 3\)</span> . This includes observations that have positive residuals with large magnitude (indicating the model greatly underpredicted) and observations with negative residuals with large magnitude (indicating the model greatly overpredicted).</p>
<p>These five observations with the largest magnitude residuals are shown in <a href="#tbl-coffee-large-resid" class="quarto-xref">Table&nbsp;<span>6.5</span></a>.</p>
<!--# think of a way to visualize observations with large magnitude residuals-->
<div class="cell">
<div id="tbl-coffee-large-resid" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coffee-large-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.5: Observations with large magnitude residuals
</figcaption><div aria-describedby="tbl-coffee-large-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">aroma</th>
<th style="text-align: right;">flavor</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.std.resid</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">5.08</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">5.53</td>
<td style="text-align: right;">9.90</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.17</td>
<td style="text-align: right;">6.08</td>
<td style="text-align: right;">7.20</td>
<td style="text-align: right;">-4.90</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.17</td>
<td style="text-align: right;">6.17</td>
<td style="text-align: right;">7.20</td>
<td style="text-align: right;">-4.51</td>
</tr>
<tr class="even">
<td style="text-align: right;">7.92</td>
<td style="text-align: right;">6.83</td>
<td style="text-align: right;">7.80</td>
<td style="text-align: right;">-4.25</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7.00</td>
<td style="text-align: right;">6.17</td>
<td style="text-align: right;">7.07</td>
<td style="text-align: right;">-3.92</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We see from <a href="#tbl-coffee-large-resid" class="quarto-xref">Table&nbsp;<span>6.5</span></a> and <a href="#fig-coffee-large-resid" class="quarto-xref">Figure&nbsp;<span>6.10</span></a> that these observations have flavor ratings that are lower than would be expected from the model based on their aroma ratings. The exception is the observation with the largest magnitude standardized residual that has a higher actual flavor rating than the model predicts based on its very low aroma rating.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-large-resid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-large-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-large-resid-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;6.10: Flavor grade versus aroma grade. Points marked with a red triangle are the observations with large standardized residuals with magnitude > 3."><img src="06-slr-conditions_files/figure-html/fig-coffee-large-resid-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-large-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.10: Flavor grade versus aroma grade. Points marked with a red triangle are the observations with large standardized residuals with magnitude &gt; 3.
</figcaption></figure>
</div>
</div>
</div>
<div class="analysis_in_practice">
<p>We can use a plot of standardized residuals versus predicted values such as the one in <a href="#fig-coffee-stdresid" class="quarto-xref">Figure&nbsp;<span>6.9</span></a> to check the linearity and equal variance conditions from <a href="#sec-model-conditions" class="quarto-xref"><span>Section 6.2</span></a>.</p>
</div>
<p>As with observations that have large leverage, we want to assess whether these points have out-sized influence on the model coefficients to help determine how to deal with these outliers (or if we need to do anything at all). To do so, we will look at the last diagnostic, Cook’s distance.</p>
</section><section id="sec-cooks-distance" class="level3" data-number="6.4.4"><h3 data-number="6.4.4" class="anchored" data-anchor-id="sec-cooks-distance">
<span class="header-section-number">6.4.4</span> Cook’s distance</h3>
<p>At this point we have introduced a diagnostic to identify outliers in the predictor variable (leverage) and one to identify outliers in the response variable (standardized residuals). Now we will use a single measure that combines information from the leverage and standardized residuals to identify potential influential points. This measure is called Cook’s distance.</p>
<p><strong>Cook’s distance</strong> is a measure of an observation’s overall impact on the estimated model coefficients. In <a href="#eq-cooks-d" class="quarto-xref">Equation&nbsp;<span>6.3</span></a>, we see that Cook’s distance takes into account an observation’s leverage, <span class="math inline">\(h_i\)</span>, the standardized residuals, <span class="math inline">\(std.resid_i\)</span>, and the number of predictors in the model, <span class="math inline">\(p\)</span> ( <span class="math inline">\(p=1\)</span> for simple linear regression).</p>
<p><span id="eq-cooks-d"><span class="math display">\[
D_i = \frac{1}{p}(std.resid_i)^2\Big(\frac{h_i}{1-h_i}\Big)
\tag{6.3}\]</span></span></p>
<!--# add something referring reader to the appendix-->
<!--# do i need to explain cook's distance? I think that's out of scope - maybe put something in the appendix?-->
<p>As with leverage and standardized residuals, there are thresholds we use to determine if a point is potentially influential. A commonly used threshold is 1. If an observation has a Cook’s distance greater than 1, <span class="math inline">\(D_i &gt; 1\)</span>, it is considered an influential point and is worth closer examination given its potential influence on the model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-coffee-cooksd" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-coffee-cooksd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="06-slr-conditions_files/figure-html/fig-coffee-cooksd-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;6.11: Cook’s distance versus observation number for coffee ratings data"><img src="06-slr-conditions_files/figure-html/fig-coffee-cooksd-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coffee-cooksd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.11: Cook’s distance versus observation number for coffee ratings data
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-coffee-cooksd" class="quarto-xref">Figure&nbsp;<span>6.11</span></a> shows the values of Cook’s distance for the observations in the data set. It includes a horizontal line at 1 marking the threshold for determining if an observation is influential. There is one observation in the data that has a value of Cook’s distance greater than 1; its value is 2.432. This is the observation with an aroma grade of <code>large_cooks$aroma</code> and flavor grade of <code>large_cooks$flavor</code>.</p>
</section><section id="sec-outliers-impact" class="level3" data-number="6.4.5"><h3 data-number="6.4.5" class="anchored" data-anchor-id="sec-outliers-impact">
<span class="header-section-number">6.4.5</span> Handling influential points</h3>
<p>To better understand the impact of influential points, let’s take a look at our model fit with and without the influential observation.</p>
<div class="cell">
<div id="tbl-influential-impact" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-influential-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.6: Estimated model coefficients for model with and without influential observation
</figcaption><div aria-describedby="tbl-influential-impact-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Term</th>
<th style="text-align: right;">With Influential Point</th>
<th style="text-align: right;">Without Influential Point</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.47</td>
<td style="text-align: right;">1.137</td>
</tr>
<tr class="even">
<td style="text-align: left;">aroma</td>
<td style="text-align: right;">0.80</td>
<td style="text-align: right;">0.843</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>In <a href="#tbl-influential-impact" class="quarto-xref">Table&nbsp;<span>6.6</span></a>, the estimates for the intercept and coefficient of <code>aroma</code> change based on whether the influential point is included or not included in the data. Therefore, it is now our task as the data scientist to determine how to best proceed given the influential point.</p>
<section id="outlier-based-on-predictor" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="outlier-based-on-predictor">Outlier based on predictor</h4>
<p>If an observation is an outlier based on the predictor variable, first consider if it is the result of a data entry error that can be fixed. If not, one option is to remove this observation from the analysis, particularly if the outlier is an influential point or a result of a data entry error. Doing so limits the scope of the conclusions that can be drawn from the analysis and the range of values for which the model can be used for prediction, because removing the outlying observation narrows the range of possible values for the predictor. When taking this approach, it is important to mention it when communicating results. Additionally, we need to be careful not to extrapolate if using the model for prediction. <!--# maybe clarify this a bit?--></p>
<p>The influential point identified in <a href="#sec-cooks-distance" class="quarto-xref"><span>Section 6.4.4</span></a> is an outlier because it has a value of the predictor much lower than the rest of the data. Therefore, we could remove this observation and thus limit the scope of the analysis to coffee that has an aroma rating of 6 or higher. We can also keep this observation in the analysis and thus have some information about coffees with aroma ratings less than 6. Given there is a single observation with a rating less than 6, however, conclusions about coffees with low coffee ratings should be made with caution.</p>
</section><section id="outlier-based-on-response" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="outlier-based-on-response">Outlier based on response</h4>
<p>If the observation is an outlier based on the value of the response variable, first consider if it is the result of a data entry error. If it is not and the value of the predictor is within the range of the other observations in the data, the observation should not be removed from the analysis. Removing the observation could result in taking out useful information for understanding the relationship between the response and predictor variable.</p>
<p>If the outlier is influential, one approach is to build the model with and without the influential point, then compare the estimated values and inference for the model coefficients. Another approach is to transform the response variable to reduce the effect of outliers (more on transformations in @@sec-ch-transformations). A last approach is to collect more data, so the model information can be informed by more observations; however, collecting more data is often not feasible in practice.</p>
</section></section></section><section id="sec-model-in-practice" class="level2" data-number="6.5"><h2 data-number="6.5" class="anchored" data-anchor-id="sec-model-in-practice">
<span class="header-section-number">6.5</span> Modeling in practice</h2>
<p>In this chapter, we have introduced a set of model conditions and diagnostics to evaluate how well the model fits the data and satisfies the assumptions for linear regression. Now we’ll conclude the chapter by discussing how we might incorporate these tools in practice.</p>
<ol type="1">
<li><p><strong>Exploratory data analysis (EDA)</strong>: Start every regression analysis with some exploratory data analysis, as in <a href="#sec-coffee-intro" class="quarto-xref"><span>Section 6.1</span></a> . The EDA will help you better understand the data, particularly the variables that will be used in the regression model. Through the EDA we may also notice points that stand out as potential outliers and potential influential points that may be of interest for further exploration. The EDA can provide valuable insights about the data; however, it cannot be used alone to confirm whether the model is a good fit or confirm if a point is influential. We need the model conditions and diagnostics to make such a robust assessment. The EDA is important, however, to help determine the best analysis approach and to understand the data enough to more fully understand the model interpretations and influential conclusions.</p></li>
<li><p><strong>Model fitting:</strong> Fit the regression model.</p></li>
<li>
<p><strong>Model conditions and diagnostics</strong>: Check the model conditions (LINE) to assess whether the model is a good fit for the data.</p>
<p>Then, check Cook’s distance to determine if there are potential influential points in the data.</p>
<ul>
<li><p>If there are influential points, check the leverage and standardized residuals to try to understand why these points are influential. Use this information, along with the analysis objective and subject matter expertise, to determine how to best proceed with the dealing with these points.</p></li>
<li><p>If there are no influential points, we can examine the leverage and standardized residuals for a deeper understanding of the data; however, no further action is needed in terms of refitting the model.</p></li>
</ul>
<p>Make any adjustments as needed based on the model conditions and diagnostics.</p>
<div class="analysis_in_practice">
<p>Modeling in practice is an iterative process. We repeat Steps 2 and 3 until we find a model that is the best fit for the data.</p>
</div>
</li>
<li><p><strong>Prediction and inference</strong>: Once the model is finalized, and we are satisfied with the results of the model conditions and diagnostics, then we can use the model for prediction and inference to answer the analysis questions.</p></li>
<li><p><strong>Communication</strong>: Once we have the final inferential results and predictions, communicate the overall conclusions in a way that can be easily understood by the intended audience.</p></li>
</ol>
<!--# add something here dealing with the outlier we found--></section><section id="sec-conditions-in-r" class="level2" data-number="6.6"><h2 data-number="6.6" class="anchored" data-anchor-id="sec-conditions-in-r">
<span class="header-section-number">6.6</span> Model conditions and diagnostics in R</h2>
<p>The residuals, along with other observation-level statistics, can be obtained using <code>augment()</code> in the <strong>broom</strong> R package <span class="citation" data-cites="broom">(<a href="references.html#ref-broom" role="doc-biblioref">Robinson, Hayes, and Couch 2023</a>)</span>. This package is in the suite of packages that are included as part of <strong>tidymodels</strong><span class="citation" data-cites="tidymodels">(<a href="references.html#ref-tidymodels" role="doc-biblioref">Kuhn and Wickham 2020</a>)</span>. The output produced by this function is shown in <a href="#tbl-coffee-aug" class="quarto-xref">Table&nbsp;<span>6.7</span></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">coffee_model</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">flavor</span> <span class="op">~</span> <span class="va">aroma</span>, data <span class="op">=</span> <span class="va">coffee_ratings</span><span class="op">)</span></span>
<span></span>
<span><span class="va">coffee_model_aug</span> <span class="op">&lt;-</span> <span class="fu">augment</span><span class="op">(</span><span class="va">coffee_model</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div id="tbl-coffee-aug" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-coffee-aug-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.7: First ten rows of output produced by the <code>augment</code> function
</figcaption><div aria-describedby="tbl-coffee-aug-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">flavor</th>
<th style="text-align: right;">aroma</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.resid</th>
<th style="text-align: right;">.hat</th>
<th style="text-align: right;">.sigma</th>
<th style="text-align: right;">.cooksd</th>
<th style="text-align: right;">.std.resid</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">8.83</td>
<td style="text-align: right;">8.67</td>
<td style="text-align: right;">8.40</td>
<td style="text-align: right;">0.4259</td>
<td style="text-align: right;">0.00978</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">0.01715</td>
<td style="text-align: right;">1.864</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.67</td>
<td style="text-align: right;">8.75</td>
<td style="text-align: right;">8.47</td>
<td style="text-align: right;">0.2019</td>
<td style="text-align: right;">0.01114</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.00440</td>
<td style="text-align: right;">0.884</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8.50</td>
<td style="text-align: right;">8.42</td>
<td style="text-align: right;">8.20</td>
<td style="text-align: right;">0.2959</td>
<td style="text-align: right;">0.00613</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.00515</td>
<td style="text-align: right;">1.293</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.58</td>
<td style="text-align: right;">8.17</td>
<td style="text-align: right;">8.00</td>
<td style="text-align: right;">0.5758</td>
<td style="text-align: right;">0.00342</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">0.01084</td>
<td style="text-align: right;">2.513</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8.50</td>
<td style="text-align: right;">8.25</td>
<td style="text-align: right;">8.07</td>
<td style="text-align: right;">0.4319</td>
<td style="text-align: right;">0.00419</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">0.00747</td>
<td style="text-align: right;">1.885</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.42</td>
<td style="text-align: right;">8.58</td>
<td style="text-align: right;">8.33</td>
<td style="text-align: right;">0.0878</td>
<td style="text-align: right;">0.00836</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.00062</td>
<td style="text-align: right;">0.384</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8.50</td>
<td style="text-align: right;">8.42</td>
<td style="text-align: right;">8.20</td>
<td style="text-align: right;">0.2959</td>
<td style="text-align: right;">0.00613</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.00515</td>
<td style="text-align: right;">1.293</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.33</td>
<td style="text-align: right;">8.25</td>
<td style="text-align: right;">8.07</td>
<td style="text-align: right;">0.2619</td>
<td style="text-align: right;">0.00419</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.00275</td>
<td style="text-align: right;">1.143</td>
</tr>
<tr class="odd">
<td style="text-align: right;">8.67</td>
<td style="text-align: right;">8.67</td>
<td style="text-align: right;">8.40</td>
<td style="text-align: right;">0.2658</td>
<td style="text-align: right;">0.00978</td>
<td style="text-align: right;">0.230</td>
<td style="text-align: right;">0.00668</td>
<td style="text-align: right;">1.164</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.58</td>
<td style="text-align: right;">8.08</td>
<td style="text-align: right;">7.93</td>
<td style="text-align: right;">0.6479</td>
<td style="text-align: right;">0.00268</td>
<td style="text-align: right;">0.229</td>
<td style="text-align: right;">0.01072</td>
<td style="text-align: right;">2.826</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We use the following columns produced by <code>augment()</code> to check model conditions and diagnostics:</p>
<ul>
<li>
<code>.fitted</code>: Predicted values</li>
<li>
<code>.resid</code>: Residuals</li>
<li>
<code>.hat</code>: Leverage</li>
<li>
<code>.cooksd</code>: Cook’s distance</li>
<li>
<code>.std.resid</code>: Standardized residuals</li>
</ul>
<p>The plots used to check the model conditions and diagnostics are produced using <code>ggplot()</code> functions. We can also produce similar plots in base R format using the <code>plot</code> function. The QQ-plot produced from <code><a href="https://rdrr.io/r/graphics/plot.default.html">plot()</a></code> is used to check the normality condition. The distribution of the residuals is approximately normal if the points lie along the diagonal line.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="06-slr-conditions_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="06-slr-conditions_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="06-slr-conditions_files/figure-html/unnamed-chunk-4-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="06-slr-conditions_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="06-slr-conditions_files/figure-html/unnamed-chunk-4-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="06-slr-conditions_files/figure-html/unnamed-chunk-4-3.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="06-slr-conditions_files/figure-html/unnamed-chunk-4-4.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="06-slr-conditions_files/figure-html/unnamed-chunk-4-4.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</section><section id="summary" class="level2" data-number="6.7"><h2 data-number="6.7" class="anchored" data-anchor-id="summary">
<span class="header-section-number">6.7</span> Summary</h2>
<p>In this chapter, we introduced model conditions and diagnostics to evaluate the fit of a simple linear regression model. We discussed the LINE model conditions: linearity, independence, normality, and equal variance, and how they are used to check the assumptions for linear regression. We also discussed scenarios in which assumptions are important or may be relaxed. We used model diagnostics, specifically Cook’s distance, leverage, and standardized residuals, to identify outliers. We discussed strategies for handling influential points that may impact model results. We concluded by describing the full process of modeling in practice and how to implement the concepts from this chapter in R.</p>
<p>Thus far, we have discussed simple linear regression, using one predictor variable to understand variability in a response variable. In the next chapter, we will extend what we know about simple linear regression to models with two or more predictor variables, called <em>multiple linear regression</em>.</p>
<!--# Exercises -->
<!--# Exercise idea: Can you make the plot using X instead of the fitted values. Why or why not?-->
<!--# does this chapter need more "your turn" opportunities?-->


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-tidytuesday" class="csl-entry" role="listitem">
Community, Data Science Learning. 2024. <span>“Tidy Tuesday: A Weekly Social Data Project.”</span> <a href="https://tidytues.day">https://tidytues.day</a>.
</div>
<div id="ref-tidymodels" class="csl-entry" role="listitem">
Kuhn, Max, and Hadley Wickham. 2020. <span>“Tidymodels: A Collection of Packages for Modeling and Machine Learning Using Tidyverse Principles.”</span> <a href="https://www.tidymodels.org">https://www.tidymodels.org</a>.
</div>
<div id="ref-roback2021beyond" class="csl-entry" role="listitem">
Roback, Paul, and Julie Legler. 2021. <em>Beyond Multiple Linear Regression: Applied Generalized Linear Models and Multilevel Models in r</em>. Chapman; Hall/CRC.
</div>
<div id="ref-broom" class="csl-entry" role="listitem">
Robinson, David, Alex Hayes, and Simon Couch. 2023. <span>“Broom: Convert Statistical Objects into Tidy Tibbles.”</span> <a href="https://CRAN.R-project.org/package=broom">https://CRAN.R-project.org/package=broom</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The null hypothesis is there is no linear relationship between <code>aroma</code> and <code>flavor</code> <span class="math inline">\((H_0: \beta_1 = 0)\)</span> and the alternative is that there is a linear relationship <span class="math inline">\((H_a:\beta_1 \neq 0)\)</span>. The p-value is <span class="math inline">\(\approx 0\)</span>, so we reject the null hypothesis. The data provide evidence of a linear relationship between the two variables. The confidence interval is consistent, because 0 is not in the interval.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/introregressio\.netlify\.app");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./05-slr-inference.html" class="pagination-link" aria-label="Inference for simple linear regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inference for simple linear regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-mlr.html" class="pagination-link" aria-label="Multiple linear regression">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple linear regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/matackett/regression-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>