<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Maria Tackett">
<title>9&nbsp; Variable transformations – Introduction to Regression Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-model-eval.html" rel="next">
<link href="./08-mlr-inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-31c3c5ec0f84e3846e28bd1517aa8340.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script defer="" data-domain="https://matackett.github.io/regression-book/" src="https://plausible.io/js/script.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-mlr.html">Part 3: Multiple linear regression</a></li><li class="breadcrumb-item"><a href="./09-mlr-transformations.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variable transformations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Regression Analysis</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/matackett/regression-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 1: Getting started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Regression in the data science workflow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-review-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data analysis in R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-eda.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Exploratory data analysis</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 2: Simple linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-slr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Inference for simple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-slr-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Model conditions and diagnostics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 3: Multiple linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-mlr-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for multiple linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-mlr-transformations.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variable transformations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-model-eval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model selection</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part 4: Beyond linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-logistic-prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Logistic regression: Prediction and evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-special-topics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Special topics</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathematics of linear regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Mathematics of logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Data sets</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#learning-goals" id="toc-learning-goals" class="nav-link active" data-scroll-target="#learning-goals">Learning goals</a></li>
  <li>
<a href="#sec-transform-eda" id="toc-sec-transform-eda" class="nav-link" data-scroll-target="#sec-transform-eda"><span class="header-section-number">9.1</span> Introduction: College basketball expenditures</a>
  <ul class="collapse">
<li><a href="#sec-ncaa-eda" id="toc-sec-ncaa-eda" class="nav-link" data-scroll-target="#sec-ncaa-eda"><span class="header-section-number">9.1.1</span> Exploratory data analysis</a></li>
  <li><a href="#initial-model" id="toc-initial-model" class="nav-link" data-scroll-target="#initial-model"><span class="header-section-number">9.1.2</span> Initial model</a></li>
  </ul>
</li>
  <li><a href="#sec-transform-logy" id="toc-sec-transform-logy" class="nav-link" data-scroll-target="#sec-transform-logy"><span class="header-section-number">9.2</span> Transformation on the response variable</a></li>
  <li><a href="#sec-transform-logx" id="toc-sec-transform-logx" class="nav-link" data-scroll-target="#sec-transform-logx"><span class="header-section-number">9.3</span> Transformation on predictor variable(s)</a></li>
  <li><a href="#sec-transform-logx-logy" id="toc-sec-transform-logx-logy" class="nav-link" data-scroll-target="#sec-transform-logx-logy"><span class="header-section-number">9.4</span> Transformation on the response variable and predictor variable(s)</a></li>
  <li>
<a href="#sec-transform-choose-model" id="toc-sec-transform-choose-model" class="nav-link" data-scroll-target="#sec-transform-choose-model"><span class="header-section-number">9.5</span> Choosing a model</a>
  <ul class="collapse">
<li><a href="#adding-interaction-term" id="toc-adding-interaction-term" class="nav-link" data-scroll-target="#adding-interaction-term"><span class="header-section-number">9.5.1</span> Adding interaction term</a></li>
  </ul>
</li>
  <li><a href="#variable-transformations-in-r" id="toc-variable-transformations-in-r" class="nav-link" data-scroll-target="#variable-transformations-in-r"><span class="header-section-number">9.6</span> Variable transformations in R</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9.7</span> Summary</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/matackett/regression-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./07-mlr.html">Part 3: Multiple linear regression</a></li><li class="breadcrumb-item"><a href="./09-mlr-transformations.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variable transformations</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-ch-transformations" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Variable transformations</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="learning-goals" class="level2 unnumbered"><h2 class="unnumbered anchored" data-anchor-id="learning-goals">Learning goals</h2>
<ul>
<li>Identify when a variable transformation is needed to summarize the relationship between a response variable and predictor variable(s)</li>
<li>Explain the role of variance-stabilizing transformations in regression analysis</li>
<li>Fit and interpret models with a log-transformed response variable</li>
<li>Fit and interpret models with one or more log-transformed predictor variables</li>
</ul>
<!--#
## R packages {.unnumbered}

-   `tidyverse` [@tidyverse]
-   `tidymodels` [@tidymodels-2]
-   `knitr` [@knitr]
--></section><section id="sec-transform-eda" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="sec-transform-eda">
<span class="header-section-number">9.1</span> Introduction: College basketball expenditures</h2>
<!--# [INSERT SOME HOOK ABOUT MARCH MADNESS AND NCAA BASKETBALL].-->
<p>The analysis in this chapter focuses on the amount of money colleges and universities spend in total on men’s and women’s basketball programs in a single year. The data come from the Equity in Athletics Data Analysis (EADA) tool from the Office of Postsecondary Education in the United States Department of Education (<a href="https://ope.ed.gov/athletics/#/">ope.ed.gov/athletics</a>). Every college and university in the United States that offers both student financial aid and intercollegiate programs (this includes nearly all colleges and universities) are required by law to submit information about its spending and revenue on athletic programs annually <span class="citation" data-cites="ope_equity_athletics_database">(<a href="references.html#ref-ope_equity_athletics_database" role="doc-biblioref">U.S. Department of Education, Office of Postsecondary Education 2025</a>)</span>.</p>
<p>The EADA is a very rich data set with over 300 hundred variables about basketball and all other collegiate sports for all 2-year and 4-year institutions that meet the federal reporting requirements.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> This analysis will focus on data from schools in the National Collegiate Athletics Association (NCAA) Division I. According to the NCAA, Division I institutions are those that “have to sponsor at least seven sports for men and seven for women (or six for men and eight for women) with two team sports for each gender. Each playing season has to be represented by each gender as well. There are contest and participant minimums for each sport, as well as scheduling criteria” <span class="citation" data-cites="ncaa_divisional_differences_2013">(<a href="references.html#ref-ncaa_divisional_differences_2013" role="doc-biblioref">NCAA 2013</a>)</span>. We will refer to these institutions as “NCAA Division I colleges” or just “colleges” throughout the remainder of the chapter.</p>
<p>The data in <code>ncaa-basketball-DI-2023-2024.csv</code> contains data from the 2023 - 2024 academic year. We will use the following variables that have been derived from variables in the EADA.</p>
<ul>
<li>
<code>expenditure_m</code>: Total expenditure on basketball programs (in millions of US dollars)</li>
<li>
<code>enrollment_th</code>: Total student enrollment (in thousands)</li>
<li>
<code>type</code>: Whether the college is public or private</li>
<li>
<code>region</code>: Region where the college is located. The regions are defined using the <code>state.region</code> vector in R.</li>
</ul>
<div class="objective">
<p>The goal of this analysis is to use the student enrollment, region, and type of college to explain variability in the total expenditure on basketball programs in the 2023 - 2024 academic year.</p>
</div>
<section id="sec-ncaa-eda" class="level3" data-number="9.1.1"><h3 data-number="9.1.1" class="anchored" data-anchor-id="sec-ncaa-eda">
<span class="header-section-number">9.1.1</span> Exploratory data analysis</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ncaa-response-eda" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-response-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-response-eda-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;9.1: Distribution of the response variable expenditure_m"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-response-eda-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-response-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Distribution of the response variable <code>expenditure_m</code>
</figcaption></figure>
</div>
</div>
</div>
<div id="fig-ncaa-pred-eda" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-pred-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-pred-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-pred-eda-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-pred-eda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-pred-eda-1.png" class="lightbox" data-gallery="fig-ncaa-pred-eda" title="Figure&nbsp;9.2&nbsp;(a): enrollment_th"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-pred-eda-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-pred-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-pred-eda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <code>enrollment_th</code>
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-pred-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-pred-eda-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-pred-eda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-pred-eda-2.png" class="lightbox" data-gallery="fig-ncaa-pred-eda" title="Figure&nbsp;9.2&nbsp;(b): region"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-pred-eda-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-pred-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-pred-eda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <code>region</code>
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-pred-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-pred-eda-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-pred-eda-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-pred-eda-3.png" class="lightbox" data-gallery="fig-ncaa-pred-eda" title="Figure&nbsp;9.2&nbsp;(c): type"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-pred-eda-3.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-pred-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-pred-eda-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) <code>type</code>
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-pred-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Distributions of predictor variables
</figcaption></figure>
</div>
<div class="cell">
<div id="tbl-ncaa-univariate-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-univariate-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Summary statistics for <code>enrollment_th</code> and <code>expenditure_m</code>
</figcaption><div aria-describedby="tbl-ncaa-univariate-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Q1</th>
<th style="text-align: right;">Median (Q2)</th>
<th style="text-align: right;">Q3</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Missing</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">expenditure_m</td>
<td style="text-align: right;">8.3</td>
<td style="text-align: right;">7.0</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">10.8</td>
<td style="text-align: right;">38.1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">enrollment_th</td>
<td style="text-align: right;">11.9</td>
<td style="text-align: right;">9.9</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">7.9</td>
<td style="text-align: right;">17.8</td>
<td style="text-align: right;">59.6</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The response variable <code>expenditure_m</code> in <a href="#fig-ncaa-response-eda" class="quarto-xref">Figure&nbsp;<span>9.1</span></a> is unimodal and skewed right. The median expenditure on basketball programs is 5 million dollars, but there are a few colleges that spent over 30 million dollars on basketball programs in 2023 - 2024. Similarly, <code>enrollment_th</code> in <a href="#fig-ncaa-pred-eda-1" class="quarto-xref">Figure&nbsp;<span>9.2 (a)</span></a> is unimodal and skewed right, with a median enrollment of about 7900 students. There are some very large colleges in the data set with enrollments of over 40,000 students.</p>
<p>Almost half of the 355 colleges in the data are located in the South region (<a href="#fig-ncaa-pred-eda-2" class="quarto-xref">Figure&nbsp;<span>9.2 (b)</span></a>), and about two-thirds of the colleges in the data set are public institutions (<a href="#fig-ncaa-pred-eda-3" class="quarto-xref">Figure&nbsp;<span>9.2 (c)</span></a>).</p>
<div id="fig-ncaa-bivariate-eda" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-bivariate-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-bivariate-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-bivariate-eda-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-bivariate-eda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-bivariate-eda-1.png" class="lightbox" data-gallery="fig-ncaa-bivariate-eda" title="Figure&nbsp;9.3&nbsp;(a): expenditure_m versus enrollment_th"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-bivariate-eda-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-bivariate-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-bivariate-eda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <code>expenditure_m</code> versus <code>enrollment_th</code>
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-bivariate-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-bivariate-eda-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-bivariate-eda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-bivariate-eda-2.png" class="lightbox" data-gallery="fig-ncaa-bivariate-eda" title="Figure&nbsp;9.3&nbsp;(b): expenditure_m versus region"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-bivariate-eda-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-bivariate-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-bivariate-eda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <code>expenditure_m</code> versus <code>region</code>
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-bivariate-eda" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-bivariate-eda-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-bivariate-eda-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-bivariate-eda-3.png" class="lightbox" data-gallery="fig-ncaa-bivariate-eda" title="Figure&nbsp;9.3&nbsp;(c): expenditure_m versus type"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-bivariate-eda-3.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-bivariate-eda"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-bivariate-eda-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) <code>expenditure_m</code> versus <code>type</code>
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-bivariate-eda-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Bivariate exploratory data analysis
</figcaption></figure>
</div>
<p>From the bivariate exploratory data analysis in <a href="#fig-ncaa-bivariate-eda-1" class="quarto-xref">Figure&nbsp;<span>9.3 (a)</span></a>, there appears to be a strong positive relationship between the enrollment and expenditure. This aligns with what we might expect; colleges with more students are likely to spend more on basketball programs. We note that this trend does seem to level off for colleges with very high enrollment, because their expenditure is lower than what we would expect if expenditure increased as a constant rate for values of enrollment (called <em>monotonically increasing</em>).</p>
<p>The plot also shows two other interesting features of the relationship. The first is that the variability in the expenditure increases as enrollment increases. Thus, there is more variability in how much colleges with larger enrollments spend on basketball programs compared to colleges with small enrollments. We will keep this issue of the changing variability in mind as we fit a model and evaluate the model conditions. The second observation is the appearance of a “V” shape in the trend, indicating two different trajectories. This could be an indication of a potential interaction, so let’s look at multivariate plots to explore a potential interaction between enrollment and type and one between enrollment and region.</p>
<div id="fig-ncaa-eda-multivariate" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-eda-multivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-eda-multivariate" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-eda-multivariate-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-eda-multivariate-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-eda-multivariate-1.png" class="lightbox" data-gallery="fig-ncaa-eda-multivariate" title="Figure&nbsp;9.4&nbsp;(a): expenditure_m versus enrollment_th by type"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-eda-multivariate-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-eda-multivariate"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-eda-multivariate-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) <code>expenditure_m</code> versus <code>enrollment_th</code> by <code>type</code>
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-eda-multivariate" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-eda-multivariate-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-eda-multivariate-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-eda-multivariate-2.png" class="lightbox" data-gallery="fig-ncaa-eda-multivariate" title="Figure&nbsp;9.4&nbsp;(b): expenditure_m versus enrollment_th by region"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-eda-multivariate-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-eda-multivariate"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-eda-multivariate-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) <code>expenditure_m</code> versus <code>enrollment_th</code> by <code>region</code>
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-eda-multivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.4: Exploration of potential interaction terms
</figcaption></figure>
</div>
<div class="yourturn">
<p>Based on the plots in <a href="#fig-ncaa-eda-multivariate" class="quarto-xref">Figure&nbsp;<span>9.4</span></a>, do there appear to be any potential interaction effects? Explain.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
</section><section id="initial-model" class="level3" data-number="9.1.2"><h3 data-number="9.1.2" class="anchored" data-anchor-id="initial-model">
<span class="header-section-number">9.1.2</span> Initial model</h3>
<p>We include the interaction between <code>type</code> and <code>enrollment_th</code> in the first modeling attempt, shown in <a href="#tbl-ncaa-model-orig" class="quarto-xref">Table&nbsp;<span>9.2</span></a>. The plot of the residuals versus fitted values along with the distribution of the residuals are in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>.</p>
<div class="cell">
<div id="tbl-ncaa-model-orig" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-model-orig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.2: Model for NCAA basketball expenditure with 95% confidence intervals
</figcaption><div aria-describedby="tbl-ncaa-model-orig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 12%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">7.247</td>
<td style="text-align: right;">1.021</td>
<td style="text-align: right;">7.100</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">5.239</td>
<td style="text-align: right;">9.254</td>
</tr>
<tr class="even">
<td style="text-align: left;">enrollment_th</td>
<td style="text-align: right;">0.557</td>
<td style="text-align: right;">0.102</td>
<td style="text-align: right;">5.476</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.357</td>
<td style="text-align: right;">0.756</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionNortheast</td>
<td style="text-align: right;">-3.044</td>
<td style="text-align: right;">0.985</td>
<td style="text-align: right;">-3.090</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">-4.981</td>
<td style="text-align: right;">-1.106</td>
</tr>
<tr class="even">
<td style="text-align: left;">regionSouth</td>
<td style="text-align: right;">-1.146</td>
<td style="text-align: right;">0.786</td>
<td style="text-align: right;">-1.458</td>
<td style="text-align: right;">0.146</td>
<td style="text-align: right;">-2.692</td>
<td style="text-align: right;">0.400</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionWest</td>
<td style="text-align: right;">-3.009</td>
<td style="text-align: right;">0.973</td>
<td style="text-align: right;">-3.093</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">-4.922</td>
<td style="text-align: right;">-1.096</td>
</tr>
<tr class="even">
<td style="text-align: left;">typePublic</td>
<td style="text-align: right;">-5.049</td>
<td style="text-align: right;">1.042</td>
<td style="text-align: right;">-4.845</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-7.099</td>
<td style="text-align: right;">-3.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">enrollment_th:typePublic</td>
<td style="text-align: right;">-0.060</td>
<td style="text-align: right;">0.107</td>
<td style="text-align: right;">-0.566</td>
<td style="text-align: right;">0.572</td>
<td style="text-align: right;">-0.271</td>
<td style="text-align: right;">0.150</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div id="fig-ncaa-orig-resid" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-orig-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-orig-resid" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-orig-resid-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-orig-resid-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-orig-resid-1.png" class="lightbox" data-gallery="fig-ncaa-orig-resid" title="Figure&nbsp;9.5&nbsp;(a): Residuals versus predicted"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-orig-resid-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-orig-resid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-orig-resid-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Residuals versus predicted
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-orig-resid" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-orig-resid-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-orig-resid-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-orig-resid-2.png" class="lightbox" data-gallery="fig-ncaa-orig-resid" title="Figure&nbsp;9.5&nbsp;(b): Distribution of residuals"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-orig-resid-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-orig-resid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-orig-resid-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Distribution of residuals
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-orig-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.5: Residual plots from original NCAA basketball expenditure model
</figcaption></figure>
</div>
<p>There is a “fan” shape in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>, so the equal variance condition is not met. Because the equal variance condition is not met, the results of theory-based inference output in <a href="#tbl-ncaa-model-orig" class="quarto-xref">Table&nbsp;<span>9.2</span></a> cannot reliably be used to draw conclusions about the relationships between the response and predictor variables. For example, the inferential results suggest the interaction between enrollment and institution type is not useful in this model, despite what we observed in <a href="#fig-ncaa-eda-multivariate" class="quarto-xref">Figure&nbsp;<span>9.4</span></a>. Before making a final conclusion about the interaction term ad any other term in the model, let’s first address the issue with the equal variance condition.</p>
<p>Here is a summary of some of the points of interest we’ve observed thus far in the exploratory data analysis and initial modeling attempt.</p>
<ol type="1">
<li><p>The relationship between <code>enrollment_th</code> and <code>expenditure_m</code> seems to “level off” for high-enrollment colleges, thus the relationship may be non-linear.</p></li>
<li><p>There is a fan shape in the plot of the residuals versus predicted values, indicating a violation of the equal variance condition.</p></li>
<li><p>The exploratory data analysis suggests there is a potential interaction between <code>enrollment_th</code> and <code>type</code>.</p></li>
</ol>
<p>Note that items (1) and (2) are about the model fit and item (3) is about a conclusion drawn from the model. Thus we need to address items (1) and (2) before digging further into item (3). To do so, we will examine three additional models that differ based on transformations on the response variable <code>expenditure_m</code> and/or <code>enrollment_th</code>, the quantitative predictor variable. Transformations only apply to quantitative variables, so <code>type</code> and <code>region</code> will remain unchanged in the subsequent models throughout the chapter.</p>
<p>Throughout the chapter, we will interpret the coefficients and evaluate the model conditions for each of the new candidate models. We’ll then use model performance statistics along with the conditions to select the model that best fits the data. The candidate models are the following:</p>
<ol type="A">
<li>Original model with no transformations (shown in <a href="#tbl-ncaa-model-orig" class="quarto-xref">Table&nbsp;<span>9.2</span></a>)</li>
<li>Log-transformation on the response variable, <span class="math inline">\(\log(y)\)</span>
</li>
<li>Log-transformation on the quantitative predictor variable, <span class="math inline">\(\log(x)\)</span>
</li>
<li>Log-transformation on the response and quantitative predictor variables, <span class="math inline">\(\log(x)\)</span> and <span class="math inline">\(\log(y)\)</span>
</li>
</ol>
<div id="fig-ncaa-model-compare" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-model-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-model-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-model-compare-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-model-compare-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-1.png" class="lightbox" data-gallery="fig-ncaa-model-compare" title="Figure&nbsp;9.6&nbsp;(a): Original"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-model-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-model-compare-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-model-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-model-compare-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-model-compare-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-2.png" class="lightbox" data-gallery="fig-ncaa-model-compare" title="Figure&nbsp;9.6&nbsp;(b): log(y)"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-model-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-model-compare-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) log(y)
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-model-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-model-compare-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-model-compare-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-3.png" class="lightbox" data-gallery="fig-ncaa-model-compare" title="Figure&nbsp;9.6&nbsp;(c): log(x)"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-3.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-model-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-model-compare-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) log(x)
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-model-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-model-compare-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-model-compare-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-4.png" class="lightbox" data-gallery="fig-ncaa-model-compare" title="Figure&nbsp;9.6&nbsp;(d): log(x) and log(y)"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-model-compare-4.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-model-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-model-compare-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) log(x) and log(y)
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-model-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.6: Relationship between <code>expenditure_m</code> and <code>enrollment_th</code> for four candidate models
</figcaption></figure>
</div>
<div class="yourturn">
<p>Which relationship visualized in <a href="#fig-ncaa-model-compare" class="quarto-xref">Figure&nbsp;<span>9.6</span></a> would be best summarized by a linear regression model?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
<p>The plots in <a href="#fig-ncaa-model-compare" class="quarto-xref">Figure&nbsp;<span>9.6</span></a> can help provide intuition on what to expect as we do the analysis. In this chapter, we will look at the transformations presented in Plots B - D in the order they are plotted. In practice, however, you can use insights from the exploratory data analysis to start with the model that appears to be the best fit for the data. We do not draw definitive conclusions from the exploratory data analysis, so we will use inference, model conditions, and model fit statistics to select the best fit model. For now, we will just discuss these transformations in terms of a main effects model. In <a href="#sec-transform-choose-model" class="quarto-xref"><span>Section 9.5</span></a>, we add the interaction term to our selected model.</p>
</section></section><section id="sec-transform-logy" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="sec-transform-logy">
<span class="header-section-number">9.2</span> Transformation on the response variable</h2>
<!--# need to make it clear somewhere that this is the natural log, not something like log10-->
<p>The plot of residuals versus predicted variables in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a> shows a clear violation in the equal variance condition based on the fan-shaped pattern of the residuals when moving from left to right. Recall from <a href="06-slr-conditions.html#sec-conditions-not-satisfied" class="quarto-xref"><span>Section 6.3</span></a> that it is necessary to satisfy the equal variance condition when doing theory-based inference (the inference results produced by output), because it relies on a single estimate of <span class="math inline">\(\hat{\sigma}_{\epsilon}\)</span>, the regression standard error (variability about the regression line). We can easily see in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a> that a single value would not be representative of the vertical spread of the residuals for all predicted values. Thus, the inferential results in <a href="#tbl-ncaa-model-orig" class="quarto-xref">Table&nbsp;<span>9.2</span></a> should be interpreted with caution.</p>
<p>One solution to this is to use the simulation-based inference methods introduced in <a href="08-mlr-inference.html#sec-mlr-sim-inf" class="quarto-xref"><span>Section 8.3</span></a>, because the sampling distribution and null distribution for an estimated coefficient <span class="math inline">\(\hat{\beta}_j\)</span> are constructed relying only on the data, rather than any underlying assumptions about the distribution of <span class="math inline">\(\hat{\beta}_j\)</span>. Another approach is to use a transformation on the response variable to reduce the impacts of the different vertical spreads in the response variable. Such transformations are called <strong>variance-stabilizing transformations</strong>.</p>
<!--# do i need a callout terminology box highlighting the definition of variance-stabilizing transformaiton?-->
<!--# i really need to figure out syntax..upper or lower case y and x-->
<p>Some commonly used variance-stabilizing transformations are the square-root transformation, <span class="math inline">\(\sqrt{y}\)</span> , and the reciprocal transformation, <span class="math inline">\(1/y\)</span> . In fact, the square root and reciprocal transformations are just two examples from the class of transformations called the <strong>Box-Cox transformations</strong> <span class="citation" data-cites="box1964analysis">(<a href="references.html#ref-box1964analysis" role="doc-biblioref">Box and Cox 1964</a>)</span>. These transformations are designed to handle a non-normal response variable of any shape. While Box-Cox transformations, such as <span class="math inline">\(\sqrt{y}\)</span> and <span class="math inline">\(1/y\)</span>, can be the optional choice for stabilizing variance and making the distribution of the response variable more normal (recall the normality condition), it is often difficult to interpret the coefficients for models with such transformed response variables in a way that an be easily understood by readers. Therefore, we will not focus on Box-Cox transformations in this text, because one of our primary objectives is to produce models that are easily interpretable.</p>
<!--# read more about these and make sure this all aligns-->
<!--# add callout box for Box-Cox transformations. History, what they are, and resources to learn more-->
<p>Let’s consider another transformation for the response variable that can help address the violations in the equal variance condition while also being easily interpreted by the reader. We can apply a natural log transformation on the response variable, <span class="math inline">\(\log(y)\)</span> (also written as <span class="math inline">\(\ln(y)\)</span>), such that <span class="math inline">\(\log(y)\)</span> has the linear relationship with the predictor variables. <a href="#eq-log-y" class="quarto-xref">Equation&nbsp;<span>9.1</span></a> shows the statistical model when applying such transformation to the response variable.</p>
<p><span id="eq-log-y"><span class="math display">\[
\log(y_i) = \beta_0 + \beta_1x_{i1} + \beta_2x_{i2}+ \dots + \beta_px_{ip} + \epsilon_i \hspace{8mm} \epsilon_i \sim N(0, \sigma^2_{\epsilon})
\tag{9.1}\]</span></span></p>
<div class="math_rules">
<p><strong>log = ln</strong></p>
<p>In statistics, the term “log” refers to the natural log (typically denoted <span class="math inline">\(\ln\)</span> in mathematics).</p>
</div>
<p>As shown in <a href="#eq-log-y" class="quarto-xref">Equation&nbsp;<span>9.1</span></a>, the log transformation is applied to the individual values of <span class="math inline">\(Y\)</span>, and the transformed values are used in the model. Therefore, when we use a log (or any) transformation on the response variable, we assume the assumptions from <a href="05-slr-inference.html#sec-slr-foundation" class="quarto-xref"><span>Section 5.3</span></a> apply to the relationship between the predictors and the transformed values of <span class="math inline">\(Y\)</span>. Using <a href="#eq-log-y" class="quarto-xref">Equation&nbsp;<span>9.1</span></a>, this means we make assumptions about the relationship between the predictors and <span class="math inline">\(\log(y_i)\)</span>. The full analysis, including evaluating conditions and diagnostics, conducting inference, and computing predictions are done in terms of <span class="math inline">\(\log(y)\)</span>. Interpretations, however, are in terms of the original variable <span class="math inline">\(y\)</span>. Although we can write interpretations in terms of <span class="math inline">\(\log(y)\)</span> (we’ll see an example of this shortly), it is not as intuitive for readers to understand interpretations on a log-scale as on the natural scale.</p>
<p>Let’s begin by looking at the distribution of <code>log(expenditure_m)</code>, its relationship with <code>enrollment_th</code>, and how these compare to the exploratory data analysis in <a href="#sec-transform-eda" class="quarto-xref"><span>Section 9.1</span></a>.</p>
<div id="fig-expend-compare" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-expend-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-expend-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-expend-compare-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-expend-compare-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-expend-compare-1.png" class="lightbox" data-gallery="fig-expend-compare" title="Figure&nbsp;9.7&nbsp;(a): Distribution of expenditure_m"><img src="09-mlr-transformations_files/figure-html/fig-expend-compare-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-expend-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-expend-compare-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Distribution of <code>expenditure_m</code>
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-expend-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-expend-compare-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-expend-compare-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-expend-compare-2.png" class="lightbox" data-gallery="fig-expend-compare" title="Figure&nbsp;9.7&nbsp;(b): Distribution of log-transformed expenditure_m"><img src="09-mlr-transformations_files/figure-html/fig-expend-compare-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-expend-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-expend-compare-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Distribution of log-transformed <code>expenditure_m</code>
</figcaption></figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-expend-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-expend-compare-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-expend-compare-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-expend-compare-3.png" class="lightbox" data-gallery="fig-expend-compare" title="Figure&nbsp;9.7&nbsp;(c): expenditure_m versus enrollmenth_th"><img src="09-mlr-transformations_files/figure-html/fig-expend-compare-3.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-expend-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-expend-compare-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) <code>expenditure_m</code> versus <code>enrollmenth_th</code>
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-expend-compare" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-expend-compare-4" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-expend-compare-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-expend-compare-4.png" class="lightbox" data-gallery="fig-expend-compare" title="Figure&nbsp;9.7&nbsp;(d): Log-transformed expenditure_m versus enrollment_th"><img src="09-mlr-transformations_files/figure-html/fig-expend-compare-4.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-expend-compare"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-expend-compare-4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) Log-transformed <code>expenditure_m</code> versus <code>enrollment_th</code>
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-expend-compare-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.7: Univariate and bivariate EDA for original and log-transformed <code>expenditure_m</code>
</figcaption></figure>
</div>
<p>Now we fit the main effects model using <code>log(expenditure_m)</code>, the log-transformed expenditure, as the response variable. The output for the new is in <a href="#tbl-ncaa-model-logy" class="quarto-xref">Table&nbsp;<span>9.3</span></a> and the equation is in <a href="#eq-ncaa-model-logy" class="quarto-xref">Equation&nbsp;<span>9.2</span></a>.</p>
<div class="cell">
<div id="tbl-ncaa-model-logy" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-model-logy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.3: Model with log-transformed expenditure as the response variable
</figcaption><div aria-describedby="tbl-ncaa-model-logy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.783</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">21.21</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.617</td>
<td style="text-align: right;">1.948</td>
</tr>
<tr class="even">
<td style="text-align: left;">enrollment_th</td>
<td style="text-align: right;">0.056</td>
<td style="text-align: right;">0.003</td>
<td style="text-align: right;">17.14</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.050</td>
<td style="text-align: right;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionNortheast</td>
<td style="text-align: right;">-0.311</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">-3.19</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">-0.503</td>
<td style="text-align: right;">-0.119</td>
</tr>
<tr class="even">
<td style="text-align: left;">regionSouth</td>
<td style="text-align: right;">-0.176</td>
<td style="text-align: right;">0.078</td>
<td style="text-align: right;">-2.26</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">-0.329</td>
<td style="text-align: right;">-0.023</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionWest</td>
<td style="text-align: right;">-0.218</td>
<td style="text-align: right;">0.096</td>
<td style="text-align: right;">-2.26</td>
<td style="text-align: right;">0.024</td>
<td style="text-align: right;">-0.408</td>
<td style="text-align: right;">-0.028</td>
</tr>
<tr class="even">
<td style="text-align: left;">typePublic</td>
<td style="text-align: right;">-0.672</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">-9.11</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.817</td>
<td style="text-align: right;">-0.527</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><span id="eq-ncaa-model-logy"><span class="math display">\[
\begin{aligned}
\widehat{\log(\text{expenditure\_m})} = &amp; 1.783 + 0.056 \times \text{enrollment\_th}\\
&amp;- 0.311 \times \text{Northeast} - 0.176 \times \text{South} \\
&amp; - 0.218 \times \text{West} - 0.672 \times \text{Public}
\end{aligned}
\tag{9.2}\]</span></span></p>
<p>Before using the model, we analyze the residuals versus predicted values to evaluate whether the concerns with equal variance have been addressed by the transformation. <a href="#fig-ncaa-logy-resid" class="quarto-xref">Figure&nbsp;<span>9.8</span></a> shows the original plot of the residuals versus predicted values and the plot for the model using the log-transformed response variable.</p>
<div id="fig-ncaa-logy-resid" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-logy-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-logy-resid" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-logy-resid-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-logy-resid-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-logy-resid-1.png" class="lightbox" data-gallery="fig-ncaa-logy-resid" title="Figure&nbsp;9.8&nbsp;(a): Original model"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-logy-resid-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-logy-resid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-logy-resid-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original model
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-ncaa-logy-resid" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-ncaa-logy-resid-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-ncaa-logy-resid-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-logy-resid-2.png" class="lightbox" data-gallery="fig-ncaa-logy-resid" title="Figure&nbsp;9.8&nbsp;(b): Model with log-transformed expenditure_m"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-logy-resid-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-ncaa-logy-resid"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-ncaa-logy-resid-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Model with log-transformed <code>expenditure_m</code>
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-logy-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.8: Residuals versus predicted values for original model and model with log-transformed <code>expenditure_m</code>
</figcaption></figure>
</div>
<p>Comparing the plots in <a href="#fig-ncaa-logy-resid" class="quarto-xref">Figure&nbsp;<span>9.8</span></a>, the first observation is that the <span class="math inline">\(y\)</span>-axis differs on the plots. This is the because the residuals are on the same scale and use the same units as the response variable. The residuals in <a href="#fig-ncaa-logy-resid-1" class="quarto-xref">Figure&nbsp;<span>9.8 (a)</span></a> are in terms of the original variable <code>expenditure_m</code>, and the residuals in <a href="#fig-ncaa-logy-resid-2" class="quarto-xref">Figure&nbsp;<span>9.8 (b)</span></a> are in terms of <code>log(expenditure_m)</code>. The same is true for the predicted values on the <span class="math inline">\(x\)</span>-axis. The second observation is that the vertical spread of the residuals is much more equal <a href="#fig-ncaa-logy-resid-2" class="quarto-xref">Figure&nbsp;<span>9.8 (b)</span></a> with the log-transformed response variable. Given this, it appears applying a log transformation on the response variable has addressed some of the problems with the equal variance condition.</p>
<p>We can consider other transformations to improve the model fit even more; we’ll discuss those as the chapter continues. For now, let’s interpret the coefficients for the model in <a href="#tbl-ncaa-model-logy" class="quarto-xref">Table&nbsp;<span>9.3</span></a>. The approach for interpreting the model coefficients in terms of the log-transformed response variable is the same as the one introduced in <a href="#sec-transform-logy" class="quarto-xref"><span>Section 9.2</span></a> for other multiple linear regression models. Below are the interpretations for <code>enrollment_th</code> and <code>regionNortheast</code> in terms of <code>log(expenditure)</code>.</p>
<blockquote class="blockquote">
<p><em>For each additional 1000 students at an NCAA Division I college, the total log(expenditure) on basketball programs is expected to increase by 0.056 log(millions of dollars), on average, holding region and type constant.</em></p>
<p><em>The total log(expenditure) on basketball programs for NCAA Division I colleges is expected to be 0.311 log(millions of dollars) less, on average, for colleges in the Northeast region compared to those in the North Central region, holding enrollment and type constant.</em></p>
</blockquote>
<p>Though these interpretations are technically correct, it is difficult to fully comprehend what a change in log(millions of dollars) to the log(expenditure) really means. Therefore, we need to get back to the original variable (<code>expenditure_m)</code> and back to the original units (millions of dollars) to write an interpretation that is more intuitive.</p>
<div class="math_rules">
<ul>
<li><p><span class="math inline">\(e^{\log(a)} = a\)</span></p></li>
<li><p><span class="math inline">\(e^{a+b} = e^ae^b\)</span></p></li>
</ul>
</div>
<p>Given <a href="#eq-log-y" class="quarto-xref">Equation&nbsp;<span>9.1</span></a> with a log-transformed response variable, the predicted values in terms of the original response variable is</p>
<p><span id="eq-log-y-orig"><span class="math display">\[
\begin{aligned}
\hat{y}_i &amp;= e^{\hat{\beta}_0 + \hat{\beta}_1x_{i1} + \hat{\beta}_2x_{i2}+ \dots + \hat{\beta}_px_{ip}} \\[10pt]
&amp; = e^{\hat{\beta}_0}e^{\hat{\beta}_1x_{i1}}e^{\hat{\beta}_2x_{i2}} \dots e^{\hat{\beta}_px_{ip}}
\end{aligned}
\tag{9.3}\]</span></span></p>
<p>From <a href="#eq-log-y-orig" class="quarto-xref">Equation&nbsp;<span>9.3</span></a>, the interpretations in terms of the original response variable are about a multiplicative change in the response when the predictor variable changes. Specifically, when <span class="math inline">\(X_j\)</span> increases by one unit, <span class="math inline">\(Y\)</span> is expected to multiply by a factor of <span class="math inline">\(e^{\hat{\beta}_j}\)</span>. The mathematical details for <a href="#eq-log-y-orig" class="quarto-xref">Equation&nbsp;<span>9.3</span></a> and the interpretations are in <a href="appendix-linear.html#sec-transform-y-math" class="quarto-xref"><span>Section A.9.1</span></a>.</p>
<p>Now let’s use <a href="#eq-log-y-orig" class="quarto-xref">Equation&nbsp;<span>9.3</span></a> to interpret the coefficients of <code>enrollment_th</code> and <code>regionNortheast</code> in terms of <code>expenditure_m</code>.</p>
<blockquote class="blockquote">
<p><em>For each additional 1000 students at an NCAA Division I college, the total log(expenditure) on basketball programs is expected to <strong>multiply by a factor</strong> of 1.058 (</em><span class="math inline">\(e^{0.056}\)</span><em>), holding region and type constant.</em></p>
<p><em>The total expenditure on basketball programs for NCAA Division I colleges in the Northeast region is expected to be 0.733 (</em><span class="math inline">\(e^{-0.311}\)</span><em>) <strong>times</strong> the expenditure at colleges in the North Central region, holding enrollment and type constant.</em></p>
</blockquote>
<div class="yourturn">
<p>Write the interpretation for <code>typePublic</code> in <a href="#tbl-ncaa-model-logy" class="quarto-xref">Table&nbsp;<span>9.3</span></a> in terms of the change in enrollment. <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</div>
<p>The intercept, the expected response when all predictors are equal to 0, is <span class="math inline">\(e^{\hat{\beta}_0}\)</span>. Thus, the interpretation of the intercept for <a href="#tbl-ncaa-model-logy" class="quarto-xref">Table&nbsp;<span>9.3</span></a> in terms of the original response variable is</p>
<blockquote class="blockquote">
<p><em>The total expenditure on basketball programs for private NCAA Division I colleges in the North Central region with no students enrolled is expected to be 5.948</em> <span class="math inline">\((e^{1.783})\)</span> million dollars.</p>
</blockquote>
<div class="yourturn">
<p>Is the interpretation of the intercept for the model in <a href="#tbl-ncaa-model-logy" class="quarto-xref">Table&nbsp;<span>9.3</span></a> meaningful? If not, what can we do to make the interpretation meaningful?<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</div>
</section><section id="sec-transform-logx" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="sec-transform-logx">
<span class="header-section-number">9.3</span> Transformation on predictor variable(s)</h2>
<p>Transformations on the response variable are often done to address violations in the equal variance condition, as shown in the previous section. In this section, we introduce transformations on one or more quantitative predictor variables that are used to model non-linear relationships with the response variable.</p>
<p>In the exploratory data analysis in <a href="#sec-ncaa-eda" class="quarto-xref"><span>Section 9.1.1</span></a>, we observed that the relationship between <code>expenditure_m</code> and <code>enrollment_th</code> flattened as <code>enrollment_th</code> increased. For Colleges with larger enrollments generally have a smaller increase in expenditures on basketball programs for each additional 1000 students compared to the increase in expenditures for colleges with smaller enrollments. We account for this decreasing effect by applying a log transformation on the predictor variable. Here we will transform a single predictor but we can apply a log transformation to multiple quantitative predictors in a model.</p>
<p>The general form of the linear regression model with a log-transformed predictor variable <span class="math inline">\(x_j\)</span> is shown in <a href="#eq-mlr-logx" class="quarto-xref">Equation&nbsp;<span>9.4</span></a> .</p>
<p><span id="eq-mlr-logx"><span class="math display">\[
y_i = \beta_0 + \beta_1x_{i1} + \dots + \beta_j\log(x_{ij}) + \dots + \beta_px_{ip} + \epsilon_i  \hspace{5mm} \epsilon_i \sim N(0, \sigma^2_{\epsilon})
\tag{9.4}\]</span></span></p>
<p><a href="#eq-ncaa-logx" class="quarto-xref">Equation&nbsp;<span>9.5</span></a> shows the form of the model for NCAA Division I basketball expenditure using log-transformed values of enrollment.</p>
<p><span id="eq-ncaa-logx"><span class="math display">\[
\begin{aligned}
\text{expenditure\_m}_i = \beta_0 &amp;+ \beta_1 \log(\text{enrollment\_th}_i) + \beta_2\text{Northeast}_i + \beta_3\text{South}_i \\
&amp;+ \beta_4\text{West}_i + \beta_5\text{Public}_i + \epsilon_i \hspace{5mm} \epsilon_i \sim N(0, \sigma^2_{\epsilon})
\end{aligned}
\tag{9.5}\]</span></span></p>
<p>At this point, we are using the original response variable, <code>expenditure_m</code>, so we can focus on understanding the log-transformed predictor variable. In the next section, we will look at the scenario in which both the response variable and one or more predictor variables is transformed. The output of the model with log-transformed enrollment is in <a href="#tbl-ncaa-model-logx" class="quarto-xref">Table&nbsp;<span>9.4</span></a>.</p>
<div class="cell">
<div id="tbl-ncaa-model-logx" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-model-logx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.4: Output of model with log-transformed <code>enrollment_th</code>
</figcaption><div aria-describedby="tbl-ncaa-model-logx-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.297</td>
<td style="text-align: right;">1.026</td>
<td style="text-align: right;">1.265</td>
<td style="text-align: right;">0.207</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(enrollment_th)</td>
<td style="text-align: right;">5.992</td>
<td style="text-align: right;">0.400</td>
<td style="text-align: right;">14.994</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionNortheast</td>
<td style="text-align: right;">-3.242</td>
<td style="text-align: right;">0.991</td>
<td style="text-align: right;">-3.271</td>
<td style="text-align: right;">0.001</td>
</tr>
<tr class="even">
<td style="text-align: left;">regionSouth</td>
<td style="text-align: right;">-0.662</td>
<td style="text-align: right;">0.793</td>
<td style="text-align: right;">-0.835</td>
<td style="text-align: right;">0.404</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionWest</td>
<td style="text-align: right;">-2.919</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">-2.985</td>
<td style="text-align: right;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">typePublic</td>
<td style="text-align: right;">-6.531</td>
<td style="text-align: right;">0.783</td>
<td style="text-align: right;">-8.337</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Let’s start by interpreting the intercept for this model. Because we have used the log-transformed value of enrollment in the model, the intercept represents the subgroup of NCAA Division 1 colleges such that <code>log(enrollment_th)</code> and all the other predictors are equal to 0. Based on the rules of logarithms, <code>log(enrollment_th)</code> is equal to 0 when <code>enrollment_th</code> is equal to 1, corresponding to an institution with 1000 students enrolled. The interpretation of the intercept for this model is the following:</p>
<blockquote class="blockquote">
<p><em>The expenditure on basketball programs for private NCAA Division 1 colleges in the North Central region with 1000 students enrolled (<code>log(enrollment_th) = 0</code>) is expected to be 1.297 million dollars.</em></p>
</blockquote>
<p>Now let’s look at the interpretation of the predictor variable <code>enrollment_th</code>. Using the coefficient interpretations introduced in <a href="07-mlr.html#sec-mlr-interpret-quantitative" class="quarto-xref"><span>Section 7.4.1</span></a>, the interpretation is the following:</p>
<blockquote class="blockquote">
<p><em>When the log-transformed enrollment increases by 1, the expenditure on basketball programs at NCAA Division 1 colleges is expected to increase by 5.992 million dollars, holding type and region constant.</em></p>
</blockquote>
<p>Though this interpretation is technically accurate, it is difficult to comprehend what an increase in the log-transformed enrollment actually means. Therefore, rather than interpreting the coefficient in terms of the log-transformed enrollment, we interpret enrollment in terms of its original units of 1000 students.</p>
<p>Because `enrollment_th` is on the logarithmic scale in the model, it is most straightforward <!--# diff word here--> to interpret the change in expenditure when enrollment is multiplied by a constant <span class="math inline">\(C\)</span>. In general terms, given a model of the form in <a href="#eq-mlr-logx" class="quarto-xref">Equation&nbsp;<span>9.4</span></a>, the interpretation of predictor <span class="math inline">\(X_j\)</span> is below. The mathematical details for this interpretation are in <a href="appendix-linear.html#sec-transform-x-math" class="quarto-xref"><span>Section A.9.2</span></a>. <!--# Maybe add more explanation about why you multiply a log-transformed variable rather than just increase by 1. Maybe show the counterfactual, if we just increase by 1--></p>
<blockquote class="blockquote">
<p><em>When</em> <span class="math inline">\(X_j\)</span> <em>is multiplied by a constant</em> <span class="math inline">\(C\)</span><em>,</em> <span class="math inline">\(Y\)</span> <em>is expected to change (increase or decrease) by</em> <span class="math inline">\(\beta_j \log(C)\)</span> <em>units, holding all else constant.</em></p>
</blockquote>
<div class="math_rules">
<p><span class="math inline">\(\log(ab) = \log(a) +  \log(b)\)</span></p>
<p>Applying this to <a href="#eq-mlr-logx" class="quarto-xref">Equation&nbsp;<span>9.4</span></a>,</p>
<p><span class="math inline">\(\beta_j\log(CX_j) = \beta_j[\log(C) + \log(X_j)] = \beta_j\log(C) + \beta_j \log(X_j)\)</span></p>
</div>
<p>Now let’s interpret the effect of <code>enrollment_th</code> in terms of the expected change in <code>expenditure_m</code> when <code>enrollment_th</code> doubles (<span class="math inline">\(C = 2\)</span>).</p>
<blockquote class="blockquote">
<p>When the enrollment doubles (is multiplied by 2), the expenditure on basketball programs at NCAA Division 1 institutions is expected to increase by 4.153 (5.992 <span class="math inline">\(\times\)</span> log(2)) million dollar, on average, holding type and region constant.</p>
</blockquote>
<p>When writing these interpretations, the constant <span class="math inline">\(C\)</span> can take any value between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span>. When choosing <span class="math inline">\(C\)</span>, however, we need to be mindful about potential extrapolation and writing interpretations for values far outside the range of the data. Use values of <span class="math inline">\(C\)</span> between 1 and 2 to reduce potential extrapolation. Values in this range provide straightforward interpretations about the expected change when there is some percentage increase in the predictor (for example, <span class="math inline">\(C = 1.1\)</span> equals a 10% increase in the value of the predictor). Note, however, that there is a risk of extrapolating for observations with values at or near the maximum value of the predictor. For example, there is a college in the data with enrollment around 59,000. We should be cautious when using the model to interpret the expected change when enrollment doubles for this institution. This would equal an enrollment of over 118,000 students, which is far outside the range of the data. We cannot safely assume the relationship between <code>enrollment_th</code> and <code>expenditure_m</code> observed in <a href="#tbl-ncaa-model-logx" class="quarto-xref">Table&nbsp;<span>9.4</span></a> is the same for colleges with such high enrollment (or that such colleges even exist!).</p>
<div class="yourturn">
<p>Write the interpretation of the expected change in expenditure on basketball programs when enrollment increases by 50% <span class="math inline">\((C = 1.5)\)</span>.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ncaa-logx-resid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-logx-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-logx-resid-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Figure&nbsp;9.9: Residuals vs.&nbsp;fitted values for plot with log-transformed enrollment_th"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-logx-resid-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-logx-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.9: Residuals vs.&nbsp;fitted values for plot with log-transformed <code>enrollment_th</code>
</figcaption></figure>
</div>
</div>
</div>
<p>The plot of the residuals versus fitted values for the model <a href="#tbl-ncaa-model-logx" class="quarto-xref">Table&nbsp;<span>9.4</span></a> is shown in <a href="#fig-ncaa-logx-resid" class="quarto-xref">Figure&nbsp;<span>9.9</span></a>. This plot has a fan shape similar to the one observed in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>. Therefore, even though the log transformation on <code>enrollment_th</code> accounted for its non-linear relationship with <code>expenditure_m</code>, it did not address the violation in the equal variance condition like the log transformation on the response variable in <a href="#sec-transform-logy" class="quarto-xref"><span>Section 9.2</span></a>. In the next section, we introduce a model that includes both a log-transformed response variable and log-transformed predictor.</p>
</section><section id="sec-transform-logx-logy" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="sec-transform-logx-logy">
<span class="header-section-number">9.4</span> Transformation on the response variable and predictor variable(s)</h2>
<p>Models with transformations on both the response variable and one or more quantitative predictor variables can both address violations in the equal variance condition and capture non-linear relationships. Given what we have observed in the exploratory data analysis in <a href="#sec-ncaa-eda" class="quarto-xref"><span>Section 9.1.1</span></a> and the residual plots in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>, <a href="#fig-ncaa-logy-resid" class="quarto-xref">Figure&nbsp;<span>9.8</span></a> , and <a href="#fig-ncaa-logx-resid" class="quarto-xref">Figure&nbsp;<span>9.9</span></a>, we will now fit a model using both <code>log(expenditure_m)</code> and <code>log(enrollment_th)</code>.</p>
<p><a href="#eq-mlr-logx-logy" class="quarto-xref">Equation&nbsp;<span>9.6</span></a> is the general form of the model with a log-transformed response variable and a log-transformed predictor variable <span class="math inline">\(x_j\)</span> is shown in</p>
<p><span id="eq-mlr-logx-logy"><span class="math display">\[
\log(y_i) = \beta_0 + \beta_1x_{i1} + \dots + \beta_j\log(x_{ij}) + \dots + \beta_px_{ip} + \epsilon_i  \hspace{5mm} \epsilon_i \sim N(0, \sigma^2_{\epsilon})
\tag{9.6}\]</span></span></p>
<p><a href="#eq-ncaa-logx-logy" class="quarto-xref">Equation&nbsp;<span>9.7</span></a> shows the form of the model for NCAA Division I basketball expenditure, and the output of the estimated model is in <a href="#tbl-ncaa-model-logx-logy" class="quarto-xref">Table&nbsp;<span>9.5</span></a>.</p>
<p><span id="eq-ncaa-logx-logy"><span class="math display">\[
\begin{aligned}
\log(\text{expenditure\_m}_i) = \beta_0 &amp;+ \beta_1 \log(\text{enrollment\_th}_i) + \beta_2\text{Northeast}_i + \beta_3\text{South}_i \\
&amp;+ \beta_4\text{West}_i + \beta_5\text{Public}_i + \epsilon_i \hspace{5mm} \epsilon_i \sim N(0, \sigma^2_{\epsilon})
\end{aligned}
\tag{9.7}\]</span></span></p>
<div class="cell">
<div id="tbl-ncaa-model-logx-logy" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-model-logx-logy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.5: Output of model with log-transformed expenditure and log-transformed enrollment
</figcaption><div aria-describedby="tbl-ncaa-model-logx-logy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.025</td>
<td style="text-align: right;">0.097</td>
<td style="text-align: right;">10.58</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(enrollment_th)</td>
<td style="text-align: right;">0.707</td>
<td style="text-align: right;">0.038</td>
<td style="text-align: right;">18.75</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionNortheast</td>
<td style="text-align: right;">-0.337</td>
<td style="text-align: right;">0.094</td>
<td style="text-align: right;">-3.60</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">regionSouth</td>
<td style="text-align: right;">-0.115</td>
<td style="text-align: right;">0.075</td>
<td style="text-align: right;">-1.53</td>
<td style="text-align: right;">0.126</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionWest</td>
<td style="text-align: right;">-0.221</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">-2.39</td>
<td style="text-align: right;">0.017</td>
</tr>
<tr class="even">
<td style="text-align: left;">typePublic</td>
<td style="text-align: right;">-0.830</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">-11.22</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>To interpret the model in <a href="#tbl-ncaa-model-logx-logy" class="quarto-xref">Table&nbsp;<span>9.5</span></a> that has both a log-transformed response and predictor variable, we will combine the approach to interpretations from <a href="#sec-transform-logy" class="quarto-xref"><span>Section 9.2</span></a> and <a href="#sec-transform-logx" class="quarto-xref"><span>Section 9.3</span></a>.</p>
<p>The intercept is the expected value of <code>log(y)</code> when all the predictors are equal to 0. Because there is a log-transformed predictor <span class="math inline">\(x_j\)</span> in the model in <a href="#eq-mlr-logx-logy" class="quarto-xref">Equation&nbsp;<span>9.6</span></a>, this will be when <span class="math inline">\(\log(x_j)\)</span> is equal to 0, meaning <span class="math inline">\(x_j\)</span> is equal to 1. In terms of the model on NCAA Division I basketball expenditures shown in <a href="#tbl-ncaa-model-logx-logy" class="quarto-xref">Table&nbsp;<span>9.5</span></a>, the intercept 1.025 is interpreted as follows:</p>
<blockquote class="blockquote">
<p><em>The expected log-transformed expenditure on basketball programs at private NCAA Division I colleges in the North Central region with 1000 students enrolled is 1.025.</em></p>
</blockquote>
<p>For readability, we won’t present results in terms of log-transformed expenditure, so we get back to the original response variable <code>expenditure_m</code>.</p>
<blockquote class="blockquote">
<p><em>The expected expenditure on basketball programs at private NCAA Division I colleges in the North Central region with 1000 students enrolled is 2.787 (exp(1.025)) million dollars.</em></p>
</blockquote>
<p>The interpretation for <span class="math inline">\(\beta_j\)</span>, the coefficient for <span class="math inline">\(\log(X_j)\)</span> in <a href="#eq-mlr-logx-logy" class="quarto-xref">Equation&nbsp;<span>9.6</span></a> is a bit more involved, as it incorporates the multiplicative change in both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. We’ll start by writing the interpretation in terms of <span class="math inline">\(\log(Y)\)</span>.</p>
<blockquote class="blockquote">
<p><em>When</em> <span class="math inline">\(X_j\)</span> <em>multiplies by a factor of</em> <span class="math inline">\(C\)</span><em>,</em> <span class="math inline">\(\log(Y)\)</span> <em>is expected to change (increase or decrease) by</em> <span class="math inline">\(\beta_j \log(C)\)</span> <em>, on average, holding all else constant.</em></p>
</blockquote>
<div class="math_rules">
<p><span class="math inline">\(e^{a\log(b)} = b^a\)</span></p>
</div>
<p>Note that this interpretation is very similar to the interpretation from <a href="#sec-transform-logx" class="quarto-xref"><span>Section 9.3</span></a>, when there is a log-transformed predictor variable. The full mathematical details to get back to the original response variable are in <a href="appendix-linear.html#sec-transform-x-y-math" class="quarto-xref"><span>Section A.9.3</span></a> .The final interpretation in terms of the original response variable when <span class="math inline">\(X_j\)</span> is multiplied by <span class="math inline">\(C\)</span> is</p>
<blockquote class="blockquote">
<p><em>When</em> <span class="math inline">\(X_j\)</span> <em>multiplies by a factor of</em> <span class="math inline">\(C\)</span><em>,</em> <span class="math inline">\(Y\)</span> <em>is expected multiply by a factor of</em> <span class="math inline">\(C^{\beta_j}\)</span> <em>, holding all else constant.</em></p>
</blockquote>
<p>Now let’s use this to interpret <code>enrollment_th</code> for the model in <a href="#tbl-ncaa-model-logx-logy" class="quarto-xref">Table&nbsp;<span>9.5</span></a>. Below is the interpretation in terms of a 20% increase in enrollment, <span class="math inline">\(C = 1.2\)</span>.</p>
<blockquote class="blockquote">
<p><em>When enrollment at NCAA Division I colleges increases by 20% (multiples by 1.2), the expenditure on basketball programs is expected to multiply by a factor of 1.138 (</em> <span class="math inline">\(1.2^{0.707}\)</span><em>), holding type and region constant.</em></p>
</blockquote>
<div class="yourturn">
<p>Write the interpretation for <code>typePublic</code> in <a href="#tbl-ncaa-model-logx-logy" class="quarto-xref">Table&nbsp;<span>9.5</span></a> in the context of the data. Write the interpretation in terms of the original variable <code>expenditure_m</code>. <a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
</div>
<p>The plot of residuals versus predicted for the model in <a href="#tbl-ncaa-model-logx-logy" class="quarto-xref">Table&nbsp;<span>9.5</span></a> is shown in <a href="#fig-ncaa-logx-logy-resid" class="quarto-xref">Figure&nbsp;<span>9.10</span></a>. This plot shows improvement in the equal variance condition compared to the original residuals plot in <a href="#fig-ncaa-orig-resid" class="quarto-xref">Figure&nbsp;<span>9.5</span></a>, given the vertical spread of the residuals is more equal around the majority of the data. There is less variability in the residuals for institutions with low predicted expenditure, but there are few institutions with predicted <code>log(expenditure)</code> less than 1.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ncaa-logx-logy-resid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-logx-logy-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-logx-logy-resid-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="Figure&nbsp;9.10: Residuals vs.&nbsp;fitted values for plot with log-transformed enrollment and expenditure"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-logx-logy-resid-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-logx-logy-resid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.10: Residuals vs.&nbsp;fitted values for plot with log-transformed enrollment and expenditure
</figcaption></figure>
</div>
</div>
</div>
</section><section id="sec-transform-choose-model" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="sec-transform-choose-model">
<span class="header-section-number">9.5</span> Choosing a model</h2>
<p>So far we have looked at four potential models using <code>enrollment_th</code>, <code>type</code> and <code>region</code> to understand variability in <code>expenditure_m</code>. The next step is to select one of these models to use for prediction and inference based on the original analysis objectives. In addition to checking the residual plots and model conditions, we use performance statistics, such as <span class="math inline">\(R^2\)</span>, to help select the model that best fits the data. We discuss model evaluation and selection in-depth in <a href="10-model-eval.html" class="quarto-xref"><span>Chapter 10</span></a>.</p>
<div class="cell">
<div id="tbl-ncaa-compare-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-compare-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.6: R-Squared values for models presented in this chapter
</figcaption><div aria-describedby="tbl-ncaa-compare-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead><tr class="header">
<th style="text-align: right;">Original</th>
<th style="text-align: right;">log(y)</th>
<th style="text-align: right;">log(x)</th>
<th style="text-align: right;">log(x) &amp; log(y)</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: right;">0.409</td>
<td style="text-align: right;">0.473</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">0.516</td>
</tr></tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-ncaa-compare-models" class="quarto-xref">Table&nbsp;<span>9.6</span></a> shows the <span class="math inline">\(R^2\)</span> values for the four candidate models. Based on the <span class="math inline">\(R^2\)</span> values and the plots of the residuals versus predicted values, the model that includes both <code>log(expenditure_m)</code> and <code>log(enrollmet_th)</code> is the one that best fits the data.</p>
<section id="adding-interaction-term" class="level3" data-number="9.5.1"><h3 data-number="9.5.1" class="anchored" data-anchor-id="adding-interaction-term">
<span class="header-section-number">9.5.1</span> Adding interaction term</h3>
<p>Now that we have selected the main effects, let’s reconsider the interaction between <code>enrollment_th</code> and <code>type</code>. <a href="#fig-ncaa-logx-logy-int" class="quarto-xref">Figure&nbsp;<span>9.11</span></a> visualizes <code>log(expenditure_m)</code> versus <code>log(enrollment_th)</code> by <code>type</code> to see if there is a potential interaction effect using the transformed variables.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ncaa-logx-logy-int" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ncaa-logx-logy-int-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="09-mlr-transformations_files/figure-html/fig-ncaa-logx-logy-int-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="Figure&nbsp;9.11: Expenditure versus enrollment by institution type"><img src="09-mlr-transformations_files/figure-html/fig-ncaa-logx-logy-int-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ncaa-logx-logy-int-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.11: Expenditure versus enrollment by institution type
</figcaption></figure>
</div>
</div>
</div>
<p>The plot shows that there may be an interaction effect, because the slope of the relationship between <code>log(expenditure_m)</code> and <code>log(enrollment_th)</code> is steeper for public colleges than for private colleges. Given this plot, we include the interaction term to the model selected in <a href="#sec-transform-choose-model" class="quarto-xref"><span>Section 9.5</span></a>. The output is in <a href="#tbl-ncaa-model-logx-logy-int" class="quarto-xref">Table&nbsp;<span>9.7</span></a>.</p>
<div class="cell">
<div id="tbl-ncaa-model-logx-logy-int" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-model-logx-logy-int-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.7: Model including interaction term with 95% confidence intervals
</figcaption><div aria-describedby="tbl-ncaa-model-logx-logy-int-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 34%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">1.308</td>
<td style="text-align: right;">0.131</td>
<td style="text-align: right;">9.96</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.050</td>
<td style="text-align: right;">1.566</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(enrollment_th)</td>
<td style="text-align: right;">0.524</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">7.58</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.388</td>
<td style="text-align: right;">0.660</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionNortheast</td>
<td style="text-align: right;">-0.339</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">-3.67</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-0.521</td>
<td style="text-align: right;">-0.158</td>
</tr>
<tr class="even">
<td style="text-align: left;">regionSouth</td>
<td style="text-align: right;">-0.117</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">-1.58</td>
<td style="text-align: right;">0.114</td>
<td style="text-align: right;">-0.262</td>
<td style="text-align: right;">0.028</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionWest</td>
<td style="text-align: right;">-0.232</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">-2.54</td>
<td style="text-align: right;">0.011</td>
<td style="text-align: right;">-0.411</td>
<td style="text-align: right;">-0.053</td>
</tr>
<tr class="even">
<td style="text-align: left;">typePublic</td>
<td style="text-align: right;">-1.284</td>
<td style="text-align: right;">0.162</td>
<td style="text-align: right;">-7.94</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">-1.602</td>
<td style="text-align: right;">-0.966</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log(enrollment_th):typePublic</td>
<td style="text-align: right;">0.255</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">0.002</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.414</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The confidence interval for <code>log(enrollment_th):typePublic</code> gives evidence that the interaction is useful to include in the model. Additionally, the <span class="math inline">\(R^2\)</span> for this model is 0.53, which is higher than the model chosen from <a href="#tbl-ncaa-compare-models" class="quarto-xref">Table&nbsp;<span>9.6</span></a>. The equation for the model with the interaction term is</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{\log(\text{expenditure\_m}_i)} &amp;= 1.308 + 0.524 \times \log(\text{enrollment\_th}_i)\\
&amp;- 0.339 \times \text{Northeast}_i - 0.117 \times \text{South}_i \\
&amp;- 0.232 \times \text{West}_i - 1.284 \times \text{Public}_i \\
&amp; + 0.255 \times \log(\text{enrollment\_th}_i) \times \text{Public}_i
\end{aligned}
\]</span></p>
<p>We put together the concepts from <a href="07-mlr.html#sec-mlr-interaction" class="quarto-xref"><span>Section 7.7</span></a> and <a href="#sec-transform-logx-logy" class="quarto-xref"><span>Section 9.4</span></a> to interpret the model coefficients describing the relationship between <code>enrollment_th</code>, <code>type</code>, and <code>expenditure_m</code> on basketball programs. The coefficient of the interaction term <span class="math inline">\(\hat{\beta}_{interaction} = 0.255\)</span> means that <span class="math inline">\(\log(\text{expenditure})\)</span> changes (increases or decreases) by an additional <span class="math inline">\(C \times 0.255\)</span> for public colleges compared to private colleges when enrollment is multiplied by a factor <span class="math inline">\(C\)</span>. This means that the expenditure is expected to multiply by an additional <span class="math inline">\(C^{0.255}\)</span> for public institutions compared to private ones.</p>
<p>Below are the interpretations of the relationship between enrollment and expenditure for public and private schools given a 10% increase in the enrollment.</p>
<blockquote class="blockquote">
<p><em>For each additional 10% increase (</em> <span class="math inline">\(C = 1.1\)</span><em>) in enrollment at <strong>private</strong> NCAA Division I <strong>private</strong> colleges, the expenditure on basketball programs is expected to multiply by 1.689</em> <span class="math inline">\((e^{0.524})\)</span><em>, holding region constant.</em></p>
<p><em>For each additional 10% increase (</em> <span class="math inline">\(C = 1.1\)</span><em>) in enrollment at <strong>public</strong> NCAA Division I colleges, the expenditure on basketball programs is expected to multiply by 2.179</em> <span class="math inline">\((e^{0.524 + 0.255})\)</span><em>, holding region constant.</em></p>
</blockquote>
<!--# maybe clarify the wording here to make it clear that is addition-->
<!--# start here-->
<div class="analysis_in_practice">
<p>We interpreted the relationship between enrollment and expenditure and how it differs for public and private colleges. But what if we wish to just describe how expenditure differs between public and private colleges, on average?</p>
<p>The coefficient of Public, <span class="math inline">\(\hat{\beta}_{\text{public}} = -1.284\)</span> is the expected difference in the expenditure on basketball programs between public and private colleges <u>with <code>enrollment_th = 0</code></u>. A college with zero students does not make sense in practice, so we cannot meaningfully interpret this value in isolation.</p>
<p><br></p>
<p>Therefore, we need to include both the main effect and the interaction term in order to describe how expenditures at public and private colleges differ, on average (<code>-1.284 + 0.255 * enrollment_th</code>). We plug in different values of enrollment to interpret the difference.</p>
<p><br></p>
<p>For example, let’s consider how the average expenditure differs between public and private colleges for colleges with 5000 students. Assume region is the same.</p>
<blockquote class="blockquote">
<p>Public NCAA Division I institutions with 5000 students are expected to spend 1273.716 (<code>-1.284 + 0.255 * 5000</code>) times the expenditure at private colleges with the same enrollment in the same region.</p>
</blockquote>
</div>
<div class="yourturn">
<p>Describe how the expenditure on basketball programs compare between public and private NCAA Division I colleges with 10,000 students enrolled. Assume both are in the South region.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
</div>
</section></section><section id="variable-transformations-in-r" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="variable-transformations-in-r">
<span class="header-section-number">9.6</span> Variable transformations in R</h2>
<p>The code for fitting a linear regression model with one or more transformed variables is very similar to the code shown in <a href="07-mlr.html#sec-mlr-estimate-r" class="quarto-xref"><span>Section 7.8.1</span></a>. Use <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code> to apply the (natural) log transformation on a variable. The code for all the models introduced in this chapter is shown below:</p>
<p><strong>Original model</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ncaa_model_orig</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">expenditure_m</span> <span class="op">~</span> <span class="va">enrollment_th</span> <span class="op">+</span> <span class="va">region</span> <span class="op">+</span> <span class="va">type</span>, </span>
<span>                      data <span class="op">=</span> <span class="va">ncaa_basketball</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Model with <code>log(expenditure_m)</code></strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ncaa_model_logy</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">expenditure_m</span><span class="op">)</span> <span class="op">~</span> <span class="va">enrollment_th</span> <span class="op">+</span> <span class="va">region</span> <span class="op">+</span> <span class="va">type</span>, </span>
<span>                      data <span class="op">=</span> <span class="va">ncaa_basketball</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Model with <code>log(enrollment_th)</code></strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ncaa_model_logx</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">expenditure_m</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">enrollment_th</span><span class="op">)</span> <span class="op">+</span> <span class="va">region</span> <span class="op">+</span> <span class="va">type</span>, </span>
<span>                      data <span class="op">=</span> <span class="va">ncaa_basketball</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Model with <code>log(enrollment_th)</code> , <code>log(expenditure_m)</code> , and interaction</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ncaa_model_final</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">expenditure_m</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">enrollment_th</span><span class="op">)</span> <span class="op">+</span> <span class="va">region</span> <span class="op">+</span> <span class="va">type</span> <span class="op">+</span> </span>
<span>                         <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">enrollment_th</span><span class="op">)</span> <span class="op">*</span> <span class="va">type</span>,</span>
<span>                       data <span class="op">=</span> <span class="va">ncaa_basketball</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The function <code><a href="https://rdrr.io/r/base/Log.html">exp()</a></code> is used to exponentiate coefficients when writing interpretations for models with a log-transformed response variable. For example, <span class="math inline">\(e^2\)</span> is computed as <code>exp(2)</code> in R. Below is code and output to make a new column with the exponentiated coefficients for the final model with <code>log(enrollment_th)</code>, <code>log(expenditure_m)</code>, and the interaction term. Note when displaying results using <code>tidy()</code> the coefficients are contained in the column <code>estimate</code> .</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">tidy</span><span class="op">(</span><span class="va">ncaa_model_final</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span>exp_coefficient <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="va">estimate</span><span class="op">)</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 6
  term               estimate std.error statistic  p.value exp_coefficient
  &lt;chr&gt;                 &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;
1 (Intercept)           1.31     0.131       9.96 9.73e-21           3.70 
2 log(enrollment_th)    0.524    0.0691      7.58 3.17e-13           1.69 
3 regionNortheast      -0.339    0.0924     -3.67 2.78e- 4           0.712
4 regionSouth          -0.117    0.0739     -1.58 1.14e- 1           0.890
5 regionWest           -0.232    0.0912     -2.54 1.14e- 2           0.793
6 typePublic           -1.28     0.162      -7.94 2.83e-14           0.277
# ℹ 1 more row</code></pre>
</div>
</div>
<p>Instead of adding a new column, we may wish to automatically produce the exponentiated coefficients. The output produced by <code>tidy()</code> is in terms of the response variable by default. Therefore, the output is in terms of <span class="math inline">\(\log(y)\)</span> when fitting a model with a log-transformed response variable. The argument <code>exponentiate = TRUE</code> in <code>tidy()</code> is used to output the exponentiated coefficients, <span class="math inline">\(e^{\beta_j}\)</span>, so the model output is in terms of the original variable.</p>
<p>Below is the code and output for the model in <a href="#tbl-ncaa-model-logx-logy-int" class="quarto-xref">Table&nbsp;<span>9.7</span></a> in terms of the original response <code>expenditure_m</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">ncaa_model_final</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">expenditure_m</span><span class="op">)</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">enrollment_th</span><span class="op">)</span> <span class="op">+</span> <span class="va">region</span> <span class="op">+</span> <span class="va">type</span> <span class="op">+</span> </span>
<span>                         <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">enrollment_th</span><span class="op">)</span> <span class="op">*</span> <span class="va">type</span>, </span>
<span>                       data <span class="op">=</span> <span class="va">ncaa_basketball</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">tidy</span><span class="op">(</span><span class="va">ncaa_model_final</span>, exponentiate <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">kable</span><span class="op">(</span>digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-ncaa-final-exponentiated" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ncaa-final-exponentiated-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.8: Exponentiated coefficients for model using log-transformed repsonse and predictor
</figcaption><div aria-describedby="tbl-ncaa-final-exponentiated-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 44%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
</colgroup>
<thead><tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.698</td>
<td style="text-align: right;">0.131</td>
<td style="text-align: right;">9.96</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">log(enrollment_th)</td>
<td style="text-align: right;">1.689</td>
<td style="text-align: right;">0.069</td>
<td style="text-align: right;">7.58</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionNortheast</td>
<td style="text-align: right;">0.712</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">-3.67</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">regionSouth</td>
<td style="text-align: right;">0.890</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">-1.58</td>
<td style="text-align: right;">0.114</td>
</tr>
<tr class="odd">
<td style="text-align: left;">regionWest</td>
<td style="text-align: right;">0.793</td>
<td style="text-align: right;">0.091</td>
<td style="text-align: right;">-2.54</td>
<td style="text-align: right;">0.011</td>
</tr>
<tr class="even">
<td style="text-align: left;">typePublic</td>
<td style="text-align: right;">0.277</td>
<td style="text-align: right;">0.162</td>
<td style="text-align: right;">-7.94</td>
<td style="text-align: right;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">log(enrollment_th):typePublic</td>
<td style="text-align: right;">1.290</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">0.002</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="summary" class="level2" data-number="9.7"><h2 data-number="9.7" class="anchored" data-anchor-id="summary">
<span class="header-section-number">9.7</span> Summary</h2>
<p>In this chapter, we introduced transformations for non-linear relationships, with a focus on log transformations. We used exploratory data analysis, plots of residuals versus fitted values, and subject matter knowledge to identify scenarios in which a transformation is needed to best capture the relationships in the data. We introduced variance-stabilizing transformations on the response variable to address violations of the equal variance condition and a log transformation on the predictor variable to capture decreasing effect as the predictor increases. We also presented and interpreted models with log transformations on both the response and predictor variables.</p>
<p>We used <span class="math inline">\(R^2\)</span> to select the model that best fit the data; however, there are other model performance statistics available to compare and select a model. In <a href="10-model-eval.html" class="quarto-xref"><span>Chapter 10</span></a>, we will discuss model evaluation and selection in more depth, including stepwise methods and cross validation.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-box1964analysis" class="csl-entry" role="listitem">
Box, George EP, and David R Cox. 1964. <span>“An Analysis of Transformations.”</span> <em>Journal of the Royal Statistical Society Series B: Statistical Methodology</em> 26 (2): 211–43.
</div>
<div id="ref-ncaa_divisional_differences_2013" class="csl-entry" role="listitem">
NCAA. 2013. <span>“Divisional Differences and the History of Multidivision Classification.”</span> National Collegiate Athletic Association. <a href="https://www.ncaa.org/sports/2013/11/20/divisional-differences-and-the-history-of-multidivision-classification.aspx">https://www.ncaa.org/sports/2013/11/20/divisional-differences-and-the-history-of-multidivision-classification.aspx</a>.
</div>
<div id="ref-ope_equity_athletics_database" class="csl-entry" role="listitem">
U.S. Department of Education, Office of Postsecondary Education. 2025. <span>“Equity in Athletics Data Analysis Cutting Tool.”</span> U.S. Department of Education. <a href="https://ope.ed.gov/athletics/">https://ope.ed.gov/athletics/</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>Interested readers are encouraged to visit the EADA for further data exploration!<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>There appears to be a potential interaction between <code>enrollment_th</code> and <code>type</code> . The slope of the relationship between <code>enrollment_th</code> and <code>expenditure</code> appears to be different based on the type of college.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>From the figure, it appears <a href="#fig-ncaa-model-compare-4" class="quarto-xref">Figure&nbsp;<span>9.6 (d)</span></a> with with a log transformation on both <code>enrollment_th</code> and <code>expenditure_m</code> would be best represented by a linear model, because the shape is most linear.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The total expenditure on basketball programs for NCAA Division I colleges that are public is expected to be 0.511 (<span class="math inline">\(e^{-0.672}\)</span>) <strong>times</strong> the expenditure at private institutions, holding enrollment and region constant.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>No.&nbsp;The interpretation of the intercept is not meaningful, because there cannot be a college with 0 students. We could center <code>enrollment_th</code> , so that the intercept represents colleges with some other value of enrollment (e.g., the mean enrollment in the data).<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>When the enrollment increases by 50% (is multiplied by 1.5), the expenditure on basketball programs at NCAA Division I colleges is expected to increase by 2.43 (5.992 <span class="math inline">\(\times\)</span> log(1.5)) million dollars, on average, holding type and region constant.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The expenditure on basketball programs at public NCAA Division I colleges is expected to be 0.436 times the expenditure at private institutions, holding region and enrollment constant. Note, since the there is no transformation on the predictor <code>type</code> (or any categorical predictor), the interpretation is very similar to the interpretations in <a href="#sec-transform-logy" class="quarto-xref"><span>Section 9.2</span></a>.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Public NCAA Division I institutions with 10,000 students are expected to spend 2548.716 (<code>-1.284 + 0.255 * 10000</code>) times the expenditure at private colleges with the same enrollment, holding region constant.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/introregressio\.netlify\.app");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./08-mlr-inference.html" class="pagination-link" aria-label="Inference for multiple linear regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inference for multiple linear regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-model-eval.html" class="pagination-link" aria-label="Model selection">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model selection</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/matackett/regression-book/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>