{
  "hash": "b9c45ad83b15ff5b1c7210a0a96f4026",
  "result": {
    "engine": "knitr",
    "markdown": "# Special topics {#sec-ch-special-topics}\n\n\n\n\n::: {.cell}\n\n:::\n\n\n## Learning goals {.unnumbered}\n\nThis chapter introduces readers to a collection to models that are extensions of linear and logistic regression. The goal is to provide an introduction to the topic along with resources for those interested in learning more. The following topics are introduced:\n\n-   Multinomial logistic regression\n-   Random intercepts models\n-   Decision trees for regression and classification\n-   Causal inference using propensity score models\n\n## Multinomial logistic regression {#sec-multinomial}\n\nIn @sec-ch-logistic, we introduced logistic regression models for binary response variables. In this section, we introduce multinomial logistic regression, models for categorical response variables with three or more levels.\n\n### Data: Voting frequency {#sec-voters-data}\n\nIn the 2020 article “Why Many Americans Don’t Vote” [@ThomsonDeVeaux_et_al_2020] on the now defunct data journalism website FiveThirtyEight, journalists explored the voting behavior of eligible voters in the United States. <!--# maybe add something else here about the article--> As indicated by the article's title, their primary objective was to understand why many eligible voters choose not to vote at all or only vote sporadically. <!--# include something here about the data collection--> They considered numerous factors in their analysis, but we will focus on a few, age and political affiliation, for this analysis. <!--# need to include somewhere that this is includes people who were eligible in the last four elections-->\n\nThe data were obtained from the FiveThirtyEight data website ([https://data.fivethirtyeight.com](https://data.fivethirtyeight.com/)) and is available in `fivethirtyeight-voters-data.csv`. It contains survey responses <!--# is survey correct?--> from 5836 respondents. All survey participants had been eligible to vote in at least four prior elections. The variables used in this analysis are below. The definitions are adapted from the data documentation (<https://github.com/fivethirtyeight/data/tree/master/non-voters>)\n\n-   `voter_category`: An respondent's past voting behavior, categorized as\n\n    -   `always`: respondent voted in all or all-but-one of the elections they were eligible in\n\n    -   `sporadic`: respondent voted in at least two, but fewer than all-but-one of the elections they were eligible in\n\n    -   `rarely/never`: respondent voted in 0 or 1 of the elections they were eligible in\n\n-   `age`: Respondent's age in years (called `ppage` in original data set)\n\n-   `party_id`: Respondent's political affiliation categorized as `Democrat`, `Republican` , `No affiliation`. This variable was derived from the variable `Q30` in the original data set, defined as the following:\n\n    -   *Response to the question “Generally speaking, do you think of yourself as a…”*\n\n        -   *1:Republican*\n\n        -   *2: Democrat*\n\n        -   *3: Independent*\n\n        -   *4: Another party, please specify*\n\n        -   *5: No preference*\n\n        -   *-1: No response*\n\n    -   Responses `3, 4, 5,-1` are classified as \"No affiliation\" in this analysis.\n\n-   `income_cat`: Respondent's annual income (`Less than $40k`, `$40-75k`, `$75-125k`, `$125k or more`)\n\nThe goal of this analysis is to use `age` and `party_id` to predict `voting_id` and describe factors associated with variability in voting behavior. The univariate exploratory data analysis is in @fig-voting-univar-eda and @tbl-voting-univar-eda.\n\n\n::: {#fig-voting-univar-eda .cell layout=\"[[1], [1,1]]\"}\n::: {.cell-output-display}\n![`voter_category`](13-special-topics_files/figure-html/fig-voting-univar-eda-1.png){#fig-voting-univar-eda-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![`age`](13-special-topics_files/figure-html/fig-voting-univar-eda-2.png){#fig-voting-univar-eda-2 width=100%}\n:::\n\n::: {.cell-output-display}\n![`party_id`](13-special-topics_files/figure-html/fig-voting-univar-eda-3.png){#fig-voting-univar-eda-3 width=100%}\n:::\n\nUnivariate EDA for voting frequency data\n:::\n\n\n\n::: {#tbl-voting-univar-eda .cell tbl-cap='Summary statistics for `age`'}\n::: {.cell-output-display}\n\n\n|Variable | Mean|   SD| Min| Q1| Median (Q2)| Q3| Max| Missing|\n|:--------|----:|----:|---:|--:|-----------:|--:|---:|-------:|\n|age      | 51.7| 17.1|  22| 36|          54| 65|  94|       0|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThe most common voting frequency among respondents in `sporadic`, with 44.1% of the voters being in this category. About 24.9% of the respondents vote rarely or never, and 31% of the respondents voted always. The distribution of `age` is bimodal and skewed right. The median age in the data set is 54 years old, and the IQR is 29 years. The most common political party identification is \"No affiliation\" with about 38.4% of the respondents. About 34.3% of the respondents identified as \"Democrat\" and about 27.3% as \"Republican\".\n\n\n::: {#fig-voting-bivar-eda .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![`voter_category` versus `age`](13-special-topics_files/figure-html/fig-voting-bivar-eda-1.png){#fig-voting-bivar-eda-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![`voter_category` versus `party_id`](13-special-topics_files/figure-html/fig-voting-bivar-eda-2.png){#fig-voting-bivar-eda-2 width=100%}\n:::\n\nBivariate EDA for voting frequency data. Blue: rarely/never, Red: sporadic, Yellow: always\n:::\n\n\nThe bivariate exploratory data analysis is in @fig-voting-bivar-eda. From @fig-voting-bivar-eda-1, the distribution of `age` among voters categorized as \"always\" is bimodal with a peak around 25 years old and another around 60 years old. In contrast, the distribution of `age` among voters categorized as \"rarely/never\" is unimodal and skewed towards younger voters. This suggest there may be a relationship between age and voting frequency.\n\nFrom @fig-voting-bivar-eda-2, the voters who have no political party affiliation are the most likely to vote \"rarely/never\" and the least likely to vote \"always\". The distribution of voting frequency appears to be similar between Democrats and Republicans. This indicates there may be some relationship between political party identification (or even whether or not someone identifies with a political party) and voting frequency.\n\nWe have some initial insights from the data about overall voting frequency and potential relationships with age and political party affiliation, so we want to fit a model to summarize the relationship between these variables that we can use to draw robust conclusions and make predictions.\n\n### Multinomial logistic model\n\nThe response variable in this analysis has three levels, so we will use an extension of the logistic regression model. **Multinomial logistic regression** is part of the wider class of models called *generalized linear models*. It is a model for data with a categorical response variable that has three or more levels. Such response variables follow a multinomial distribution.\n\n::: {.math_rules latex=\"\"}\n**Multinomial distribution**\n\nLet $Y$ be a categorical random variable with $K > 2$ levels. Then,\n\n$$P(Y = 1) = \\pi_1, P(Y = 2) = \\pi_2, \\ldots, P(Y = K) = \\pi_K$$ such that $\\sum_{k=1}^K \\pi_K = 1$\n:::\n\nLet's look at the general form of the multinomial logistic regression model, then apply it to model voting frequency. Suppose we have a categorical response variable that takes values $A$, $B$, and $C$. Let $A$ be the baseline level. Then, the general form of the multinomial logistic regression model is\n\n$$\\begin{aligned}\n\\log\\Big(\\frac{\\pi_B}{\\pi_A}\\Big) = \\beta_{0\nB} + \\beta_{1B}X_1 +\\beta_{2B}X_2 + \\dots + \\beta_{pB}X_p \\\\\n\\log\\Big(\\frac{\\pi_C}{\\pi_A}\\Big) = \\beta_{0C} + \\beta_{1C}X_1 +\\beta_{2C}X_2 + \\dots + \\beta_{pC}X_p \n\\end{aligned}\n$$ {#eq-multinom-general}\n\nFrom @eq-multinom-general, we see a few features of the multinomial logistic model. We start by choosing a baseline level for the response variable. Each equation in the fitted model quantifies the log odds of being at another level of the response variable versus the baseline[^13-special-topics-1]. WE saw this implicitly in logistic regression, where the response variable, $\\log(\\frac{\\pi}{1-\\pi})$, is the \"log odds of $Y = 1$ versus $Y = 0$.\"\n\n[^13-special-topics-1]: Similar to how categorical predictors are interpreted as one level versus the baseline ([see @sec-mlr-interpret-categorical]).\n\nThe next feature of multinomial logistic regression is the multiple equations that comprise the model. More specifically, if the response variable has $K$ levels, then there will be $K - 1$ equations in the model. We will ultimately use the model to compute the predicted probabilities an observation takes each level of the response variable, so we need all $K-1$ equations in order to compute the predicted probabilities for every level of the response variable.\n\nThe last feature is that each of the $K -1$ equations have the same form but different values of the coefficients. This is shown in @eq-multinom-general as the $\\beta's$ have unique indices in each equation. As with logistic regression, the coefficients for multinomial logistic regression are estimated using maximum likelihood estimation ([see @sec-logistic-interpret-coef]).\n\n@tbl-voter-model is the multinomial logistic regression model using `age` and `party_id` to predict `voter_category`.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#tbl-voter-model .cell tbl-cap='Model of `voter_category` versus `age` and `party_id` with 95% confidence intervals for the coefficients'}\n::: {.cell-output-display}\n\n\n|y.level  |term                   | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:--------|:----------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|sporadic |(Intercept)            |   -1.046|     0.116|    -9.031|   0.000|   -1.273|    -0.819|\n|sporadic |age                    |    0.041|     0.002|    18.834|   0.000|    0.036|     0.045|\n|sporadic |party_idNo affiliation |   -0.677|     0.081|    -8.389|   0.000|   -0.836|    -0.519|\n|sporadic |party_idRepublican     |   -0.106|     0.095|    -1.118|   0.264|   -0.292|     0.080|\n|always   |(Intercept)            |   -1.983|     0.131|   -15.157|   0.000|   -2.240|    -1.727|\n|always   |age                    |    0.052|     0.002|    22.144|   0.000|    0.048|     0.057|\n|always   |party_idNo affiliation |   -0.872|     0.089|    -9.824|   0.000|   -1.046|    -0.698|\n|always   |party_idRepublican     |   -0.091|     0.101|    -0.901|   0.368|   -0.288|     0.106|\n\n\n:::\n:::\n\n\nThe column `y.level` indicates the corresponding level for the given equation. The level of the response variable that is not listed is the baseline. In this case, the baseline level is `rarely/never`. Therefore, this model produces the log odds of being in the other categories versus rarely/ never.\n\nWe can write the model in @tbl-voter-model as the following:\n\n$$\n\\begin{aligned}\n\\log\\Big(\\frac{\\pi_{sporadic}}{\\pi_{rarely/never}}\\Big)  = -1.046 + 0.041 \\times \\text{age} -0.677 \\times \\text{No affiliation} -0.106 \\times \\text{Republican} \\\\\n\\log\\Big(\\frac{\\pi_{always}}{\\pi_{rarely/never}}\\Big)  = -1.983 + 0.052 \\times \\text{age} -0.872 \\times \\text{No affiliation}  -0.091 \\times \\text{Republican}\n\\end{aligned}\n$$\n\n### Interpretation\n\nThe interpretation for the coefficients of the multinomial logistic model are very similar to the interpretations for the logistic model in @sec-logistic-interpret-coef. Like logistic regression, the model coefficients represent the change in the log odds, but in practice want to write interpretations in terms of the odds. The primary difference in the interpretation is the explicit statement of the baseline level of the response variable.\n\nLet's interpret the coefficients in terms of having the voter frequency of `sporadic` versus `rarely/never`. The interpretation of `age` in terms of the log odds is as follows:\n\n> *For each additional year older, the log odds of an individual voting sporadically versus rarely/never are expected to increase by 0.041, holding political affiliation constant.*\n\nThe interpretation in terms of the odds is the following:\n\n> **For each additional year older, the** <b>odds</b> of an individual voting sporadically versus rarely/never are expected to multiply by 1.042 $(e^{0.041})$, holding political affiliation constant.\n\nNext, we interpret the effect of political affiliation on the voting frequency. As with other models, we write the interpretation in reference to the baseline level of the categorical predictor. The interpretation of the coefficients for `party_id` in terms of the log odds are the following:\n\n> *The log odds an individual who has no political affiliation votes sporadically versus rarely/never are 0.677 less than the log odds of an individual whose party affiliation is Democrat, holding age constant.*\n\n> *The log odds an individual whose political affiliation is Republican votes sporadically versus rarely/never are 0.106 less than the log odds of an individual whose party affiliation is Democrat, holding age constant.*\n\nThe interpretations in terms of the odds are as follows:\n\n> *The* <b>odds</b> an individual who has no political affiliation votes sporadically versus rarely/never are 0.508 $(e^{-0.872})$ times the odds of an individual whose party affiliation is Democrat, holding age constant.\n\n> *The* <b>odds</b> an individual whose political affiliation is Republican votes sporadically versus rarely/never are 0.899 $(e^{-0.106})$ times the odds of an individual whose party affiliation is Democrat, holding age constant.\n\nAlong with the coefficients in @tbl-voter-model are 95% confidence intervals for the population coefficients. These confidence intervals are estimated in a similar way as those for logistic regression in @sec-logistic-inf. As with previous models, we look to see whether the confidence interval contains 0 to determine whether it is a useful predictor in explaining variability in voting frequency after adjusting for the other predictors. In both equations in @tbl-voter-model, none of the confidence intervals for `age` and `party_idNoaffiliation` include 0. Thus, both of these indicators are helpful in understanding voting frequency. In contrast, the confidence intervals for `party_idRepublican` do contain 0, so the voting behavior for Republicans does not differ significantly from Democrats, after adjusting for age. This is consistent with the observations from @fig-voting-bivar-eda-2.\n\n::: {.analysis_in_practice latex=\"\"}\nIn @tbl-voter-model, the inferential conclusions for each predictor are the same for both equations in the multinomial logistic model. This is not a requirement for multinomial logistic regression and is not always the case. It could be possible for a predictor to be useful in differentiating `always` versus `rarely/never`, but not useful in differentiating `sporadic` versus `rarely/never`.\n:::\n\n### Prediction and classification\n\nWe often want to use multinomial logistic regression models for prediction, and more specifically classifying observations into the groups defined by the response variable. We can use the log odds produced by the multinomial logistic model to compute probabilities, then use those probabilities for classification.\n\nLet's go back to the general form of the model in @eq-multinom-general. The predicted probability an observation is in category $B$ is computed as\n\n$$\n\\hat{\\pi}_B = \\frac{e^{\\beta_{0B} + \\beta_{1B}X_1 + \\beta_{2B}X_2 + \\dots + \\beta_{pB}X_p}}{1 + \\sum_{k \\in (B,C)}e^{\\beta_{0k} + \\beta_{1k}X_1 + \\beta_{2k}X_2 + \\dots + \\beta_{pk}X_p}}\n$$ {#eq-multinom-pred-prob}\n\n<!--# do i want to do the subscript i?-->\n\nThe numerator of @eq-multinom-pred-prob are the odds of an observation being in category $B$ versus the baseline $A$. The denominator is the sum of the odds for every possible level. In this example, it is the sum of the odds an observation is in category $A$ versus $A$ (that's the \"1\" in the denominator), the odds an observation is in category $B$ versus $A$, and the odds an observation is in category $C$ versus $A$. A similar formula is used to compute $\\hat{p}_c$, the predicted probability of being in category $C$. The difference is the numerator, which would be the odds of being in category $C$ versus $A$.\n\nThe predicted probability an observation is in the baseline category $A$ is computed as\n\n$$\n\\hat{\\pi}_A = 1 - (\\hat{\\pi}_B + \\hat{\\pi}_C)\n$$ {#eq-multinom-pred-baseline}\n\n@eq-multinom-pred-baseline utilizes the fact that the sum of the probabilities across all possible categories equals 1. This is is also why we need all $K - 1$ equations as part of the multinomial logistic when there are $K$ categories of the response variable.\n\n@tbl-voter-model-pred shows the predicted probabilities based on @tbl-voter-model for ten observations in the data.\n\n\n::: {#tbl-voter-model-pred .cell tbl-cap='Predictions from voter frequency model for ten observations'}\n::: {.cell-output-display}\n\n\n|voter_category | rarely/never| sporadic| always|pred_class |\n|:--------------|------------:|--------:|------:|:----------|\n|always         |        0.071|    0.484|  0.446|sporadic   |\n|always         |        0.069|    0.483|  0.447|sporadic   |\n|sporadic       |        0.160|    0.486|  0.354|sporadic   |\n|sporadic       |        0.132|    0.490|  0.379|sporadic   |\n|always         |        0.055|    0.466|  0.479|always     |\n|rarely/never   |        0.220|    0.470|  0.310|sporadic   |\n|always         |        0.057|    0.468|  0.475|always     |\n|always         |        0.087|    0.488|  0.424|sporadic   |\n|always         |        0.088|    0.479|  0.433|sporadic   |\n|always         |        0.093|    0.489|  0.417|sporadic   |\n\n\n:::\n:::\n\n\nThe predicted probabilities are then used to classify the observations based on the model. For each observation, the predicted class is the one with the highest predicted probability. For example, for the first observation in @tbl-voter-model-pred, $\\hat{\\pi}_{rarely/never} = 0.071$, $\\hat{\\pi}_{sporadic} = 0.484$, and $\\hat{\\pi}_{always} = 0.446$. Therefore, the predicted class for this observation is \"sporadic\".\n\n### Confusion matrix\n\nFrom @tbl-voter-model-pred, we see the predicted class is not always equal to the observed class. Therefore, we want to quantify the model performance, specifically how well the model classifies observations and how well it distinguishes observations from a specific class. A confusion matrix, introduced in @sec-classification, is used to compare the observed versus predicted classes. @fig-confmat-voters-model is the confusion matrix for the model in @tbl-voter-model. Because the predicted class is always the category with the highest predicted probability, we do not need to specify a threshold as in logistic regression.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Confusion matrix for voters model](13-special-topics_files/figure-html/fig-confmat-voters-model-1.png){#fig-confmat-voters-model width=100%}\n:::\n:::\n\n\n::: {.yourturn latex=\"\"}\nUse @fig-confmat-voters-model to compute\n\n-   the accuracy.\n\n-   the misclassification rate[^13-special-topics-2]\n\nThere are 5836 observations in the data.\n:::\n\n[^13-special-topics-2]: The accuracy is the 0.493 $(563 + 2219 + 94)/5836)$. The misclassification rate is 0.507 $(1 - 0.407)$.\n\n@fig-confmat-voters-model can also be used to compute more specific statistics about how well the model identifies observations from a particular class. For example, among those who are actually classified voting rarely/never, the model correctly identified 38.801 % of them.\n\nConversely, among those who were classified by the model as rarely/never, 49.343% of them actually vote rarely/never.\n\n### ROC Curves and AUC\n\nReceiver Operating Characteristic (ROC) curves, introduced in @sec-roc, can be used to evaluate how well the model distinguishes observations from a particular category. To do so, we create **multiclass ROC curves** using a \"one versus all\" approach that evaluates how well the model distinguishes one category versus all the others. For example, one curve represents how well the model distinguishes \"always\" voters versus all the others (\"rarely/never\" and \"sporadic\"). Essentially, we compute a logistic regression ROC curve for each possible class of the response.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Multiclass ROC curves for the voter frequency model in @tbl-voter-model](13-special-topics_files/figure-html/fig-voters-roc-curve-1.png){#fig-voters-roc-curve width=100%}\n:::\n:::\n\n\n@fig-voters-roc-curve shows the multiclass ROC curve for the model in @tbl-voter-model. We interpret this curve similarly to the ROC curve for logistic regression. Curves close to the upper-left portion of the graph indicate good model distinguishing, but curves close to the diagonal line indicate poor model distinguishing. Based on this, the model performs best in identifying \"rarely/never\" voters versus the others and does the worst in identifying sporadic voters.\n\n\n::: {.cell}\n\n:::\n\n\nThe overall model performance is quantified using the **average area under the curve (AUC)**. The average AUC is computed in two ways. The first by computing the AUC for each class, then taking the average across all values of AUC. The average AUC for @fig-voters-roc-curve is 0.656 . The second approach is to weight the AUC by the number of observations actually in each class. Therefore, larger classes have more influence on the measure of model performance. Using this approach, the average AUC for @fig-voters-roc-curve is 0.627.\n\n### Multinomial logistic regression in R\n\nMultinomial logistic models are fit using `multinom()` from the **nnet** R package [@nnet].\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# library(nnet) \n\nvoter_fit <- multinom(voter_category ~ age + party_id,\n                      data = voters)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  15 (8 variable)\ninitial  value 6411.501317 \niter  10 value 5881.210811\nfinal  value 5858.219129 \nconverged\n```\n\n\n:::\n:::\n\n\nThe model output can be tidied and neatly displayed using `tidy()` from the **broom** package [@broom] and `kable()` from the **knitR** package [@knitr].\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(voter_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|y.level  |term                   | estimate| std.error| statistic| p.value|\n|:--------|:----------------------|--------:|---------:|---------:|-------:|\n|sporadic |(Intercept)            |   -1.046|     0.116|    -9.031|   0.000|\n|sporadic |age                    |    0.041|     0.002|    18.834|   0.000|\n|sporadic |party_idNo affiliation |   -0.677|     0.081|    -8.389|   0.000|\n|sporadic |party_idRepublican     |   -0.106|     0.095|    -1.118|   0.264|\n|always   |(Intercept)            |   -1.983|     0.131|   -15.157|   0.000|\n|always   |age                    |    0.052|     0.002|    22.144|   0.000|\n|always   |party_idNo affiliation |   -0.872|     0.089|    -9.824|   0.000|\n|always   |party_idRepublican     |   -0.091|     0.101|    -0.901|   0.368|\n\n\n:::\n:::\n\n\n::: {.analysis_in_practice latex=\"\"}\n**Suppress model fit messages**\n\nThe coefficients are estimated using numerical approximation methods to find the values that maximize the likelihood function. The `mulitnom` function will produce a message summarizing the optimization iterations. This information is generally not necessary in practice, so include the code chunk option `#| results:  hide` in Quarto documents to suppress the message.\n:::\n\nPredictions from the multinomial model are computed using the `predict()` function. The argument `type = \"probs\"` produces a matrix of the predicted probabilities and `type = \"class\"` produces a vector of the predicted classes.\n\nWe add these to the original tibble for additional analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute predicted probabilities\nvoter_pred_prob <- predict(voter_fit, type = \"probs\")\n\n# compute predicted class\nvoter_pred_class <- predict(voter_fit, type = \"class\")\n\n# add predictions to original tibble\nvoters <- voters |> \n  bind_cols(voter_pred_prob) |>\n  mutate(pred_class = voter_pred_class)\n```\n:::\n\n\nThe syntax for the confusion matrix, ROC curves, and AUC are similar to logistic regression in @sec-logistic-prediction-R.\n\nThe confusion matrix is produced using `conf_mat()` from the **yardstick** R package [@yardstick]. We use `autoplot()` to format the confusion matrix such that the cells are shaded by the number of observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvoters |> \n  conf_mat(voter_category, pred_class) |>\n  autoplot(type = \"heatmap\")\n```\n\n::: {.cell-output-display}\n![](13-special-topics_files/figure-html/unnamed-chunk-5-1.png){width=100%}\n:::\n:::\n\n\nThe multiclass ROC curves are produced using `roc_curve()` in the **yardstick** R package [@yardstick]. The argument `truth =` specifies the columns with the observed classes, and the next line of code indicates the columns that contain the predicted probabilities. The `roc_curve()` function produces the data underlying the curves, and `autoplot()` produces the curves.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvoters |> \n  roc_curve(\n    truth = voter_category, \n    `rarely/never`:always\n  ) |> \n  autoplot()\n```\n\n::: {.cell-output-display}\n![](13-special-topics_files/figure-html/unnamed-chunk-6-1.png){width=100%}\n:::\n:::\n\n\nLastly, the AUC is computed using `roc_auc()` from the **yardstick** R package. The the weighted average AUC is computed using the argument `estimator = \"macro_weighted\"`. The unweighted average AUC is computed by default.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute unweighted average AUC\nvoters |> \n  roc_auc(\n    truth = voter_category, \n    `rarely/never`:always\n  ) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc hand_till      0.656\n```\n\n\n:::\n\n```{.r .cell-code}\n# compute weighted average AUC\nvoters |> \n  roc_auc(\n    truth = voter_category, \n    `rarely/never`:always,\n    estimator = \"macro_weighted\"\n  ) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator     .estimate\n  <chr>   <chr>              <dbl>\n1 roc_auc macro_weighted     0.627\n```\n\n\n:::\n:::\n\n\n### Generalized linear models\n\n## Random intercepts model {#sec-random-intercepts}\n\nOne of the key assumptions we've made throughout this book is that the observations in the sample data are independent of each other. Often in practice, however, there is an underlying grouping structure in the data, and the observations are not completely independent of one another. For example, the data may contain multiple measurements from each individual (call repeated measures) as in @fig-repeated-measures.\n\n![Repeated measures data structure](images/13-repeated-measures-structure.png){#fig-repeated-measures fig-align=\"center\" width=\"100%\"}\n\nAnother common grouping structure is having multiple observations from within a single group, such that we expect the observations within the group to be more similar than observations from different groups, as in @fig-grouped-data-structure.\n\n![Grouped data structure](images/13-grouped-data-structure.png){#fig-grouped-data-structure fig-align=\"center\" width=\"100%\"}\n\nData that contain a grouping structure are called **multilevel data**. The individual observations are at the first level of the data, and the groups are at the second level. We use **generalized linear mixed models** (GLMM), also called *multilevel models* or *hierarchical models*, to account for the grouping structure when we fit the model and conduct statistical inference. There are many types of generalized linear mixed models; in fact, there are often entire undergraduate-level courses dedicated to these models. In this section, we will introduce one of the most widely used GLMMs in practice, the random intercepts model.\n\n### Data: Lemurs\n\n\n::: {.cell}\n\n:::\n\n\nIn @sec-ch-mlr, we introduced a data set containing the weight, age, and other characteristics of lemurs living at the Duke Lemur Center. The data used in that chapter contained observations from a single weigh-in for each lemur between 0 and 24 months old. The lemurs were, in fact, weighed regularly, so the original data from @tidytuesday <!--# more specific citation?--> includes multiple measures for each lemur. The data in this section includes all the measurements for each lemur when they were 1 to 24 months old.\n\nThe data are in `lemurs-repeated-measures.csv`. We will use the following variables:\n\n-   `weight`: Weight of the lemur (in grams)\n-   `taxon` : Code made as a combination of the lemur's genus and species. Note that the genus is a broader categorization that includes lemurs from multiple species. <!--# is this note helpful or confusing?--> This analysis focuses on the following taxon:\n    -   `ERUF`: Eulemur rufus, commonly known as Red-fronted brown lemur\n\n    -   `PCOQ`: Propithecus coquereli, commonly known as Coquerel's sifaka\n\n    -   `VRUB`: Varecia rubra, commonly known as Red ruffed lemur\n-   `sex` : Sex of lemur (`M`: Male, `F`: Female)\n-   `age`: Age of lemur when weight was recorded (in months)\n-   `litter_size`: Total number of infants in the litter the lemur was born into (this includes the observed lemur)\n\nSee @tidytuesday for the full codebook. <!--# more specific reference?-->\n\nThe goal of the analysis is to understand a lemur's growth rate (relationship between age and weight) after adjusting for other characteristics.\n\n![Structure of lemur data](images/13-lemurs-data-structure.png){#fig-lemur-structure fig-align=\"center\" width=\"100%\"}\n\nThe lemurs data set is an example of repeated measures, where the data are grouped by lemur as shown in @fig-lemur-structure. These data violate the independence assumption of linear regression models ([@sec-mlr-conditions-diagnositics]) and logistic regression models ([@sec-logistic-conditions]), because we expected observations from a single lemur to be correlated with one another. Some factors (e.g., `taxon` ) will remain constant for all observations from an individual lemur. @tbl-individual-lemur shows the data for an individual lemur.\n\n\n::: {#tbl-individual-lemur .cell tbl-cap='All observations from an individual lemur'}\n::: {.cell-output-display}\n\n\n| dlc_id|name   |taxon |sex | litter_size|   age| weight|\n|------:|:------|:-----|:---|-----------:|-----:|------:|\n|   6492|MIRFAK |VRUB  |M   |           2|  1.32|    590|\n|   6492|MIRFAK |VRUB  |M   |           2|  8.22|   2560|\n|   6492|MIRFAK |VRUB  |M   |           2| 10.06|   2610|\n|   6492|MIRFAK |VRUB  |M   |           2| 12.79|   2800|\n|   6492|MIRFAK |VRUB  |M   |           2| 14.63|   3160|\n|   6492|MIRFAK |VRUB  |M   |           2| 16.47|   3020|\n|   6492|MIRFAK |VRUB  |M   |           2| 18.84|   3340|\n\n\n:::\n:::\n\n\nIn this data, the lemur's `dlc_id`, `name`, `sex`, `taxon`, and `litter_size` remain the same for its observations. These variables are at level two of the data, i.e., they differ between lemurs but are the same for all observations from an individual lemur. The `age` and `weight` are different across observations. These are variables at level one, because they change each time data are collected.\n\n\n::: {.cell}\n\n:::\n\n\nThe data set contains seven observations for the lemur Mirfak in @tbl-individual-lemur , but there are not necessarily seven observations for every lemur in the data. The number of observations for each lemur range from as few as 1 to as many as 120. The GLMMs can account for the different number of observations from each individual. When we fit the model, lemurs with more observations will be weighted more heavily when estimating the coefficients.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![`weight` versus `age` for nine lemurs](13-special-topics_files/figure-html/fig-lemurs-weight-1.png){#fig-lemurs-weight width=100%}\n:::\n:::\n\n\nNow let's take a look at the relationship between `weight` and `age` for the lemurs in the data. @fig-lemurs-weight shows the relationship between these variables for a sample of nine lemurs. The figure illustrates how the number of observations differ for each lemur. We can also begin to see how the weight changes with age for the lemurs. The visualizations of these 9 lemurs give us an idea of the variation in the data, but we would like to visualize the relationship for all the lemurs in the data. To do so, we use a **spaghetti plot**, shown in @fig-lemurs-spaghetti-plot.\n\n\n::: {.cell fig-label='Spaghetti plot of lemurs weight versus age'}\n::: {.cell-output-display}\n![](13-special-topics_files/figure-html/fig-lemurs-spaghetti-plot-1.png){#fig-lemurs-spaghetti-plot width=100%}\n:::\n:::\n\n\nThe gray lines in @fig-lemurs-spaghetti-plot are the relationships between age and weight for each of the 248 lemurs in the data set. The blue line is the average trajectory across all the lemurs. From this plot, we more easily see the difference in the growth rate for the lemurs by the different slopes of the relationship between age and weight. We can also see the general differences in weight across the lemurs at each age.\n\nThe linear regression (and logistic regression) models we've seen thus have a single intercept for all observations. In other words, if we fit a model using age to predict weight, there would be a single intercept for the expected weight for new born lemurs. From @fig-lemurs-spaghetti-plot, we see that the lemurs are generally different weights (even lemurs with the same age and taxon), so a single intercept may not best represent the trend in the data We will use a random intercepts model to account for this additional variability.[^13-special-topics-3]\n\n[^13-special-topics-3]: We can also specify the GLMMs to account for the different slopes of age across the lemurs. That is beyond the scope of this text, but we provide resources at the end of the section for readers interested in learning more.\n\n### Model fit and interpretation\n\nGLMMs differ from the GLMs we've studied thus far, because they include both fixed and random effects. The **fixed effects** are the variables we are interested in studying or explicitly adjusting for in the model. These are the variables for which we want to obtain an estimated coefficient. In the lemurs analysis, the fixed effects are `age`, `taxon`, `sex`, and `litter_size`. The **random effects** are those we don't want to estimate explicitly but whose variability we want to understand. These are generally defined by the grouping variable in the data. In this analysis, the random effect is the individual lemur, captured by the variable `dlc_id`.\n\nThe **random intercepts model** includes fixed and random effects, such that the random effects account for random variability in the intercept. The general form of the model is <!--# think about how to write this./ do i need it?-->\n\nLet $\\text{weight}_{ij}$ be the weight in the $j^{th}$ observation for lemur $i$. Then, the random intercepts model for the lemurs analysis is\n\n$$\n\\begin{aligned}\n\\text{weight}_{ij} = \\beta_0 &+ \\beta_1 ~ \\text{taxonPCOQ}_{i} + \\beta_2 ~ \\text{taxonVRUB}_i \\\\\n& +\\beta_3 ~ \\text{sexM}_{i}  + \\beta_4 ~ \\text{litter\\_size}_{i} + \\beta_5 ~ \\text{age}_{ij}\\\\\n& + u_i + \\epsilon_{ij} \\\\\n&u_i \\sim N(0, \\sigma^2_{u}) \\hspace{5mm} \\epsilon_{ij} \\sim N(0, \\sigma^2_{\\epsilon})\n\\end{aligned}\n$$ {#eq-lemurs-random-int}\n\nLet's break down the components of @eq-lemurs-random-int. The subscript indicate whether the variable is at the first or second level of the data. The variable `age` is the only predictor in the second level that changes for each observation, so the subscript indicates that we plug in the age for lemur $i$ at the $j^{th}$ observation. The other predictors are measured at the second level of the data, so the subscript $i$ indicates that we plug in the same value for lemur $i$ across all its observations. The term $\\beta_0$ is the global intercept. It is the expected (mean) weight across all lemurs when all predictors are equal to 0.\n\nThe error term $\\epsilon_{ij}$ is like the error term previously introduced for linear models. It is the difference between the observed and expected value of the weight for the $j^{th}$ observation from lemur $i$. As in linear regression, these error terms follow a normal distribution with mean of 0 and variance of $\\sigma^2_{\\epsilon}$. This $\\sigma^2_{\\epsilon}$ is a measure of the variability in the weights (response variable) within an individual lemur (group).\n\nThe term $u_{i}$ is the random effect that makes this the \"random intercepts model\". We don't estimate $u_i$ directly, but its distribution tells us about the variability in the average weights between lemurs. The $u_{i}$ are normally distributed with a mean of 0 and variance of $\\sigma^2_{u}$. This $\\sigma^2_{u}$ is the measure of between lemur variability. From this model, the intercept of an individual lemur $i$ is $\\beta_0 + u_i$ where, $u_i$ is drawn from $N(0,\\sigma^2_{u})$.\n\nThe coefficients $\\beta_0, \\beta_1, \\ldots, \\beta_5$ and the variance components $\\sigma_u$ and $\\sigma_{\\epsilon}$ are estimated using maximum likelihood estimation. The output for the lemurs random intercepts model is in @tbl-lemurs-model-random-int.\n\n\n::: {#tbl-lemurs-model-random-int .cell tbl-cap='Random intercepts model for lemurs data'}\n::: {.cell-output-display}\n\n\n|effect   |group    |term            | estimate| std.error| statistic|\n|:--------|:--------|:---------------|--------:|---------:|---------:|\n|fixed    |         |(Intercept)     |     16.0|     79.07|     0.202|\n|fixed    |         |taxonPCOQ       |    449.9|     67.12|     6.703|\n|fixed    |         |taxonVRUB       |   1021.4|     94.48|    10.811|\n|fixed    |         |sexM            |    -27.1|     45.22|    -0.599|\n|fixed    |         |litter_size     |    -66.8|     45.14|    -1.479|\n|fixed    |         |age             |    147.7|      0.97|   152.338|\n|ran_pars |dlc_id   |sd__(Intercept) |    311.5|          |          |\n|ran_pars |Residual |sd__Observation |    356.3|          |          |\n\n\n:::\n:::\n\n\nThe equation of the fitted model is\n\n$$\n\\begin{aligned}\n\\widehat{\\text{weight}}_{ij} = 15.969 &+  449.932 ~ \\text{taxonPOQ} +  1021.387 ~ \\text{taxonVRUB} \\\\\n&  -27.073 ~ \\text{sexM} - 66.771 ~ \\text{litter\\_size} + 147.719 ~ \\text{age} \\\\\n&\\hat{\\sigma}_u = 311.504 \\hspace{5mm} \\hat{\\sigma}_\\epsilon = 356.275\n\\end{aligned}\n$$\n\n::: {.yourturn latex=\"\"}\nUse the model in @tbl-lemurs-model-random-int.\n\n-   Interpret the coefficient of `age` in the context of the data.\n\n-   Explain what $\\hat{\\sigma}_u = 311.504$ means in the context of the data.[^13-special-topics-4]\n:::\n\n[^13-special-topics-4]: `age:` As a lemur gets one month older, its weight is expected to increase by 147.719 grams, on average, after adjusting for taxon, sex, and litter size.\n\n    $\\hat{\\sigma}_u = 311.504$: The variability in the average weights between lemurs is 311.504. On average, the mean weight of an individual lemur is 311.504 grams away from the overall mean weight of all lemurs.\\\n\n### Random intercepts model in R\n\nRandom intercepts models are fit using the `lmer` function in the `lme4` R package [@lme4]. The syntax for the response and predictor variables is the same as in `lm()`. The grouping variable is specified using the syntax `(1|grouping_var)`. This specifies that the random intercepts are based on `grouping_var`. The syntax for the model in @tbl-lemurs-model-random-int is below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlemurs_fit <- lmer(weight ~ taxon + sex + litter_size + age + \n                     (1|dlc_id), \n                   data = lemurs)\n\nlemurs_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: weight ~ taxon + sex + litter_size + age + (1 | dlc_id)\n   Data: lemurs\nREML criterion at convergence: 54636\nRandom effects:\n Groups   Name        Std.Dev.\n dlc_id   (Intercept) 312     \n Residual             356     \nNumber of obs: 3715, groups:  dlc_id, 248\nFixed Effects:\n(Intercept)    taxonPCOQ    taxonVRUB         sexM  litter_size          age  \n       16.0        449.9       1021.4        -27.1        -66.8        147.7  \n```\n\n\n:::\n:::\n\n\nThe results can be displayed in a tidy format using `tidy` function in the **broom.mixed** R package [@broom.mixed]. The results below are neatly displayed using `kable()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(lemurs_fit) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|effect   |group    |term            | estimate| std.error| statistic|\n|:--------|:--------|:---------------|--------:|---------:|---------:|\n|fixed    |         |(Intercept)     |     16.0|     79.07|     0.202|\n|fixed    |         |taxonPCOQ       |    449.9|     67.12|     6.703|\n|fixed    |         |taxonVRUB       |   1021.4|     94.48|    10.811|\n|fixed    |         |sexM            |    -27.1|     45.22|    -0.599|\n|fixed    |         |litter_size     |    -66.8|     45.14|    -1.479|\n|fixed    |         |age             |    147.7|      0.97|   152.338|\n|ran_pars |dlc_id   |sd__(Intercept) |    311.5|          |          |\n|ran_pars |Residual |sd__Observation |    356.3|          |          |\n\n\n:::\n:::\n\n\n### Further reading\n\nWe have just scratched the surface in this section, but there are many resources for readers interested in learning more about random intercepts models and other types of GLMMs. See *Beyond Multiple Linear Regression* [@roback2021beyond] and *Data Analysis Using Regression and Multilevel/Hierarchical Models* [@gelman2007data] for an in-depth introduction to these topics.\n\n## Decision trees {#sec-decision-trees}\n\nThe models presented in this book thus far have been parametric methods, in which we specify a form of the model then estimate the parameters of that model ([@sec-what-is-regression]). An alternative to this approach are tree-based models, a set of non-parametric methods that split the data based on a series of decision points. These methods are particularly useful if a precise interpretation of the relationship between the response and predictor variables is not needed, but rather a general understanding how to use the predictors to estimate the response is sufficient.\n\nIn the book *Introduction to Statistical Learning 2nd edition, @james2021introduction* \\[pp. 339\\] lists advantages of tree-based models compared to GLMs.\n\n> -   They are easier for others to understand;\n> -   They are believed to better mirror the human decision-making process;\n> -   They can more easily represented visually, making it easier for non-experts to understand them;\n> -   They can use categorical predictors without creating indicator variables.\n\nThis list could be summarized as \"The key advantage to tree-based models is that they are easy for others, especially non-experts, to understand.\" Here we introduce two tree-based models: regression trees for quantitative response variables and classification trees for categorical response variables.\n\n### Regression trees {#sec-regression-trees}\n\nRegression trees are decision trees to model data with quantitative response variables, so they are often an alternative to linear regression. The general idea is to use the predictor variables to split the data into groups of similar observations. For each observation, the predicted value of the response is computed as the mean response among the observations in its group. To illustrate this, let's go back to the total expenditure on basketball programs for Division I NCAA institutions introduced in @sec-ch-transformations. We will use a regression tree to predict `expenditure_m` (total expenditure in millions of dollars) using `type` (private or public institution), `region` (North Central, Northeast, South, West), and `enrollment_th` (total student enrollment in thousands).\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {#fig-ncaa-expenditure .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Original `expenditure_m`](13-special-topics_files/figure-html/fig-ncaa-expenditure-1.png){#fig-ncaa-expenditure-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![Log-transformed `expenditure_m`](13-special-topics_files/figure-html/fig-ncaa-expenditure-2.png){#fig-ncaa-expenditure-2 width=100%}\n:::\n\nDistribution of original and log-transformed `expenditure_m`\n:::\n\n\nThe distribution of `expenditure_m` is heavily right-skewed [@fig-ncaa-expenditure-1], so we will use the log-transformed variable `log(expenditure_m)` in the model [@fig-ncaa-expenditure-2].\n\n::: {.analysis_in_practice latex=\"\"}\nWhen the response variable is strongly skewed, it is good practice to use the transformed version in the regression tree. Though regression trees do not rely on the same assumptions as linear regression, their results can be strongly influenced by extreme observations when the distribution of the response variable is heavily skewed. Predictor variables do not need to be transformed for regression trees, because the tree does not depend on a linear relationship between the response and predictor variables.\n:::\n\nA regression tree is made up of a series of nodes (also called *leaves*) and branches. The **nodes** are the decision-making points at each split (e.g., `enrollment_th < 10?`). The **branches** connect two nodes (e.g, `enrollment_th < 10 = TRUE` and `enrollment_th < 10 = FALSE`). The **terminal nodes** are the points at the end of the tree where the data are no longer split and the predictions are made. The prediction is the mean value of the response variable for the observations in that node.\n\nAt each step, the model searches to find the variable and associated cut point that minimizes the sum of squares residual (SSR) in [@eq-tree-ssr]. This is the same SSR introduced in @sec-slr-sum-sq. Minimizing SSR maximizes the similarity of observations within a node. This process continues until making a new split no longer minimizes the SSR.\n\n$$\nSSR = \\sum_{i = 1}^n(y_i - \\hat{y}_i)^2\n$$ {#eq-tree-ssr}\n\nNow let's fit the regression tree to predict `expenditure_m` using `enrollment_th`, `region`, and `type`. Because the primary objective for the tree is prediction, we split the data into training (80%) and testing (20%) sets ([@sec-training-testing]). This will give us an assessment on how well the model performs on new data.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Regression tree predicting NCAA basketball expenditure](13-special-topics_files/figure-html/fig-ncaa-tree-1.png){#fig-ncaa-tree width=100%}\n:::\n:::\n\n\n@fig-ncaa-tree is the output of the regression tree. In this output, we see the variables and associated cutpoint used to make the split at each step, along with the percentage of observations in each subsequent node. This output also shows the predicted `expenditure_m` in each node.\n\nFor example, the first split is whether `enrollment_th < 12`. About 62% of the observations in the training data have `enrollment_th < 12`, and the mean log(expenditure) for those observations is 1.5 million. In contrast, about 38% of the observations have `enrollment_th >= 12`, and the mean log(expenditure) for those observations is about 2.4 million. If we were to stop there, then 1.5 million would be the predicted log(expenditure) for all observations with `enrollment < 12` and 2.4 million would be the predicted log(expenditure) for all other observations.\n\nLet's use the tree to find the predicted expenditure for a private institution in the South region that has enrollment of 6,000 students. At the first step, we go down the \"Yes\" branch for `enrollment_th < 12`. Next, we go down the \"No\" branch for `type = Public`. Next, we go down the \"No\" branch for `enrollment_th < 4.1`. Next, we go down the branch, \"No\" for `region = Northeast`. Lastly, we go down the \"Yes\" branch for `enrollment_th < 6.3`. This branch leads to the terminal node of $\\widehat{\\log(\\text{expenditure\\_m})} = 2.2$, which is equal to a predicted expenditure of 9.025 ($e^{2.2}$) million dollars.\n\n::: {.yourturn latex=\"\"}\nWhat is the predicted expenditure for a public institution in the West region with enrollment of 20,000 students.[^13-special-topics-5]\n:::\n\n[^13-special-topics-5]: The predicted expenditure is 2.1 million. Note that the fact that it was a public institution was not used based on its path in the decision tree.\n\nWe evaluate the model's performance using the testing data. We compute the predicted expenditures for the observations in the testing data the root mean square error (RSME), introduced in @sec-model-assessment, as a measure of the model performance.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\nThe RMSE for the testing data is 0.506. This is the terms of the response variable, `log(expenditure_m)`, so the error in terms of the original variable is 1.659. This means that the average difference between the observed expenditure and predicted is 1.659 million dollars.\n\n### Classification trees {#sec-classification-trees}\n\nClassification trees are decision trees for predicting categorical outcomes. We might use such a tree as an alternative to logistic regression [@sec-ch-logistic] or multinomial logistic regression [@sec-multinomial]. They are very similar to regression trees with two primary differences. The first is that predictions in the **terminal nodes** are the predicted classes. The second is that the potential variables and associated cutoffs to define each split are evaluated using different criteria. The default in most software is the **Gini Index** shown in [@eq-gini-index]\n\n$$\n\\text{Gini index} = 1 - \\sum_{k = 1}^K p_{mk}^2\n$$ {#eq-gini-index}\n\nwhere $p_{mk}$ is the proportion of observations in the $m^{th}$ node that belong to class $k$. Similar to RSS, the model selects the variable and cutoff that minimizes the Gini index at each step. Low values of the Gini index indicate a large proportion of observations in a given node are from the same class.\n\nLet's go back to the voter frequency data introduced in @sec-voters-data. We'll use a classification tree to predict the `voter_category` (`rarely/never`, `sporadic`, `always`) using `age`, `party_id`, and an additional variable `income_cat`. We split the data into training (80%) and testing sets (20%), so we can evaluate the model's performance on new data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Classification tree voter frequency](13-special-topics_files/figure-html/fig-voters-tree-1.png){#fig-voters-tree width=100%}\n:::\n:::\n\n\n@fig-voters-tree is the output from the classification tree. Something that may stand out is that the predictor `party_id` is not used in the tree. This means there was never a point where using `party_id` was more useful in classifying observations compared to the other predictors.\n\nThe first split in @fig-voters-tree is at `age < 34`. About 21% of the observations have `age < 34`, and this group leads to a terminal node. Among those with `age < 34`, 34% of them are classified as `rarely/never`, 21% are classified as `sporadic`, and 30% are classified as `always` in the data. Therefore, if `age < 34`, the predicted class is `rarely/never` based on the classification tree. There is a bit more work among those with `age >= 34`. The next split is `age < 61`. If `age < 61`, then there is a terminal node with the predicted class `sporadic`. Otherwise, `income_cat` is taken into account, with a split at `income_cat = Less than $40k`. If yes, then the predicted class is `sporadic`; if no, the predicted class is `always`.\n\n::: {.yourturn latex=\"\"}\nBased on @fig-voters-tree, what is the predicted voting frequency for an a 40 year old individual whose party affiliation is Democrat and annual income is \\$70,000?[^13-special-topics-6]\n:::\n\n[^13-special-topics-6]: The predicted voting frequency is sporadic.\n\n### Decision trees in R\n\nWe fit decision trees using the `rpart()` function in the **rpart** R package [@rpart]. The argument `method =` is used to specify the type of decision tree.\n\nBelow is the code for the regression tree fit in @sec-regression-trees. The argument `method = \"anova\"` specifies that we are fitting a regression tree. If we type the name of the tree, we see a summary of the nodes and branches\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncaa_tree <- rpart(log(expenditure_m) ~ enrollment_th + \n                     type + region,\n                   data = ncaa_train,\n                   method = \"anova\")\n\nncaa_tree\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn= 284 \n\nnode), split, n, deviance, yval\n      * denotes terminal node\n\n 1) root 284 165.00 1.840  \n   2) enrollment_th< 11.7 176  65.20 1.510  \n     4) type=Public 95  15.90 1.240  \n       8) enrollment_th< 4.35 22   2.32 0.821 *\n       9) enrollment_th>=4.35 73   8.64 1.360 *\n     5) type=Private 81  34.30 1.820  \n      10) enrollment_th< 4.06 40   5.41 1.500 *\n      11) enrollment_th>=4.06 41  20.70 2.140  \n        22) region=Northeast 18   5.53 1.650 *\n        23) region=North Central,South,West 23   7.60 2.520  \n          46) enrollment_th< 6.32 12   2.62 2.180 *\n          47) enrollment_th>=6.32 11   2.13 2.880 *\n   3) enrollment_th>=11.7 108  49.30 2.370  \n     6) enrollment_th< 31.5 96  42.70 2.290  \n      12) enrollment_th< 18.1 38  15.10 2.080  \n        24) region=North Central,Northeast,West 20   4.98 1.880 *\n        25) region=South 18   8.42 2.300 *\n      13) enrollment_th>=18.1 58  24.70 2.440  \n        26) region=West 19   7.67 2.090 *\n        27) region=North Central,Northeast,South 39  13.60 2.610 *\n     7) enrollment_th>=31.5 12   1.09 3.010 *\n```\n\n\n:::\n:::\n\n\nThe code below is the classification tree from @sec-classification-trees. We use the argument `method = \"class\"` to specify the classification tree. Similar to regression trees, we can type the name of the tree to see a summary of the nodes and branches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvoters_tree <- rpart(voter_category ~ age + party_id +\n                       income_cat + educ, \n                   data = voters_train, \n                   method = \"class\")\n\nvoters_tree\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nn= 4668 \n\nnode), split, n, loss, yval, (yprob)\n      * denotes terminal node\n\n 1) root 4668 2590 sporadic (0.2509 0.4460 0.3031)  \n   2) age< 33.5 973  495 rarely/never (0.4913 0.2127 0.2960) *\n   3) age>=33.5 3695 1820 sporadic (0.1876 0.5074 0.3050)  \n     6) age< 60.5 2017  879 sporadic (0.2558 0.5642 0.1800) *\n     7) age>=60.5 1678  914 always (0.1055 0.4392 0.4553)  \n      14) income_cat=Less than $40k 452  223 sporadic (0.1770 0.5066 0.3164) *\n      15) income_cat=$125k or more,$40-75k,$75-125k 1226  605 always (0.0791 0.4144 0.5065) *\n```\n\n\n:::\n:::\n\n\nThe summaries produced by `rpart()` are challenging to read, so we use the `rpart.plot()` from the **rpart.plot** R package [@rpart.plot] to create a visual representation of the tree. The code below produces the visualization of the regression tree for NCAA basketball expenditures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrpart.plot(ncaa_tree)\n```\n\n::: {.cell-output-display}\n![](13-special-topics_files/figure-html/unnamed-chunk-13-1.png){width=100%}\n:::\n:::\n\n\nPredictions are produced using `predict()`. This will produce a vector of predictions that can be added to the original data frame to evaluate model performance.\n\nThe code below produces the predictions for the testing data from the regression tree predicting NCAA basketball expenditures and saves the predictions as a column in the testing data. The same code is used to produce predictions from the classification tree.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nncaa_test <- ncaa_test |>\n  mutate(predict_expend = predict(ncaa_tree, ncaa_test))\n```\n:::\n\n\nThe predictions are in the same units as the response variable, so in this case, the predicted values are the predicted `log(expenditure_m)`.\n\n### Further reading\n\nOverall, decision trees can be a nice alternative to linear and logistic regression. Their greatest advantage is that they can be easily represented visually and thus easier for non-experts to understand. The two greatest disadvantages to these models, however, are the inferior predictive accuracy compared to other modeling approaches and their sensitivity to small changes in the data [@james2021introduction, pp.340]. In this section, we introduced decision trees, but there is extensive work in tuning (customizing) these models along with more advanced models that take into account multiple trees (e.g., random forest). We refer the reader to Chapter 8 @james2021introduction for an in-depth discussion on the tree-based models.\n\n## Causal inference {#sec-causal}\n\nThroughout this text, we have interpreted the coefficients of regression models to describe the *association* between the response and predictor variables and the \"expected\" change in the response variable based on the model. In other words, we have been bound by the common phrase in statistics \"correlation does not equal causation.\" There are many situations in practice, however, in which we want to make a stronger claim and conclude that \"X causes Y.\" For example, medical researchers developing a new treatment want to know if the treatment causes improved health outcomes. In social sciences, researchers may want to know if a particular social program improves outcomes for individuals living in poverty. Economists want to know the impact of changing economic measures, such as interest rates, on the economy overall. Each of these scenarios requires an analysis that can more thoroughly account for **confounding variables**, underlying variables that impact both the response and predictor variables, so that the impact of the medical treatment, social program, or economic measure can be quantified. We will refer to all of these as *treatment* or *intervention* throughout the rest of the section.\n\nThe ability to make causal claims start with the data. There are two types of data: experimental and observational data. **Experimental data** are data obtained from a randomized-control experiment <!--# is this the correct term--> in which individuals were randomly assigned to the treatment group that receives the intervention or control group that does not receive the intervention. Because individuals are randomly assigned groups, we can assume the only difference between the treatment and control groups is the intervention itself. Therefore, as we interpret the model coefficients associated with the treatment, we can interpret it in terms of how a change in the treatment [**causes**]{.underline} in a change in the response.\n\nThe ideal randomized experiment is often not feasible in practice due to a variety of factors. For example, it may be unethical to assign individuals to a control group and withhold beneficial treatment, or it is not feasible to restrict the behavior of individuals to implement experimental conditions. Therefore, researchers often rely on observational data, even when they want to draw conclusions stronger than a \"correlation\" or \"association\" between some treatment or intervention (predictor) and an outcome (response). To make such causal claims, we use statistical methods to make the observational data \"look\" more like data from a randomized experiment. These methods make up the branch of statistics called *causal inference*.\n\n### Propensity score matching\n\n\n::: {.cell}\n\n:::\n\n\nIn **propensity score matching**, we compute the probability (propensity) an observation is assigned to the treatment group based on a set of confounding variables that directly impact both the response and the likelihood an individual is in the treatment group. We then match individuals in the treatment and control groups who have the same or similar propensities to create a new data set in which the control and treatment groups have similar characteristics. The matched data set is used to estimate the effect of the treatment. <!--# use exchangeability here?-->\n\nLet's apply propensity score matching to evaluate the effect of an educational program, Project ACE: Action for Equity. Project ACE was a \"five year interdisciplinary program aimed to get more underrepresented high school students from disadvantaged backgrounds to get interested in college degrees in engineering as well as biomedical and behavioral sciences\" [@ProjectACE_UTEP]. We will analyze data from @evans2025testing who use propensity score matching to analyze outcomes of high school students. The data are available in `project-ace-data.csv`. We will follow their analysis closely with some modifications, so we refer readers to their article for the full analysis.\n\nWe will use the variables below. The definitions are adapted from @evans2025testing.\n\n-   `Grade`: Grade level (9, 10, 11, 12)\n-   `Gender`: Gender (F, M)\n-   `Ethnicity`: Ethnicity (Hispanic, Non-Hispanic)\n-   `ELL`: Whether student is an English language learner (N, Y)\n-   `Sped`: Whether student is in a special education program (N, Y)\n-   `Homeless`: Whether student is homeless (N, Y)\n-   `Tracking.Pathway`: Whether student was in Project ACE (Treatment) or not (Control)\n-   `Current.GPA`: Grade Point Average (GPA) ranging 0 to 5.0\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of GPA for treatment and control groups](13-special-topics_files/figure-html/fig-response-gpa-1.png){#fig-response-gpa width=100%}\n:::\n:::\n\n\n@fig-response-gpa shows the distribution of the response variable `Current.GPA` for the treatment and control groups. There is a lot of overlap in the distributions, but there does appear to be a higher proportion of students in the treatment group who have higher GPAs. The goal of this analysis is to measure if there is a difference in the GPAs between students in Project ACE versus those not in the program, and if so, the effect of the Project ACE on GPA.\n\nSome variables are associated with both the response and the chance to receiving the treatment. For example, research shows that demographic and socioeconomic variables are associated with academic performance [@evans2025testing]. Because Project ACE is aimed at students who are \"underrepresented\" and from \"disadvantaged backgrounds\", demographic and socioeconomic factors are also associated with the probability of being in the program. We see examples of this in @fig-compare-distributions, where the distributions of three potential covariates differ between control and treatment groups.\n\n\n::: {#fig-compare-distributions .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![`Grade`](13-special-topics_files/figure-html/fig-compare-distributions-1.png){#fig-compare-distributions-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![`Gender`](13-special-topics_files/figure-html/fig-compare-distributions-2.png){#fig-compare-distributions-2 width=100%}\n:::\n\n::: {.cell-output-display}\n![`ELL`](13-special-topics_files/figure-html/fig-compare-distributions-3.png){#fig-compare-distributions-3 width=100%}\n:::\n\nDistribution of Subset of confounding variables for treatment and control groups.\n:::\n\n\nIn a standard regression model, these variables and the other demographic and socioeconomic variables would be confounders that limit the strength of the claim we can make about the effect of the treatment, even if these variables are included as predictors in the model. Therefore, we will match the data in a way such that the distributions of these factors are similar between the treatment and control groups.\n\n::: {.analysis_in_practice latex=\"\"}\nChoosing the variables to include in the propensity score model can be challenging. We often choose these variables based on previous research and collaboration with individuals who are domain experts. Deciding up front which variables are important helps strengthen the analysis conclusions, as there is less potential there are confounding variables impacting the model of the treatment effect.\n:::\n\n<!--# We will just look at a few characteristics here, but will use many more in the PSM-->\n\n<!--# We will not use Free.Lunch bc it is coded as Y for all observations in the available data.-->\n\nThe propensity score model is a logistic regression model where the response variable is the binary indicator for Treatment vs. Control. As shown in @eq-propensity-score-model, we use this model to compute the probability that an individual is in the treatment group. The form of the propensity score model for this analysis is as follows:\n\n$$\n\\begin{aligned}\n\\log\\Big(\\frac{\\pi}{1-\\pi}\\Big) = \\beta_0 &+ \\beta_1 ~ \\text{Grade10} + \\beta_2 ~ \\text{Grade11} + \\beta_3 ~ \\text{Grade12}  \\\\\n& + \\beta_4 ~ \\text{GenderM} + \\beta_5 ~ \\text{EthnicityNon-Hispanic} \\\\\n&+ \\beta_6 ~ \\text{ELL} + \\beta_7 ~ \\text{Sped} + \\beta_8 ~ \\text{Homeless} \n\\end{aligned}\n$$ {#eq-propensity-score-model} where $\\pi$ is the propensity, the probability of being in the treatment group (participating in Project ACE). @tbl-propensity-score-model is the output of the fitted propensity score model. <!--# foot note: All the variables in this model happen to be categorical, but both quantitative and categorical variables can be used in the propensity score model.-->\n\n\n::: {#tbl-propensity-score-model .cell}\n::: {.cell-output-display}\n\n\n|term                               | estimate| std.error| statistic| p.value|\n|:----------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                        |   -1.670|     0.216|    -7.733|   0.000|\n|Grade10                            |    0.539|     0.264|     2.040|   0.041|\n|Grade11                            |    0.566|     0.263|     2.155|   0.031|\n|Grade12                            |    0.314|     0.273|     1.151|   0.250|\n|GenderM                            |   -1.390|     0.206|    -6.731|   0.000|\n|Ethnicity.Hispanic.Y.NNon Hispanic |   -0.498|     0.775|    -0.643|   0.520|\n|ELLY                               |   -0.792|     0.222|    -3.562|   0.000|\n|SpedY                              |    0.017|     0.277|     0.060|   0.952|\n|HomelessY                          |    1.126|     0.649|     1.734|   0.083|\n\n\n:::\n:::\n\n\nIn general, we are not interested in interpreting the coefficients of the propensity score model but rather using it to compute the propensity for each observation. Before using the propensity scores to match, let's take a look at the distribution of propensity scores for the treatment and control group in @fig-propensity-scores.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of propensity scores for treatment and control groups](13-special-topics_files/figure-html/fig-propensity-scores-1.png){#fig-propensity-scores width=100%}\n:::\n:::\n\n\nIn @fig-propensity-scores, we see that the center of the distribution of propensity scores for individuals in the treatment group is higher than the center for the control group. This is what we might expect, because the individuals in the treatment group are more likely to have the characteristics of eligibility to participate in Project ACE.\n\nThe other important feature from this graph is the large overlap between the two distributions. This indicates **common support**, in which individuals in both the treatment and control groups have a nonzero probability of receiving the treatment. In the context of this analysis, this means every student had a non-zero chance of participating in Project ACE. Practically speaking, we use the propensity scores to match observations in the treatment group with an observation in the control group, so there needs to be overlap in the distributions.\n\n\n::: {.cell}\n\n:::\n\n\nNow let's use the propensity scores to match observations. The number of observations in the treatment group is often equal to or less than the number of observations in the control group. Therefore, the matching is done such that each observation in the treatment group is matched to an observation in the control group. Then, the observations in the control group that are not matched are discarded. In the Project ACE analysis, there are 148 observations in the treatment group and 1152 observations in the control group. Therefore, the final matched data set will contain 148 observations in the treatment group and 148 observations in the control group. The unmatched 1004 observations in the control group are discarded.\n\nOne of the most widely used matching approaches is **nearest-neighbor matching**, in which each observation in the treatment group is matched with an observation in the control group with the closest propensity score. @tbl-sample-matches shows three treatment/control pairs in the matched data for the Project ACE analysis.\n\n\n::: {#tbl-sample-matches .cell tbl-cap='Three pairs of matched observations based on the model in @tbl-propensity-score-model. The column `subclass` identifies the matches.'}\n::: {.cell-output-display}\n\n\n|subclass |Tracking.Pathway | propensity_score|\n|:--------|:----------------|----------------:|\n|14       |Control          |            0.367|\n|14       |Treatment        |            0.443|\n|50       |Control          |            0.249|\n|50       |Treatment        |            0.249|\n|118      |Control          |            0.158|\n|118      |Treatment        |            0.158|\n\n\n:::\n:::\n\n\nSometimes there are **exact matches**, where an observation in the treatment group is matched with an observation in the control group with an equal propensity score. Matches 50 and 118 in the table are examples of this. This generally indicates that the two observations are the same in terms of the characteristics included in the propensity score model [@eq-propensity-score-model]. In other cases, such as Match 14, the scores are close but not exact.\n\n\n::: {#tbl-match-14 .cell tbl-cap='Features for observations in Match 14'}\n::: {.cell-output-display}\n\n\n|Tracking.Pathway |Grade |Gender |Ethnicity.Hispanic.Y.N |ELL |Sped |Homeless | propensity_score|\n|:----------------|:-----|:------|:----------------------|:---|:----|:--------|----------------:|\n|Treatment        |12    |F      |Hispanic               |N   |N    |Y        |            0.443|\n|Control          |9     |F      |Hispanic               |N   |N    |Y        |            0.367|\n\n\n:::\n:::\n\n\nFrom @tbl-match-14, we see that the two observations that make up the 14th match are the same in all characteristics except grade. The student in the treatment group is in grade 12, and the student in the control group is in grade 9.\n\n<!--# to add - analysis in practice - what about the nonmatched observations? Do ratios-->\n\nBefore fitting the model to estimate the effect of the treatment, let's take a look at the distributions of the variables we examined in @fig-compare-distributions, and see how the distributions compare between the treatment and control group for the 296 observations in the matched data.\n\n\n::: {#fig-compare-distributions-matched .cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![`Grade`](13-special-topics_files/figure-html/fig-compare-distributions-matched-1.png){#fig-compare-distributions-matched-1 width=100%}\n:::\n\n::: {.cell-output-display}\n![`Gender`](13-special-topics_files/figure-html/fig-compare-distributions-matched-2.png){#fig-compare-distributions-matched-2 width=100%}\n:::\n\n::: {.cell-output-display}\n![`ELL`](13-special-topics_files/figure-html/fig-compare-distributions-matched-3.png){#fig-compare-distributions-matched-3 width=100%}\n:::\n\nDistribution of subset of confounding variables for treatment versus control groups in the matched data.\n:::\n\n\nIn @fig-compare-distributions-matched, the distributions of these student characteristics are now the same for the treatment and control groups (compare to @fig-compare-distributions). For brevity, we only show three variables here, but we could look at the distributions for all variables in the propensity score model [@eq-propensity-score-model]. Now the data look more like what we would expect in a randomized experiment. Therefore, we can be more confident that any differences in the GPA (response variable) are due to the treatment and not underlying confounding variables. <!--# need to make sure I define confounding somewhere-->\n\nOnce we have the matched data set, it's time to evaluate the effect of the treatment. We do this by using a regression model with the treatment as a predictor.\n\n$$\n\\text{GPA} = \\beta_0 + \\beta_1 ~\\text{Treatment} + \\epsilon \\hspace{8mm} \\epsilon \\sim N(0, \\sigma^2_{\\epsilon})\n$$ {#eq-treatment-model} For the Project ACE analysis, the response variable GPA is quantitative, so we use a linear regression model of the form in @eq-treatment-model. The fitted model is in @tbl-model-treatment-effect.\n\n\n::: {#tbl-model-treatment-effect .cell tbl-cap='Model of treatment effect with 95% confidence intervals for coefficients'}\n::: {.cell-output-display}\n\n\n|term                      | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)               |    2.430|     0.069|        35|   0.000|    2.294|      2.57|\n|Tracking.PathwayTreatment |    0.196|     0.098|         2|   0.046|    0.003|      0.39|\n\n\n:::\n:::\n\n\nWe interpret the model just as we interpret other linear regression models (see [@sec-ch-slr] and [@sec-ch-mlr]). In @tbl-model-treatment-effect, the estimated effect of the treatment, participating in Project ACE is 0.196 and the 95% confidence interval is 0.003 to 0.39. This estimate 0.196 is the **average treatment effect (ATE)**, the difference in the expected response between the treatment and control group. Therefore, based on this analysis, we can make a causal relationship between participating in Project ACE and higher GPA, on average. The 95% confidence interval gives a plausible range for the effect in the population.\n\n::: {.yourturn latex=\"\"}\nInterpret the 95% confidence interval for the effect of participating in Project ACE in the context of the data.[^13-special-topics-7]\n:::\n\n[^13-special-topics-7]: We are 95% confident that improvement in GPA from participating in Project ACE is between 0.003 and 0.39 points.\n\nAs we use these results to inform decision-making, one thing to keep in mind is that this is the average treatment effect in the matched population. Therefore, the results may not generalize to the entire population if the discarded individuals in the control group are significantly different from the individuals in the matched group. One way to mitigate this is to include more observations from the control group. Strategies for this are available in the resources at the end of this section.\n\n### Causal inference in R\n\nMuch of the code for causal inference is the code for linear `lm()` and logistic `glm()` models that we've seen in previous chapters. The primarily new code is for creating the matched data set using the propensity scores.\n\nWe compute the propensity scores \"manually\" by fitting a logistic regression model using `glm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npropensity_score_model <- glm(Tracking.Pathway ~ Grade + Gender + \n                                Ethnicity.Hispanic.Y.N + ELL + \n                                Sped + Homeless,\n                        data = ace, \n                        family = \"binomial\")\n```\n:::\n\n\nThe assigned matches are done using the `matchit()` function from the **MatchIt** R package [@MatchIt]. The code below shows the propensity score matching for the Project Ace data.\n\nThe argument `method = \"nearest\"` species to conduct nearest-neighbor matching (the default method), and `distance = \"logit\"` indicates to compute the propensity scores using a logistic regression model. The `matchit()` function will refit the model with propensity scores.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nace_psm <- matchit(Tracking.Pathway ~ Grade + Gender + Ethnicity.Hispanic.Y.N +\n                          Race + ELL + Sped + Homeless,\n                 data = ace,\n                 method = \"nearest\",   \n                 distance = \"logit\")\n\nace_psm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA `matchit` object\n - method: 1:1 nearest neighbor matching without replacement\n - distance: Propensity score\n             - estimated with logistic regression\n - number of obs.: 1300 (original), 296 (matched)\n - target estimand: ATT\n - covariates: Grade, Gender, Ethnicity.Hispanic.Y.N, Race, ELL, Sped, Homeless\n```\n\n\n:::\n:::\n\n\nThis code creates a `matchit` object called `ace_psm` that contains information about the propensity score matching. We retrieve the matched data using the `match.data()` function as shown below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nace_matched <- match.data(ace_psm)\n```\n:::\n\n\nWe use `glimpse()` to see what is in the new matched data set.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 296\nColumns: 17\n$ Student.ID                                        <dbl> 9478, 8268, 9846, 22…\n$ Grade                                             <fct> 12, 12, 12, 12, 11, …\n$ Gender                                            <chr> \"M\", \"M\", \"F\", \"F\", …\n$ Race                                              <chr> \"C\", \"C\", \"C\", \"C\", …\n$ Ethnicity.Hispanic.Y.N                            <chr> \"Hispanic\", \"Hispani…\n$ ELL                                               <chr> \"N\", \"N\", \"N\", \"N\", …\n$ Sped                                              <chr> \"N\", \"N\", \"N\", \"N\", …\n$ Homeless                                          <chr> \"N\", \"N\", \"Y\", \"N\", …\n$ Free.Lunch                                        <chr> \"Y\", \"Y\", \"Y\", \"Y\", …\n$ Migrant                                           <chr> \"N\", \"N\", \"N\", \"N\", …\n$ Current.GPA                                       <dbl> 1.45, 2.96, 2.96, 3.…\n$ Number.of.Classes.Enrolled.in.for.the.school.year <dbl> 7, 7, 7, 7, 7, 7, 7,…\n$ Tracking.Pathway                                  <fct> Control, Treatment, …\n$ propensity_score                                  <dbl> 0.0603, 0.0603, 0.44…\n$ distance                                          <dbl> 0.0590, 0.0590, 0.45…\n$ weights                                           <dbl> 1, 1, 1, 1, 1, 1, 1,…\n$ subclass                                          <fct> 1, 1, 42, 3, 2, 2, 4…\n```\n\n\n:::\n:::\n\n\nThere are some new columns in addition to the columns in the original `ace` tibble. The column `distance` contains the propensity scores. The column `sub.class` identifies the matches. The column `weights` contains sample weights. All observations are equally weighted using the methods introduced in this section. See the resources in @sec-causal-further-reading to learn about propensity score matching that incorporates weighting.\n\nThe `lm` function is used to fit the linear regression model for the treatment effect.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreatment_effect <- lm(Current.GPA ~ Tracking.Pathway, data = ace_matched)\n```\n:::\n\n\n### Further reading {#sec-causal-further-reading}\n\nGiven the plethora of data available today, it is no surprise that causal inference is a rich and growing field in statistics and data science. We refer interested readers to *The effect: An introduction to research design and causality* [@huntington2021effect] and *Causal Inference: The Mixtape* [@cunningham2021causal] for an introduction to causal inference on observational data and *Design and Analysis of Experiments* [@montgomery2017design] for an introduction to experimental design.\n\n## Summary\n\nIn this chapter, we introduced models that are extensions of linear and logistic regression. Specifically, we introduced the multinomial logistic regression model for categorical response variables with at least three levels, the random intercepts model for data with correlated observations, decision trees for prediction, and propensity scores models for causal inference. The goal of this book is to introduce readers to regression analysis, so this chapter is a springboard for readers interested in learning more about modeling. All the resources mentioned throughout the chapter are a nice followup to this text for readers interested in a deeper dive into the special topics introduced here and much more.\n",
    "supporting": [
      "13-special-topics_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}